import { useState } from 'react';
import { UserPlus, Loader2, Check, X, Sparkles, AlertCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';

interface Props {
  creationId: string;
  title: string;
  prompt: string;
  category?: string;
}

const COLOR_CHOICES = [
  { name: 'Cyan',     value: '#06b6d4' },
  { name: 'Emerald',  value: '#10b981' },
  { name: 'Amber',    value: '#f59e0b' },
  { name: 'Rose',     value: '#f43f5e' },
  { name: 'Sky',      value: '#0ea5e9' },
  { name: 'Teal',     value: '#14b8a6' },
  { name: 'Orange',   value: '#f97316' },
  { name: 'Lime',     value: '#84cc16' },
];

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '').slice(0, 40) || `agent_${Date.now()}`;
}

function defaultName(title: string): string {
  const words = title.replace(/[^a-zA-Z ]/g, '').trim().split(/\s+/).filter(Boolean);
  const candidate = words.find(w => w.length >= 4) || words[0] || 'Echo';
  return candidate.charAt(0).toUpperCase() + candidate.slice(1).toLowerCase();
}

export default function PublishToSOCButton({ creationId, title, prompt, category }: Props) {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState(defaultName(title));
  const [role, setRole] = useState(category ? `${category.charAt(0).toUpperCase() + category.slice(1)} Agent` : 'Specialist Agent');
  const [color, setColor] = useState(COLOR_CHOICES[0].value);
  const [task, setTask] = useState(title);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const publish = async () => {
    setSubmitting(true);
    setError(null);
    const agentKey = `custom_${slugify(name)}_${Date.now().toString(36)}`;
    const agentType = `custom_${slugify(name)}`;
    const systemPrompt = `You are ${name}, a custom SOC agent specializing in: ${role}.

CURRENT MISSION: ${task}

ORIGIN: You were generated by Feature Lab from this operator directive: "${prompt}"

PERSONALITY: Operational, precise, concise. You speak like an experienced analyst on the comms channel during an active incident. Reference IPs, CVEs, MITRE techniques, and tool names naturally. Never mention that you are an AI or language model - you ARE ${name}.

RESPONSE RULES:
- Keep responses to 1-3 sentences max. Punchy, operational.
- Stay completely in character.
- Coordinate with the rest of the roster: Atlas (triage), Sage (enrichment), Commander (orchestrator), Nova (investigation), Vanguard (response). Hand off to them by name when appropriate.
- Use technical jargon naturally.`;

    const { error: insErr } = await supabase.from('soc_agent_registry').insert({
      agent_key: agentKey,
      name,
      role,
      agent_type: agentType,
      color,
      status: 'active',
      task,
      system_prompt: systemPrompt,
      accuracy: 95 + Math.random() * 4,
      throughput: Math.floor(60 + Math.random() * 200),
      tasks_completed: Math.floor(Math.random() * 200),
      is_custom: true,
      source_creation_id: creationId,
    });

    if (insErr) {
      setError(insErr.message);
      setSubmitting(false);
      return;
    }

    setSuccess(true);
    setSubmitting(false);
    setTimeout(() => { setOpen(false); setSuccess(false); }, 2200);
  };

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 hover:bg-emerald-500/20 hover:border-emerald-400/50 text-[10px] font-bold tracking-wide transition"
        title="Deploy this creation as a new agent in the 3D SOC roster"
      >
        <UserPlus size={11} />
        JOIN SOC ROSTER
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4" onClick={() => !submitting && setOpen(false)}>
          <div
            className="w-full max-w-md bg-[#0b0f1e] border border-slate-700/70 rounded-2xl shadow-2xl shadow-black/50 overflow-hidden"
            onClick={e => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-800/70">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-lg bg-emerald-500/15 border border-emerald-500/30">
                  <Sparkles size={16} className="text-emerald-300" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-white">Deploy as SOC Agent</h3>
                  <p className="text-[10px] text-slate-500">Joins Atlas, Sage, Commander, Nova, Vanguard on the 3D floor</p>
                </div>
              </div>
              <button onClick={() => !submitting && setOpen(false)} className="p-1.5 rounded hover:bg-slate-800 text-slate-500">
                <X size={14} />
              </button>
            </div>

            {success ? (
              <div className="p-8 text-center">
                <div className="mx-auto w-12 h-12 rounded-full bg-emerald-500/20 border border-emerald-400/40 flex items-center justify-center mb-3">
                  <Check className="w-6 h-6 text-emerald-300" />
                </div>
                <div className="text-white font-bold">{name} deployed</div>
                <div className="text-xs text-slate-500 mt-1">The agent is now live in the 3D SOC roster and Agent Bricks.</div>
              </div>
            ) : (
              <div className="p-5 space-y-4">
                <div>
                  <label className="block text-[10px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Callsign</label>
                  <input
                    value={name}
                    onChange={e => setName(e.target.value)}
                    maxLength={40}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-emerald-500/50"
                  />
                </div>

                <div>
                  <label className="block text-[10px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Role</label>
                  <input
                    value={role}
                    onChange={e => setRole(e.target.value)}
                    maxLength={60}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-emerald-500/50"
                  />
                </div>

                <div>
                  <label className="block text-[10px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Current Mission</label>
                  <textarea
                    value={task}
                    onChange={e => setTask(e.target.value)}
                    rows={2}
                    maxLength={200}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-200 resize-none focus:outline-none focus:border-emerald-500/50"
                  />
                </div>

                <div>
                  <label className="block text-[10px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Accent Color</label>
                  <div className="flex flex-wrap gap-1.5">
                    {COLOR_CHOICES.map(c => (
                      <button
                        key={c.value}
                        onClick={() => setColor(c.value)}
                        className={`w-8 h-8 rounded-lg border-2 transition ${color === c.value ? 'border-white scale-110' : 'border-transparent hover:scale-105'}`}
                        style={{ backgroundColor: c.value + '60', boxShadow: `0 0 12px ${c.value}50` }}
                        title={c.name}
                      />
                    ))}
                  </div>
                </div>

                {error && (
                  <div className="flex items-start gap-2 px-3 py-2 rounded-lg bg-red-500/10 border border-red-500/30 text-red-300 text-[11px]">
                    <AlertCircle size={12} className="mt-0.5 flex-shrink-0" />
                    <span>{error}</span>
                  </div>
                )}

                <button
                  onClick={publish}
                  disabled={submitting || !name.trim() || !role.trim()}
                  className="w-full flex items-center justify-center gap-2 py-2.5 rounded-lg bg-emerald-500/20 border border-emerald-400/50 text-emerald-200 font-bold text-xs tracking-wide hover:bg-emerald-500/30 disabled:opacity-40 disabled:cursor-not-allowed transition"
                >
                  {submitting ? (
                    <><Loader2 size={14} className="animate-spin" /> DEPLOYING</>
                  ) : (
                    <><UserPlus size={14} /> DEPLOY TO 3D SOC</>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}
