import { supabase } from './supabase';

interface DiscoveredPattern {
  id: string;
  pattern_name: string;
  pattern_type: string;
  event_sequence: any[];
  occurrence_count: number;
  confidence_score: number;
  threat_level: string;
  is_anomaly: boolean;
  description: string;
  indicators: any[];
}

interface CorrelationRule {
  rule_name: string;
  rule_description: string;
  rule_logic: any;
  source_pattern_id: string;
  severity: string;
  status: string;
  confidence_score: number;
  generated_by: string;
  agent_reasoning: string;
  tags: string[];
}

export class AICorrelationAgent {
  private agentType = 'correlation_generator';

  async analyzePatternAndGenerateRule(pattern: DiscoveredPattern): Promise<CorrelationRule | null> {
    const startTime = Date.now();

    try {
      const reasoning = this.generateReasoning(pattern);
      const rule = this.createCorrelationRule(pattern, reasoning);

      await this.logAgentActivity(
        'rule_created',
        { pattern_id: pattern.id, pattern_name: pattern.pattern_name },
        rule,
        reasoning,
        rule.confidence_score,
        Date.now() - startTime
      );

      return rule;
    } catch (error) {
      console.error('Error generating correlation rule:', error);
      await this.logAgentActivity(
        'rule_creation_failed',
        { pattern_id: pattern.id, error: String(error) },
        {},
        'Failed to create correlation rule',
        0,
        Date.now() - startTime
      );
      return null;
    }
  }

  private generateReasoning(pattern: DiscoveredPattern): string {
    const reasons: string[] = [];

    if (pattern.threat_level === 'critical' || pattern.threat_level === 'high') {
      reasons.push(`High threat level (${pattern.threat_level}) indicates potential security risk requiring immediate correlation.`);
    }

    if (pattern.occurrence_count > 10) {
      reasons.push(`Pattern has occurred ${pattern.occurrence_count} times, suggesting a repeatable attack sequence.`);
    }

    if (pattern.is_anomaly) {
      reasons.push(`Identified as anomalous behavior, deviating from established baseline patterns.`);
    }

    if (pattern.confidence_score >= 80) {
      reasons.push(`High confidence score (${pattern.confidence_score}%) indicates strong statistical significance.`);
    }

    if (pattern.pattern_type === 'threat_sequence') {
      reasons.push(`Detected as a threat sequence with ${pattern.event_sequence.length} distinct stages.`);
    }

    if (pattern.pattern_type === 'zero_day_indicator') {
      reasons.push(`Exhibits characteristics of zero-day exploit activity, requiring proactive detection.`);
    }

    const eventTypes = pattern.event_sequence.map((e: any) => e.event_type || e.type);
    if (eventTypes.includes('failed_login') && eventTypes.includes('privilege_escalation')) {
      reasons.push(`Sequence includes authentication failure followed by privilege escalation - classic attack pattern.`);
    }

    if (eventTypes.includes('data_exfiltration') || eventTypes.includes('suspicious_transfer')) {
      reasons.push(`Pattern includes data exfiltration indicators, suggesting data theft attempt.`);
    }

    return reasons.join(' ');
  }

  private createCorrelationRule(pattern: DiscoveredPattern, reasoning: string): CorrelationRule {
    const eventSequence = pattern.event_sequence.map((e: any) => e.event_type || e.type || e);

    const ruleLogic = {
      conditions: [
        {
          type: 'sequence',
          events: eventSequence,
          time_window: '1 hour',
          order: 'sequential'
        },
        {
          type: 'threshold',
          field: 'occurrence_count',
          operator: '>=',
          value: Math.max(2, Math.floor(pattern.occurrence_count / 2))
        }
      ],
      actions: [
        {
          type: 'create_alert',
          severity: pattern.threat_level,
          title: `Detected: ${pattern.pattern_name}`,
          description: pattern.description
        },
        {
          type: 'enrich_events',
          add_tags: [`pattern:${pattern.pattern_name}`, `auto_correlation`]
        }
      ],
      metadata: {
        pattern_type: pattern.pattern_type,
        is_anomaly: pattern.is_anomaly,
        original_occurrence_count: pattern.occurrence_count
      }
    };

    const tags = [
      'ai_generated',
      pattern.pattern_type,
      pattern.threat_level,
      pattern.is_anomaly ? 'anomaly' : 'known_pattern'
    ];

    if (pattern.pattern_type === 'zero_day_indicator') {
      tags.push('zero_day', 'advanced_threat');
    }

    const confidenceScore = this.calculateRuleConfidence(pattern);

    return {
      rule_name: `Auto: ${pattern.pattern_name}`,
      rule_description: `${pattern.description} - This rule was automatically generated by the AI correlation agent based on discovered pattern analysis.`,
      rule_logic: ruleLogic,
      source_pattern_id: pattern.id,
      severity: this.mapThreatLevelToSeverity(pattern.threat_level),
      status: confidenceScore >= 70 ? 'active' : 'testing',
      confidence_score: confidenceScore,
      generated_by: 'ai_agent',
      agent_reasoning: reasoning,
      tags
    };
  }

  private calculateRuleConfidence(pattern: DiscoveredPattern): number {
    let confidence = pattern.confidence_score;

    if (pattern.occurrence_count > 20) confidence += 10;
    else if (pattern.occurrence_count > 10) confidence += 5;

    if (pattern.is_anomaly) confidence += 5;

    if (pattern.threat_level === 'critical') confidence += 10;
    else if (pattern.threat_level === 'high') confidence += 5;

    if (pattern.event_sequence.length >= 3) confidence += 5;

    return Math.min(100, confidence);
  }

  private mapThreatLevelToSeverity(threatLevel: string): string {
    const mapping: { [key: string]: string } = {
      critical: 'critical',
      high: 'high',
      medium: 'medium',
      low: 'low'
    };
    return mapping[threatLevel] || 'medium';
  }

  private async logAgentActivity(
    activityType: string,
    sourceData: any,
    result: any,
    reasoning: string,
    confidence: number,
    executionTimeMs: number
  ): Promise<void> {
    try {
      await supabase.from('ai_agent_activity').insert({
        agent_type: this.agentType,
        activity_type: activityType,
        source_data: sourceData,
        result,
        reasoning,
        confidence,
        execution_time_ms: executionTimeMs
      });
    } catch (error) {
      console.error('Error logging agent activity:', error);
    }
  }

  async processAllPatterns(): Promise<void> {
    try {
      const { data: patterns, error } = await supabase
        .from('discovered_patterns')
        .select('*')
        .gte('confidence_score', 60)
        .order('threat_level', { ascending: false });

      if (error) throw error;

      if (!patterns || patterns.length === 0) {
        console.log('No patterns found to process');
        return;
      }

      for (const pattern of patterns) {
        const { data: existingRule } = await supabase
          .from('correlation_rules')
          .select('id')
          .eq('source_pattern_id', pattern.id)
          .maybeSingle();

        if (!existingRule) {
          const rule = await this.analyzePatternAndGenerateRule(pattern);

          if (rule) {
            await supabase.from('correlation_rules').insert(rule);
            console.log(`Generated correlation rule for pattern: ${pattern.pattern_name}`);
          }
        }
      }
    } catch (error) {
      console.error('Error processing patterns:', error);
    }
  }

  async getAgentStatistics(): Promise<any> {
    try {
      const { data: activityData } = await supabase
        .from('ai_agent_activity')
        .select('*')
        .eq('agent_type', this.agentType)
        .order('created_at', { ascending: false })
        .limit(100);

      const { data: rulesData } = await supabase
        .from('correlation_rules')
        .select('*')
        .eq('generated_by', 'ai_agent');

      const totalRulesCreated = rulesData?.length || 0;
      const activeRules = rulesData?.filter(r => r.status === 'active').length || 0;
      const avgConfidence = rulesData?.reduce((sum, r) => sum + r.confidence_score, 0) / (totalRulesCreated || 1);

      const recentActivity = activityData?.slice(0, 10) || [];

      return {
        totalRulesCreated,
        activeRules,
        testingRules: totalRulesCreated - activeRules,
        avgConfidence: avgConfidence.toFixed(2),
        recentActivity,
        lastActivity: activityData?.[0]?.created_at || null
      };
    } catch (error) {
      console.error('Error getting agent statistics:', error);
      return null;
    }
  }
}

export const aiCorrelationAgent = new AICorrelationAgent();
