apiVersion: v1
kind: Service
metadata:
  name: {{ include "collector.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.syslogUDP }}
      targetPort: syslog-udp
      protocol: UDP
      name: syslog-udp
    - port: {{ .Values.service.syslogTCP }}
      targetPort: syslog-tcp
      protocol: TCP
      name: syslog-tcp
    - port: {{ .Values.service.httpListener }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collector.fullname" . }}-secret
type: Opaque
data:
  token: {{ .Values.controlPlane.token | b64enc | quote }}
---
{{- if .Values.dna.custom }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collector.fullname" . }}-dna
data:
  custom.yaml: |
    {{ .Values.dna.custom | nindent 4 }}
{{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "collector.fullname" . }}-buffer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
