/*
  # Populate Alerts System with Mock Data

  This migration adds realistic security alerts from various detection sources.

  ## Mock Data Included
  - 50+ diverse security alerts covering multiple categories
  - Various alert sources: IDS, EDR, SIEM, WAF, Email Gateway, DLP, etc.
  - Different severity levels: low, medium, high, critical
  - Multiple statuses: open, acknowledged, investigating, resolved
  - MITRE ATT&CK framework mappings
  - Confidence scores and metadata
  - Links to related cases where applicable

  ## Alert Categories Covered
  - Malware detections
  - Network intrusions
  - Privilege escalations
  - Data exfiltration
  - Brute force attacks
  - Phishing attempts
  - Suspicious DNS queries
  - Unauthorized access
  - Policy violations
*/

-- Insert comprehensive alert mock data
INSERT INTO alerts (
  alert_id, title, description, severity, status, alert_type, source,
  source_ip, dest_ip, user_id, hostname, rule_id, rule_name,
  mitre_tactic, mitre_technique, confidence_score, false_positive,
  assigned_to, tags, metadata, created_at, updated_at, acknowledged_at, resolved_at
) VALUES
  -- Critical Active Alerts
  (
    'ALR-2025-00001',
    'Ransomware Encryption Activity Detected',
    'Multiple files with ransomware-associated extensions detected on file server. Mass file modification events observed.',
    'critical',
    'investigating',
    'malware',
    'EDR',
    '192.168.10.45',
    NULL,
    'admin-fs01',
    'FS-PROD-01',
    'EDR-RANSOMWARE-001',
    'Ransomware File Encryption Pattern',
    'TA0040',
    'T1486',
    98,
    false,
    'SOC Team Alpha',
    '["ransomware", "file-encryption", "critical-system"]'::jsonb,
    '{"files_affected": 1247, "encryption_speed": "high", "ransomware_family": "BlackCat"}'::jsonb,
    NOW() - INTERVAL '2 hours 15 minutes',
    NOW() - INTERVAL '10 minutes',
    NOW() - INTERVAL '2 hours 10 minutes',
    NULL
  ),
  (
    'ALR-2025-00002',
    'APT Malware - Keylogger Detected',
    'Advanced keylogger with network communication capabilities discovered on executive laptop.',
    'critical',
    'investigating',
    'malware',
    'EDR',
    '10.0.50.142',
    '185.220.101.45',
    'ceo',
    'EXEC-LAPTOP-01',
    'EDR-KEYLOG-002',
    'Keylogger with C2 Communication',
    'TA0009',
    'T1056.001',
    95,
    false,
    'Incident Response Team',
    '["apt", "keylogger", "executive", "data-theft"]'::jsonb,
    '{"c2_server": "185.220.101.45", "data_exfil_bytes": 45678, "apt_group": "APT29"}'::jsonb,
    NOW() - INTERVAL '7 hours 30 minutes',
    NOW() - INTERVAL '5 minutes',
    NOW() - INTERVAL '7 hours',
    NULL
  ),
  (
    'ALR-2025-00003',
    'Large-Scale Data Exfiltration Attempt',
    'Unusual outbound data transfer of 15GB to external cloud storage during non-business hours.',
    'high',
    'investigating',
    'data_exfiltration',
    'DLP',
    '192.168.45.78',
    '54.239.28.85',
    'user234',
    'WS-SALES-023',
    'DLP-EXFIL-003',
    'Large Data Transfer to Cloud Storage',
    'TA0010',
    'T1567.002',
    87,
    false,
    'SOC Team Alpha',
    '["data-exfil", "cloud-storage", "insider-threat"]'::jsonb,
    '{"bytes_transferred": 16106127360, "destination_service": "Dropbox", "file_types": ["xlsx", "pdf", "docx"]}'::jsonb,
    NOW() - INTERVAL '5 hours 45 minutes',
    NOW() - INTERVAL '15 minutes',
    NOW() - INTERVAL '5 hours 30 minutes',
    NULL
  ),
  (
    'ALR-2025-00004',
    'Privilege Escalation via Kernel Exploit',
    'Multiple attempts to exploit kernel vulnerability for root access detected on production server.',
    'critical',
    'acknowledged',
    'privilege_escalation',
    'HIDS',
    '192.168.100.23',
    NULL,
    'webapp-user',
    'PROD-WEB-03',
    'HIDS-PRIV-004',
    'Linux Kernel Privilege Escalation',
    'TA0004',
    'T1068',
    92,
    false,
    'SOC Team Beta',
    '["privilege-escalation", "linux", "kernel-exploit"]'::jsonb,
    '{"exploit_attempts": 7, "cve": "CVE-2024-XXXX", "success": false}'::jsonb,
    NOW() - INTERVAL '3 hours 20 minutes',
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '3 hours',
    NULL
  ),
  (
    'ALR-2025-00005',
    'Brute Force Attack Against VPN Gateway',
    'Automated authentication attack with 15,000+ failed login attempts detected.',
    'high',
    'acknowledged',
    'brute_force',
    'VPN Gateway',
    '203.0.113.45',
    '198.51.100.10',
    NULL,
    'VPN-GW-01',
    'VPN-BRUTE-005',
    'VPN Brute Force Attack',
    'TA0006',
    'T1110.001',
    94,
    false,
    'Security Analyst - Sarah Chen',
    '["brute-force", "vpn", "authentication"]'::jsonb,
    '{"failed_attempts": 15234, "targeted_accounts": ["admin", "vpnuser", "support"], "attack_duration_minutes": 120}'::jsonb,
    NOW() - INTERVAL '18 hours',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '17 hours',
    NULL
  ),

  -- High Severity Active Alerts
  (
    'ALR-2025-00006',
    'Suspicious DNS Queries to Known C2 Domains',
    'Multiple internal hosts querying domains associated with known malware command and control infrastructure.',
    'high',
    'investigating',
    'command_control',
    'DNS Monitor',
    '192.168.25.156',
    '8.8.8.8',
    'user891',
    'WS-IT-045',
    'DNS-C2-006',
    'Known C2 Domain Query',
    'TA0011',
    'T1071.004',
    89,
    false,
    'Threat Intel Team',
    '["c2", "dns", "malware-comms"]'::jsonb,
    '{"c2_domains": ["evil-domain.ru", "malware-c2.com"], "query_count": 47, "infected_hosts": 5}'::jsonb,
    NOW() - INTERVAL '4 hours 10 minutes',
    NOW() - INTERVAL '20 minutes',
    NOW() - INTERVAL '3 hours 55 minutes',
    NULL
  ),
  (
    'ALR-2025-00007',
    'Unauthorized Database Access Attempt',
    'Multiple failed database authentication attempts followed by suspicious query patterns.',
    'high',
    'open',
    'unauthorized_access',
    'Database Monitor',
    '10.10.25.89',
    '10.10.1.50',
    'contractor_temp',
    'DB-PROD-01',
    'DB-UNAUTH-007',
    'Unauthorized Database Access Pattern',
    'TA0006',
    'T1078',
    85,
    false,
    NULL,
    '["database", "unauthorized-access", "sql"]'::jsonb,
    '{"failed_auth_attempts": 12, "suspicious_queries": 156, "tables_accessed": ["customers", "financial_records"]}'::jsonb,
    NOW() - INTERVAL '1 hour 30 minutes',
    NOW() - INTERVAL '1 hour 30 minutes',
    NULL,
    NULL
  ),
  (
    'ALR-2025-00008',
    'Port Scan Detected from Internal Network',
    'Comprehensive port scanning activity targeting multiple internal servers.',
    'medium',
    'investigating',
    'reconnaissance',
    'IDS',
    '192.168.30.78',
    '192.168.0.0/16',
    'unknown',
    'WS-UNKNOWN-078',
    'IDS-PORTSCAN-008',
    'Internal Network Port Scan',
    'TA0043',
    'T1046',
    91,
    false,
    'Network Security Team',
    '["port-scan", "reconnaissance", "internal"]'::jsonb,
    '{"ports_scanned": 1024, "hosts_targeted": 156, "scan_type": "SYN"}'::jsonb,
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '1 hour',
    NOW() - INTERVAL '5 hours 45 minutes',
    NULL
  ),
  (
    'ALR-2025-00009',
    'Phishing Email with Malicious Attachment',
    'Sophisticated phishing email with weaponized document detected and quarantined.',
    'high',
    'resolved',
    'phishing',
    'Email Gateway',
    '198.51.100.89',
    NULL,
    'finance-team@company.com',
    'MAIL-GW-01',
    'EMAIL-PHISH-009',
    'Phishing with Malicious Macro',
    'TA0001',
    'T1566.001',
    93,
    false,
    'Security Analyst - John Smith',
    '["phishing", "malware", "quarantined"]'::jsonb,
    '{"recipients": 47, "clicked_count": 3, "malware_family": "Emotet", "quarantined": true}'::jsonb,
    NOW() - INTERVAL '1 day 20 hours',
    NOW() - INTERVAL '1 day 1 hour',
    NOW() - INTERVAL '1 day 19 hours',
    NOW() - INTERVAL '1 day 1 hour'
  ),
  (
    'ALR-2025-00010',
    'Cryptocurrency Mining Activity',
    'Unauthorized cryptomining software detected consuming excessive CPU resources.',
    'medium',
    'resolved',
    'malware',
    'EDR',
    '192.168.75.134',
    '45.76.123.89',
    'user456',
    'WS-RND-087',
    'EDR-CRYPTO-010',
    'Cryptocurrency Mining Detection',
    'TA0040',
    'T1496',
    96,
    false,
    'Security Analyst - Mike Torres',
    '["cryptomining", "resource-abuse", "malware"]'::jsonb,
    '{"mining_pool": "pool.minexmr.com", "cpu_usage": 98, "coins_mined": 0.0023, "duration_hours": 72}'::jsonb,
    NOW() - INTERVAL '3 days 5 hours',
    NOW() - INTERVAL '10 hours',
    NOW() - INTERVAL '3 days 4 hours',
    NOW() - INTERVAL '10 hours'
  ),

  -- Medium Severity Alerts
  (
    'ALR-2025-00011',
    'Multiple Failed SSH Login Attempts',
    'Repeated failed SSH authentication attempts from external IP address.',
    'medium',
    'acknowledged',
    'brute_force',
    'SSH Logs',
    '45.142.212.67',
    '203.0.113.15',
    'root',
    'WEB-SERVER-02',
    'SSH-BRUTE-011',
    'SSH Brute Force Pattern',
    'TA0006',
    'T1110',
    78,
    false,
    'SOC Team Beta',
    '["ssh", "brute-force", "external-attack"]'::jsonb,
    '{"failed_attempts": 234, "usernames_tried": ["root", "admin", "user"], "attack_duration_minutes": 45}'::jsonb,
    NOW() - INTERVAL '12 hours',
    NOW() - INTERVAL '8 hours',
    NOW() - INTERVAL '11 hours 30 minutes',
    NULL
  ),
  (
    'ALR-2025-00012',
    'Suspicious PowerShell Execution',
    'Obfuscated PowerShell command with base64 encoding detected on workstation.',
    'high',
    'open',
    'execution',
    'EDR',
    '10.0.45.23',
    NULL,
    'user789',
    'WS-MARKETING-12',
    'EDR-PS-012',
    'Suspicious PowerShell Command',
    'TA0002',
    'T1059.001',
    82,
    false,
    NULL,
    '["powershell", "obfuscation", "suspicious-execution"]'::jsonb,
    '{"command_length": 2048, "base64_detected": true, "parent_process": "winword.exe"}'::jsonb,
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '45 minutes',
    NULL,
    NULL
  ),
  (
    'ALR-2025-00013',
    'Web Application SQL Injection Attempt',
    'Multiple SQL injection patterns detected in web application requests.',
    'medium',
    'resolved',
    'web_attack',
    'WAF',
    '198.18.0.45',
    '203.0.113.100',
    NULL,
    'WEB-APP-01',
    'WAF-SQLI-013',
    'SQL Injection Attack Pattern',
    'TA0001',
    'T1190',
    88,
    false,
    'AppSec Team',
    '["sql-injection", "waf-blocked", "web-app"]'::jsonb,
    '{"attack_patterns": 23, "blocked_requests": 23, "vulnerability_found": false}'::jsonb,
    NOW() - INTERVAL '6 days',
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '5 days 23 hours',
    NOW() - INTERVAL '5 days'
  ),
  (
    'ALR-2025-00014',
    'Rogue DHCP Server Detected',
    'Unauthorized DHCP server discovered on corporate network segment.',
    'high',
    'investigating',
    'network_attack',
    'Network Monitor',
    '192.168.99.254',
    NULL,
    NULL,
    'ROGUE-DEVICE',
    'NET-ROGUE-014',
    'Rogue DHCP Server Detection',
    'TA0006',
    'T1557.002',
    90,
    false,
    'Network Security Team',
    '["rogue-dhcp", "man-in-the-middle", "network"]'::jsonb,
    '{"ip_leases_issued": 12, "network_segment": "192.168.99.0/24", "mac_address": "00:11:22:33:44:55"}'::jsonb,
    NOW() - INTERVAL '8 hours',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '7 hours 45 minutes',
    NULL
  ),
  (
    'ALR-2025-00015',
    'Sensitive Data Exposed in Log Files',
    'Credit card numbers and PII detected in application log files.',
    'high',
    'acknowledged',
    'data_leak',
    'DLP',
    '10.0.15.67',
    NULL,
    'app-service',
    'APP-SERVER-05',
    'DLP-LEAK-015',
    'Sensitive Data in Logs',
    'TA0009',
    'T1005',
    95,
    false,
    'DevSecOps Team',
    '["data-leak", "pii", "compliance"]'::jsonb,
    '{"records_exposed": 1247, "data_types": ["credit_card", "ssn", "email"], "log_size_mb": 450}'::jsonb,
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day 23 hours',
    NULL
  ),

  -- Additional Diverse Alerts
  (
    'ALR-2025-00016',
    'Suspicious Registry Modification',
    'Windows registry keys associated with persistence mechanisms modified.',
    'medium',
    'investigating',
    'persistence',
    'EDR',
    '192.168.50.89',
    NULL,
    'user234',
    'WS-FINANCE-34',
    'EDR-REG-016',
    'Persistence Registry Modification',
    'TA0003',
    'T1547.001',
    84,
    false,
    'SOC Team Alpha',
    '["registry", "persistence", "windows"]'::jsonb,
    '{"registry_keys": ["HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"], "action": "create"}'::jsonb,
    NOW() - INTERVAL '3 hours',
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '2 hours 45 minutes',
    NULL
  ),
  (
    'ALR-2025-00017',
    'DDoS Attack Pattern Detected',
    'Large volume of SYN packets from distributed sources targeting web server.',
    'high',
    'resolved',
    'ddos',
    'IDS',
    'multiple',
    '203.0.113.100',
    NULL,
    'WEB-DMZ-01',
    'IDS-DDOS-017',
    'DDoS SYN Flood Attack',
    'TA0040',
    'T1498',
    93,
    false,
    'Network Operations',
    '["ddos", "syn-flood", "availability"]'::jsonb,
    '{"packets_per_second": 125000, "source_ips": 450, "traffic_increase_percent": 1200}'::jsonb,
    NOW() - INTERVAL '10 hours',
    NOW() - INTERVAL '9 hours',
    NOW() - INTERVAL '9 hours 55 minutes',
    NOW() - INTERVAL '9 hours'
  ),
  (
    'ALR-2025-00018',
    'Lateral Movement via PSExec',
    'PSExec tool used to execute commands on remote systems across network.',
    'high',
    'open',
    'lateral_movement',
    'EDR',
    '10.0.25.45',
    '10.0.25.89',
    'admin_temp',
    'WS-IT-025',
    'EDR-PSEXEC-018',
    'PSExec Remote Execution',
    'TA0008',
    'T1021.002',
    87,
    false,
    NULL,
    '["psexec", "lateral-movement", "remote-exec"]'::jsonb,
    '{"target_systems": ["10.0.25.89", "10.0.25.90", "10.0.25.91"], "commands_executed": 15}'::jsonb,
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '2 hours',
    NULL,
    NULL
  ),
  (
    'ALR-2025-00019',
    'USB Device Policy Violation',
    'Unauthorized USB storage device connected to restricted workstation.',
    'medium',
    'acknowledged',
    'policy_violation',
    'DLP',
    '192.168.80.45',
    NULL,
    'user567',
    'WS-SECURE-09',
    'DLP-USB-019',
    'Unauthorized USB Storage Device',
    'TA0010',
    'T1052.001',
    100,
    false,
    'Security Operations',
    '["usb", "policy-violation", "removable-media"]'::jsonb,
    '{"device_type": "USB Flash Drive", "vendor": "Kingston", "capacity_gb": 64, "files_copied": 0}'::jsonb,
    NOW() - INTERVAL '5 hours',
    NOW() - INTERVAL '4 hours',
    NOW() - INTERVAL '4 hours 50 minutes',
    NULL
  ),
  (
    'ALR-2025-00020',
    'Tor Network Connection Detected',
    'Workstation established connection to Tor network exit node.',
    'medium',
    'investigating',
    'proxy',
    'Network Monitor',
    '192.168.45.123',
    '185.220.101.15',
    'user890',
    'WS-SALES-078',
    'NET-TOR-020',
    'Tor Network Connection',
    'TA0011',
    'T1090.003',
    76,
    false,
    'SOC Team Beta',
    '["tor", "proxy", "anonymization"]'::jsonb,
    '{"tor_node": "185.220.101.15", "data_transferred_mb": 45, "duration_minutes": 120}'::jsonb,
    NOW() - INTERVAL '1 day 2 hours',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day 1 hour 45 minutes',
    NULL
  ),

  -- Low Severity and False Positives
  (
    'ALR-2025-00021',
    'High Volume of DNS Queries',
    'Abnormally high DNS query rate detected from workstation.',
    'low',
    'resolved',
    'anomaly',
    'DNS Monitor',
    '192.168.15.67',
    '8.8.8.8',
    'user123',
    'WS-DEV-023',
    'DNS-VOL-021',
    'High DNS Query Volume',
    'TA0011',
    'T1071.004',
    65,
    true,
    'SOC Team Alpha',
    '["dns", "volume-anomaly", "false-positive"]'::jsonb,
    '{"queries_per_minute": 450, "cause": "Development testing", "legitimate": true}'::jsonb,
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '1 day 18 hours',
    NOW() - INTERVAL '1 day 23 hours',
    NOW() - INTERVAL '1 day 18 hours'
  ),
  (
    'ALR-2025-00022',
    'Unusual Login Time',
    'User authentication outside typical working hours.',
    'low',
    'closed',
    'anomaly',
    'SIEM',
    '192.168.10.23',
    NULL,
    'user345',
    'WS-SUPPORT-12',
    'SIEM-TIME-022',
    'Unusual Authentication Time',
    'TA0001',
    'T1078',
    45,
    true,
    'SOC Team Beta',
    '["authentication", "time-anomaly", "false-positive"]'::jsonb,
    '{"login_time": "02:30 AM", "user_explanation": "Emergency maintenance", "approved": true}'::jsonb,
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '2 days 20 hours',
    NOW() - INTERVAL '2 days 23 hours',
    NOW() - INTERVAL '2 days 20 hours'
  ),

  -- Recent High Priority Alerts
  (
    'ALR-2025-00023',
    'Suspicious Process Injection Detected',
    'Process injection technique observed, potentially indicating malware activity.',
    'high',
    'open',
    'defense_evasion',
    'EDR',
    '10.0.67.89',
    NULL,
    'user678',
    'WS-HR-045',
    'EDR-INJECT-023',
    'Process Injection Detection',
    'TA0005',
    'T1055',
    88,
    false,
    NULL,
    '["process-injection", "defense-evasion", "malware"]'::jsonb,
    '{"source_process": "svchost.exe", "target_process": "explorer.exe", "injection_type": "CreateRemoteThread"}'::jsonb,
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '30 minutes',
    NULL,
    NULL
  ),
  (
    'ALR-2025-00024',
    'Credential Dumping Attempt',
    'Attempt to access LSASS memory for credential extraction detected.',
    'critical',
    'open',
    'credential_access',
    'EDR',
    '192.168.30.45',
    NULL,
    'user901',
    'WS-IT-067',
    'EDR-LSASS-024',
    'LSASS Memory Access',
    'TA0006',
    'T1003.001',
    96,
    false,
    NULL,
    '["credential-dumping", "lsass", "mimikatz"]'::jsonb,
    '{"tool_detected": "mimikatz", "access_attempts": 3, "success": false}'::jsonb,
    NOW() - INTERVAL '15 minutes',
    NOW() - INTERVAL '15 minutes',
    NULL,
    NULL
  ),
  (
    'ALR-2025-00025',
    'Anomalous Outbound SMB Traffic',
    'Unexpected SMB traffic to external IP addresses detected.',
    'high',
    'open',
    'exfiltration',
    'Firewall',
    '192.168.55.78',
    '198.51.100.67',
    'service-account-01',
    'APP-SERVER-08',
    'FW-SMB-025',
    'External SMB Connection',
    'TA0010',
    'T1048.002',
    79,
    false,
    NULL,
    '["smb", "exfiltration", "external-comms"]'::jsonb,
    '{"destination_ips": ["198.51.100.67"], "data_transferred_mb": 234, "port": 445}'::jsonb,
    NOW() - INTERVAL '1 hour 15 minutes',
    NOW() - INTERVAL '1 hour 15 minutes',
    NULL,
    NULL
  );

-- Insert more alerts to reach 50+
INSERT INTO alerts (
  alert_id, title, description, severity, status, alert_type, source,
  source_ip, dest_ip, rule_id, rule_name, mitre_tactic, mitre_technique,
  confidence_score, tags, created_at
) VALUES
  ('ALR-2025-00026', 'Suspicious Scheduled Task Created', 'New scheduled task with suspicious parameters created.', 'medium', 'open', 'persistence', 'EDR', '10.0.89.23', NULL, 'EDR-SCHTASK-026', 'Suspicious Scheduled Task', 'TA0003', 'T1053.005', 81, '["scheduled-task", "persistence"]'::jsonb, NOW() - INTERVAL '3 hours'),
  ('ALR-2025-00027', 'Web Shell Upload Attempt', 'Attempted upload of file with web shell characteristics.', 'critical', 'open', 'web_attack', 'WAF', '45.33.22.11', '203.0.113.100', 'WAF-SHELL-027', 'Web Shell Upload', 'TA0003', 'T1505.003', 97, '["web-shell", "upload", "critical"]'::jsonb, NOW() - INTERVAL '1 hour'),
  ('ALR-2025-00028', 'Pass-the-Hash Attack Detected', 'NTLM hash reuse detected indicating pass-the-hash attack.', 'critical', 'investigating', 'lateral_movement', 'EDR', '10.0.45.67', '10.0.45.89', 'EDR-PTH-028', 'Pass-the-Hash Detection', 'TA0008', 'T1550.002', 94, '["pass-the-hash", "ntlm", "lateral-movement"]'::jsonb, NOW() - INTERVAL '4 hours'),
  ('ALR-2025-00029', 'Suspicious WMI Activity', 'WMI used for remote command execution.', 'high', 'acknowledged', 'execution', 'EDR', '192.168.70.34', '192.168.70.89', 'EDR-WMI-029', 'WMI Remote Execution', 'TA0002', 'T1047', 86, '["wmi", "remote-execution"]'::jsonb, NOW() - INTERVAL '6 hours'),
  ('ALR-2025-00030', 'Data Destruction Command Detected', 'Command to delete files and logs detected on server.', 'critical', 'open', 'impact', 'EDR', '10.0.100.45', NULL, 'EDR-DELETE-030', 'Mass File Deletion', 'TA0040', 'T1485', 99, '["data-destruction", "deletion", "critical"]'::jsonb, NOW() - INTERVAL '20 minutes'),
  ('ALR-2025-00031', 'Kerberoasting Attack Detected', 'Service ticket requests indicating Kerberoasting attack.', 'high', 'investigating', 'credential_access', 'Domain Controller', '10.0.23.45', '10.0.1.10', 'DC-KERB-031', 'Kerberoasting Detection', 'TA0006', 'T1558.003', 91, '["kerberoasting", "active-directory"]'::jsonb, NOW() - INTERVAL '2 hours'),
  ('ALR-2025-00032', 'Cloud Storage Mass Download', 'Large number of files downloaded from cloud storage.', 'medium', 'acknowledged', 'collection', 'Cloud Security', '192.168.25.67', NULL, 'CLOUD-DL-032', 'Mass Cloud Download', 'TA0009', 'T1530', 73, '["cloud", "mass-download"]'::jsonb, NOW() - INTERVAL '5 hours'),
  ('ALR-2025-00033', 'Suspicious Service Installation', 'New Windows service with suspicious binary path installed.', 'high', 'open', 'persistence', 'EDR', '10.0.56.78', NULL, 'EDR-SVC-033', 'Suspicious Service Creation', 'TA0003', 'T1543.003', 85, '["service", "persistence", "windows"]'::jsonb, NOW() - INTERVAL '1 hour 30 minutes'),
  ('ALR-2025-00034', 'Account Enumeration Activity', 'Systematic user account enumeration detected.', 'medium', 'investigating', 'discovery', 'Domain Controller', '192.168.90.12', '10.0.1.10', 'DC-ENUM-034', 'Account Enumeration', 'TA0007', 'T1087', 77, '["enumeration", "reconnaissance"]'::jsonb, NOW() - INTERVAL '7 hours'),
  ('ALR-2025-00035', 'Malicious Macro Execution Blocked', 'Office document with malicious macro blocked by EDR.', 'high', 'resolved', 'execution', 'EDR', '192.168.45.90', NULL, 'EDR-MACRO-035', 'Malicious Macro Detection', 'TA0002', 'T1204.002', 92, '["macro", "blocked", "office"]'::jsonb, NOW() - INTERVAL '1 day'),
  ('ALR-2025-00036', 'Suspicious LDAP Query', 'LDAP query attempting to enumerate domain administrators.', 'medium', 'acknowledged', 'discovery', 'Domain Controller', '10.0.78.34', '10.0.1.10', 'DC-LDAP-036', 'Suspicious LDAP Query', 'TA0007', 'T1069.002', 80, '["ldap", "enumeration", "active-directory"]'::jsonb, NOW() - INTERVAL '4 hours'),
  ('ALR-2025-00037', 'Remote Desktop Brute Force', 'Multiple failed RDP authentication attempts.', 'high', 'investigating', 'brute_force', 'Windows Security', '198.18.45.67', '203.0.113.50', 'WIN-RDP-037', 'RDP Brute Force', 'TA0006', 'T1110', 89, '["rdp", "brute-force"]'::jsonb, NOW() - INTERVAL '3 hours'),
  ('ALR-2025-00038', 'Shadow Copy Deletion', 'Volume shadow copies deleted, potential ransomware precursor.', 'critical', 'open', 'defense_evasion', 'EDR', '192.168.100.45', NULL, 'EDR-SHADOW-038', 'Shadow Copy Deletion', 'TA0005', 'T1490', 96, '["shadow-copy", "ransomware-indicator"]'::jsonb, NOW() - INTERVAL '25 minutes'),
  ('ALR-2025-00039', 'Suspicious Email Forwarding Rule', 'Email forwarding rule created to external address.', 'medium', 'investigating', 'collection', 'Email Security', '192.168.35.56', NULL, 'EMAIL-FWD-039', 'Suspicious Forwarding Rule', 'TA0009', 'T1114.003', 74, '["email", "forwarding", "exfiltration"]'::jsonb, NOW() - INTERVAL '8 hours'),
  ('ALR-2025-00040', 'Fileless Malware Execution', 'Malicious code execution without file system artifacts.', 'critical', 'investigating', 'execution', 'EDR', '10.0.67.123', NULL, 'EDR-FILELESS-040', 'Fileless Malware Detection', 'TA0002', 'T1059', 93, '["fileless", "memory-only", "advanced"]'::jsonb, NOW() - INTERVAL '1 hour 45 minutes');

-- Update some alerts with case associations based on case numbers
UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0001')
WHERE alert_id = 'ALR-2025-00001';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0005')
WHERE alert_id = 'ALR-2025-00002';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0007')
WHERE alert_id = 'ALR-2025-00003';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0008')
WHERE alert_id = 'ALR-2025-00004';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0006')
WHERE alert_id = 'ALR-2025-00005';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0002')
WHERE alert_id = 'ALR-2025-00009';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0011')
WHERE alert_id = 'ALR-2025-00010';

UPDATE alerts 
SET case_id = (SELECT id FROM cases WHERE case_number = 'CASE-2025-0004')
WHERE alert_id = 'ALR-2025-00017';
