/*
  # Add Mock Data for Threat Escalation and Asset Registry

  1. Mock Data
    - Sample assets across network zones
    - Sample threat escalation calculations
    - Network topology data
*/

-- Insert mock assets across different network zones
INSERT INTO asset_registry (
  asset_name,
  asset_type,
  ip_address,
  hostname,
  criticality,
  criticality_score,
  business_impact,
  model_confidence,
  discovery_method,
  exposed_ports,
  known_vulnerabilities,
  location,
  owner,
  compliance_level,
  is_active
) VALUES
-- DMZ Zone
(
  'Web-Server-01',
  'server',
  '10.1.1.10',
  'web01.dmz.corp',
  'high',
  1.5,
  'Public-facing web application serving 10K+ users daily',
  9.0,
  'agent',
  '[80, 443, 22]'::jsonb,
  '[{"cve": "CVE-2023-1234", "severity": "medium", "description": "Apache vulnerability"}]'::jsonb,
  'DMZ',
  'IT Operations',
  'PCI-DSS',
  true
),
(
  'Web-Server-02',
  'server',
  '10.1.1.11',
  'web02.dmz.corp',
  'high',
  9.0,
  'Load-balanced web server',
  9.0,
  'agent',
  '[80, 443, 22]'::jsonb,
  '[]'::jsonb,
  'DMZ',
  'IT Operations',
  'PCI-DSS',
  true
),
(
  'API-Gateway-01',
  'server',
  '10.1.1.20',
  'api-gw.dmz.corp',
  'very_high',
  2.0,
  'Critical API gateway handling all external API traffic',
  10.0,
  'manual',
  '[443, 8443]'::jsonb,
  '[]'::jsonb,
  'DMZ',
  'Platform Team',
  'SOC2',
  true
),

-- Production Zone
(
  'App-Server-01',
  'application',
  '10.2.1.10',
  'app01.prod.corp',
  'very_high',
  2.0,
  'Primary application server processing transactions',
  10.0,
  'agent',
  '[8080, 8443, 22]'::jsonb,
  '[]'::jsonb,
  'Production',
  'Application Team',
  'SOC2',
  true
),
(
  'App-Server-02',
  'application',
  '10.2.1.11',
  'app02.prod.corp',
  'very_high',
  2.0,
  'Secondary application server',
  10.0,
  'agent',
  '[8080, 8443, 22]'::jsonb,
  '[]'::jsonb,
  'Production',
  'Application Team',
  'SOC2',
  true
),
(
  'Database-Primary',
  'database',
  '10.2.2.10',
  'db01.prod.corp',
  'very_high',
  2.0,
  'Primary database storing all customer and transaction data',
  10.0,
  'manual',
  '[5432, 22]'::jsonb,
  '[{"cve": "CVE-2023-5678", "severity": "high", "description": "PostgreSQL privilege escalation"}]'::jsonb,
  'Production',
  'Database Team',
  'PCI-DSS, HIPAA',
  true
),
(
  'Database-Replica',
  'database',
  '10.2.2.11',
  'db02.prod.corp',
  'high',
  1.5,
  'Read replica for reporting and analytics',
  10.0,
  'agent',
  '[5432, 22]'::jsonb,
  '[]'::jsonb,
  'Production',
  'Database Team',
  'PCI-DSS',
  true
),

-- Internal Zone
(
  'File-Server-01',
  'server',
  '10.3.1.10',
  'fileserver.internal.corp',
  'high',
  1.5,
  'Central file storage for internal documents',
  8.0,
  'automated',
  '[445, 139, 22]'::jsonb,
  '[]'::jsonb,
  'Internal',
  'IT Operations',
  'ISO27001',
  true
),
(
  'Email-Server',
  'server',
  '10.3.1.20',
  'mail.internal.corp',
  'high',
  1.5,
  'Corporate email server',
  9.0,
  'agent',
  '[25, 587, 143, 993]'::jsonb,
  '[]'::jsonb,
  'Internal',
  'IT Operations',
  'ISO27001',
  true
),
(
  'AD-Controller-01',
  'server',
  '10.3.2.10',
  'dc01.internal.corp',
  'very_high',
  2.0,
  'Primary Active Directory domain controller',
  10.0,
  'manual',
  '[389, 636, 88, 445]'::jsonb,
  '[]'::jsonb,
  'Internal',
  'Infrastructure Team',
  'ISO27001',
  true
),
(
  'AD-Controller-02',
  'server',
  '10.3.2.11',
  'dc02.internal.corp',
  'very_high',
  2.0,
  'Secondary domain controller',
  10.0,
  'manual',
  '[389, 636, 88, 445]'::jsonb,
  '[]'::jsonb,
  'Internal',
  'Infrastructure Team',
  'ISO27001',
  true
),

-- Workstations
(
  'Finance-WS-01',
  'workstation',
  '10.4.1.50',
  'fin-ws01.corp',
  'medium',
  1.0,
  'Finance department workstation',
  7.0,
  'automated',
  '[]'::jsonb,
  '[]'::jsonb,
  'Office',
  'Finance',
  'SOX',
  true
),
(
  'HR-WS-01',
  'workstation',
  '10.4.1.60',
  'hr-ws01.corp',
  'high',
  1.5,
  'HR workstation with access to personnel data',
  7.0,
  'automated',
  '[]'::jsonb,
  '[]'::jsonb,
  'Office',
  'Human Resources',
  'GDPR',
  true
),

-- Network Devices
(
  'Core-Switch-01',
  'network_device',
  '10.0.1.1',
  'core-sw01.corp',
  'very_high',
  2.0,
  'Core network switch - single point of failure',
  10.0,
  'manual',
  '[22, 161]'::jsonb,
  '[]'::jsonb,
  'Data Center',
  'Network Team',
  'ISO27001',
  true
),
(
  'Firewall-External',
  'network_device',
  '10.0.0.1',
  'fw-ext.corp',
  'very_high',
  2.0,
  'External perimeter firewall',
  10.0,
  'manual',
  '[22, 443]'::jsonb,
  '[]'::jsonb,
  'DMZ',
  'Security Team',
  'PCI-DSS',
  true
),

-- Cloud Services
(
  'AWS-S3-Backup',
  'cloud_service',
  '52.219.96.0',
  's3-backup.amazonaws.com',
  'very_high',
  2.0,
  'S3 bucket storing critical backups',
  8.0,
  'automated',
  '[443]'::jsonb,
  '[]'::jsonb,
  'AWS us-east-1',
  'Cloud Team',
  'SOC2',
  true
),
(
  'Azure-AD-Sync',
  'cloud_service',
  '20.190.128.0',
  'login.microsoftonline.com',
  'high',
  1.5,
  'Azure AD synchronization service',
  8.0,
  'automated',
  '[443]'::jsonb,
  '[]'::jsonb,
  'Azure',
  'Identity Team',
  'ISO27001',
  true
);

-- Insert mock threat escalation calculations
INSERT INTO event_priority_calculations (
  event_id,
  initial_severity,
  severity_score,
  model_confidence,
  relevance_score,
  mcr_factor,
  threat_weight,
  asset_criticality,
  final_priority,
  priority_level,
  calculation_details,
  escalated,
  escalation_reason
) VALUES
(
  'EVT-2025-001',
  'very_high',
  10.0,
  10.0,
  1.0,
  1.0,
  1.12,
  2.0,
  22.4,
  'critical',
  '{"severity": "SQL injection attempt on customer database", "mcr": "Well-known asset with matching CVE", "threat": "Source IP on threat intelligence list", "asset": "Critical customer database"}'::jsonb,
  true,
  'Critical asset targeted with known vulnerability'
),
(
  'EVT-2025-002',
  'high',
  8.0,
  10.0,
  0.8,
  0.8,
  1.09,
  2.0,
  13.95,
  'critical',
  '{"severity": "Privilege escalation attempt", "mcr": "Domain controller with high confidence", "threat": "Unusual credential usage pattern", "asset": "Active Directory controller"}'::jsonb,
  true,
  'Domain controller privilege escalation'
),
(
  'EVT-2025-003',
  'high',
  8.0,
  9.0,
  0.7,
  0.63,
  1.06,
  2.0,
  10.7,
  'critical',
  '{"severity": "Lateral movement detected", "mcr": "API Gateway with known config", "threat": "Suspicious authentication pattern", "asset": "Critical API gateway"}'::jsonb,
  true,
  'Lateral movement to critical service'
),
(
  'EVT-2025-004',
  'medium',
  6.0,
  8.0,
  0.6,
  0.48,
  1.03,
  1.5,
  4.44,
  'high',
  '{"severity": "Unusual file access", "mcr": "File server with partial visibility", "threat": "Minor threat indicator", "asset": "Business file server"}'::jsonb,
  false,
  null
),
(
  'EVT-2025-005',
  'high',
  8.0,
  7.0,
  0.5,
  0.35,
  1.0,
  1.0,
  2.8,
  'medium',
  '{"severity": "Failed login attempts", "mcr": "Workstation with low confidence", "threat": "No threat intel match", "asset": "Standard workstation"}'::jsonb,
  false,
  null
),
(
  'EVT-2025-006',
  'very_high',
  10.0,
  10.0,
  0.9,
  0.9,
  1.15,
  2.0,
  20.7,
  'critical',
  '{"severity": "Ransomware pre-attack indicators", "mcr": "Database server with shadow copy deletion", "threat": "Known ransomware group IP", "asset": "Primary production database"}'::jsonb,
  true,
  'Ransomware preparation detected on critical database'
),
(
  'EVT-2025-007',
  'high',
  8.0,
  9.0,
  0.8,
  0.72,
  1.12,
  1.5,
  9.68,
  'critical',
  '{"severity": "Data exfiltration attempt", "mcr": "Web server with unusual outbound traffic", "threat": "Connection to suspicious domain", "asset": "Public web server"}'::jsonb,
  true,
  'Large data transfer to external untrusted destination'
),
(
  'EVT-2025-008',
  'medium',
  6.0,
  5.0,
  0.3,
  0.15,
  1.0,
  1.0,
  0.9,
  'low',
  '{"severity": "Port scan detected", "mcr": "Unknown asset", "threat": "No threat intel", "asset": "Unknown criticality"}'::jsonb,
  false,
  null
);

-- Insert sample threat intelligence sources
INSERT INTO threat_intelligence_sources (
  source_name,
  source_type,
  threat_severity,
  indicator_value,
  indicator_type,
  threat_category,
  confidence_score,
  tags,
  metadata,
  is_active
) VALUES
(
  'AlienVault OTX',
  'ip_reputation',
  8,
  '203.0.113.45',
  'ipv4',
  'malware',
  85.0,
  '["apt", "targeted-attack"]'::jsonb,
  '{"first_seen": "2025-09-15", "last_activity": "2025-10-01", "associated_malware": "Emotet"}'::jsonb,
  true
),
(
  'Abuse.ch',
  'ip_reputation',
  9,
  '198.51.100.123',
  'ipv4',
  'botnet',
  92.0,
  '["c2-server", "botnet"]'::jsonb,
  '{"botnet_family": "Mirai", "active_since": "2025-08-20"}'::jsonb,
  true
),
(
  'VirusTotal',
  'domain_reputation',
  7,
  'malicious-domain.xyz',
  'domain',
  'phishing',
  78.0,
  '["phishing", "credential-theft"]'::jsonb,
  '{"detection_ratio": "45/89", "categories": ["phishing", "malware"]}'::jsonb,
  true
),
(
  'EmergingThreats',
  'ip_reputation',
  10,
  '192.0.2.200',
  'ipv4',
  'ransomware',
  95.0,
  '["ransomware", "lockbit"]'::jsonb,
  '{"ransomware_family": "LockBit 3.0", "active_campaign": true}'::jsonb,
  true
);

-- Insert escalation rules
INSERT INTO escalation_rules (
  rule_name,
  description,
  priority_threshold,
  conditions,
  actions,
  notification_targets,
  auto_escalate,
  enabled
) VALUES
(
  'Critical Asset High Priority',
  'Auto-escalate any high priority event on critical assets',
  9.0,
  '{"asset_criticality": "very_high", "min_severity": "high"}'::jsonb,
  '["create_incident", "notify_soc", "isolate_if_malware"]'::jsonb,
  '["soc-team@corp.com", "security-lead@corp.com"]'::jsonb,
  true,
  true
),
(
  'Ransomware Indicators',
  'Immediate escalation for ransomware patterns',
  8.0,
  '{"threat_category": "ransomware", "confidence": 80}'::jsonb,
  '["create_p1_incident", "page_oncall", "isolate_system", "backup_snapshot"]'::jsonb,
  '["soc-oncall", "ir-team@corp.com", "ciso@corp.com"]'::jsonb,
  true,
  true
),
(
  'Multiple Failed Escalations',
  'Escalate if same asset has 3+ high priority events in 1 hour',
  7.0,
  '{"event_count": 3, "time_window": "1h", "same_asset": true}'::jsonb,
  '["create_incident", "notify_asset_owner", "increase_monitoring"]'::jsonb,
  '["soc-team@corp.com"]'::jsonb,
  true,
  true
);
