/*
  # Insert Showcase Correlation Rules - Batch 3: Ensemble, Adversarial Simulation, Cross-Domain Fusion

  Adds 75 showcase rules (25 per type) with multi-model ensemble voting,
  adversarial attack simulation matching, and cross-domain data fusion.
*/

DO $body$
DECLARE
  i int;
  pc text;
  rname text;
  rdesc text;
  rcat text;
  rsev text;
  rconf int;
  rcomp int;
  sevs text[] := ARRAY['critical','critical','high','high','medium'];
  cats text[] := ARRAY['APT & State-Sponsored','Ransomware','Data Exfiltration','Credential Attacks','Lateral Movement','Insider Threat','Cloud Security','Supply Chain','Zero-Day Exploits','Command & Control'];
  auths text[] := ARRAY['ML Pipeline','Purple Team','Detection Engineering','Red Team','Threat Intel Team'];
  ensemble_types text[] := ARRAY['Majority Voting Ensemble','Stacked Meta-Learner','Cascade Filter Pipeline','Temporal Ensemble','Multi-Domain Fusion Ensemble'];
  adversarial_types text[] := ARRAY['MITRE CALDERA APT29','Atomic Red Team Coverage','SCYTHE Campaign Simulation','Purple Team Live Exercise','Breach & Attack Simulation'];
  fusion_types text[] := ARRAY['Physical + Cyber Convergence','HR + Security Correlation','Financial + Network Fusion','Threat Intel + Vulnerability + Asset','Supply Chain + Code + Build Pipeline'];
BEGIN

  -- ═══════════════════════════════════════════
  -- ENSEMBLE MULTI-MODEL RULES (25)
  -- ═══════════════════════════════════════════
  FOR i IN 1..25 LOOP
    rcat := cats[((i-1) % 10) + 1];
    rsev := sevs[((i-1) % 5) + 1];
    rconf := 85 + (i % 13);
    rcomp := 8 + (i % 2);

    pc := CASE (i-1) % 5
      WHEN 0 THEN E'# Majority Voting Ensemble: Multi-Algorithm Threat Consensus\n# Models: Random Forest + XGBoost + Neural Net + SVM + LightGBM\n# Quorum: 3/5 must agree | Confidence-Weighted Voting\n\nENSEMBLE majority_vote_detect(event: security.enriched_alert) {\n  FEATURES := STANDARD_FEATURE_EXTRACTION(event)\n\n  VOTES := [\n    MODEL("random_forest_v5").predict_proba(FEATURES),     -- accuracy: 94.2%\n    MODEL("xgboost_ensemble_v3").predict_proba(FEATURES),   -- accuracy: 95.1%\n    MODEL("deep_neural_4layer").predict_proba(FEATURES),    -- accuracy: 93.8%\n    MODEL("svm_rbf_calibrated").predict_proba(FEATURES),    -- accuracy: 91.5%\n    MODEL("lightgbm_dart_v2").predict_proba(FEATURES)       -- accuracy: 94.7%\n  ]\n\n  WEIGHTED_VOTE := SUM(vote.malicious_prob * model.accuracy_weight for vote in VOTES)\n  AGREEMENT := COUNT(VOTES WHERE malicious_prob > 0.5) / 5\n  DISAGREEMENT_ENTROPY := ENTROPY([v.malicious_prob for v in VOTES])\n\n  WHEN WEIGHTED_VOTE > 0.75 AND AGREEMENT >= 0.6\n  THEN\n    ALERT("Ensemble Consensus: " + ROUND(AGREEMENT*100) + "% agreement")\n    ATTACH(model_agreement_chart, per_model_explanations)\n    IF DISAGREEMENT_ENTROPY > 0.8 THEN FLAG("high_uncertainty_review")\n    ROUTE(to=SOC_ANALYST, with_explanations=true)\n}'
      WHEN 1 THEN E'# Stacked Meta-Learner: Two-Stage Alert Prioritization\n# Stage 1: 4 specialist models | Stage 2: Logistic meta-learner\n\nENSEMBLE stacked_meta_learner(alert_batch: siem.alert_queue) {\n  -- Stage 1: Specialist Models\n  FOR EACH alert IN alert_batch {\n    STAGE_1_OUTPUTS := [\n      MODEL("network_specialist").score(alert.network_features),\n      MODEL("endpoint_specialist").score(alert.endpoint_features),\n      MODEL("identity_specialist").score(alert.identity_features),\n      MODEL("threat_intel_specialist").score(alert.ti_features)\n    ]\n\n    -- Stage 2: Meta-Learner combines Stage 1 outputs\n    META_FEATURES := CONCAT(\n      STAGE_1_OUTPUTS,\n      alert.severity_numeric,\n      alert.asset_criticality,\n      HOUR_OF_DAY(alert.timestamp),\n      alert.historical_fp_rate\n    )\n    PRIORITY := MODEL("meta_logistic_v3").predict(META_FEATURES)\n    CALIBRATED := PLATT_SCALING(PRIORITY)\n\n    ANNOTATE(alert, priority=CALIBRATED, specialist_scores=STAGE_1_OUTPUTS)\n  }\n\n  TOP_ALERTS := RANK(alert_batch, by=CALIBRATED, top_n=15)\n  DISTRIBUTE(TOP_ALERTS, to=SOC_QUEUE, round_robin=true)\n}'
      WHEN 2 THEN E'# Cascade Filter Pipeline: Progressive Deep Inspection\n# Stage 1: Fast filter (1ms) | Stage 2: Medium (50ms) | Stage 3: Deep (500ms)\n\nENSEMBLE cascade_pipeline(stream: network.raw_events) {\n  -- Stage 1: Bloom Filter + Simple Rules (1ms budget)\n  STAGE_1 := BLOOM_FILTER_CHECK(event.hash, known_malicious_set)\n             OR RULE_MATCH(event, fast_signature_rules)\n  IF NOT STAGE_1 THEN PASS_THROUGH  -- 95% of traffic exits here\n\n  -- Stage 2: Lightweight ML (50ms budget)\n  FEATURES_LITE := EXTRACT_FAST(packet_size, timing, protocol, port)\n  STAGE_2 := MODEL("lightweight_rf_100trees").predict(FEATURES_LITE)\n  IF STAGE_2.benign_prob > 0.9 THEN PASS_THROUGH  -- 3% more exits\n\n  -- Stage 3: Deep Inspection (500ms budget)\n  FEATURES_DEEP := EXTRACT_FULL(\n    payload_entropy, tls_certificate_chain, dns_resolution_history,\n    behavioral_context, threat_intel_enrichment, geo_risk_score\n  )\n  STAGE_3 := MODEL("deep_transformer_v2").predict(FEATURES_DEEP)\n  EXPLANATION := INTEGRATED_GRADIENTS(MODEL, FEATURES_DEEP)\n\n  WHEN STAGE_3.threat_score > 0.8\n  THEN\n    ALERT("Deep Cascade Detection", confidence=STAGE_3.threat_score)\n    ATTACH(cascade_stage_results, explanation_attribution)\n    PCAP_PRESERVE(event.flow_id, duration=600s)\n}'
      WHEN 3 THEN E'# Temporal Ensemble: Multi-Timescale Model Aggregation\n# Models: 5min-window + 1h-window + 24h-window + 7d-window\n\nENSEMBLE temporal_ensemble(entity: monitored_asset) {\n  -- Each model operates on different time granularity\n  SCORE_5M := MODEL("short_burst_detector").predict(\n    WINDOW(entity.events, 5 minutes))\n  SCORE_1H := MODEL("session_anomaly_detector").predict(\n    WINDOW(entity.events, 1 hour))\n  SCORE_24H := MODEL("daily_pattern_detector").predict(\n    WINDOW(entity.events, 24 hours))\n  SCORE_7D := MODEL("weekly_trend_detector").predict(\n    WINDOW(entity.events, 7 days))\n\n  -- Aggregate with learned temporal weights\n  TEMPORAL_FUSION := MODEL("temporal_aggregator").fuse(\n    scores = [SCORE_5M, SCORE_1H, SCORE_24H, SCORE_7D],\n    current_context = {hour: NOW().hour, weekday: NOW().weekday}\n  )\n\n  WHEN TEMPORAL_FUSION.threat_score > 0.82\n    AND COUNT(scores WHERE > 0.6) >= 3  -- multi-scale agreement\n  THEN\n    ALERT("Multi-Timescale Threat: " + DOMINANT_TIMESCALE)\n    ATTACH(temporal_heatmap, scale_contribution_chart)\n}'
      ELSE E'# Adversarial Ensemble: Robustness Through Diversity\n# Training: Each model trained on different attack eras\n\nENSEMBLE adversarial_robust(event: security.enriched_event) {\n  -- Models trained on intentionally different data distributions\n  HISTORICAL := MODEL("trained_2020_2021").predict(event)\n  RECENT := MODEL("trained_2022_2023").predict(event)\n  CURRENT := MODEL("trained_2024_live").predict(event)\n  SYNTHETIC := MODEL("trained_adversarial_aug").predict(event)  -- adversarial training\n  TRANSFER := MODEL("pretrained_cybersec_bert").predict(event)  -- transfer learning\n\n  -- Detect when models disagree (potential evasion attempt)\n  VARIANCE := VAR([HISTORICAL, RECENT, CURRENT, SYNTHETIC, TRANSFER])\n  MAX_SCORE := MAX([HISTORICAL, RECENT, CURRENT, SYNTHETIC, TRANSFER])\n  MIN_SCORE := MIN([HISTORICAL, RECENT, CURRENT, SYNTHETIC, TRANSFER])\n\n  -- High variance + high max = potential adversarial evasion\n  WHEN VARIANCE > 0.15 AND MAX_SCORE > 0.85\n  THEN\n    ALERT("Adversarial Evasion Suspected: Model Disagreement")\n    FLAG(event, "potential_evasion")\n    MANUAL_REVIEW(priority="high")\n    RETRAIN_TRIGGER(failing_models, with_sample=event)\n\n  WHEN MAX_SCORE > 0.9 AND VARIANCE < 0.05\n  THEN\n    ALERT("High-Confidence Ensemble Detection")\n    AUTO_RESPOND(playbook="confirmed_threat")\n}'
    END;

    rname := 'ENS-' || lpad(i::text, 3, '0') || ' ' || ensemble_types[((i-1)%5)+1] || ' ' || rcat;
    rdesc := 'Ensemble multi-model rule using ' || ensemble_types[((i-1)%5)+1] || '. Combines outputs from multiple independent detection models to achieve higher accuracy and robustness than any single model. Includes model agreement analysis, uncertainty quantification, and adversarial evasion detection.';

    INSERT INTO correlation_rules_library (rule_name, rule_description, category, subcategory, severity, confidence_score, mitre_tactics, mitre_techniques, data_sources, rule_logic, enabled, tags, author, rule_type, complexity_score, trigger_count, false_positive_rate, created_at, updated_at)
    VALUES (
      rname, rdesc, rcat, 'Ensemble Detection', rsev, rconf,
      ARRAY['Execution','Defense Evasion','Command and Control','Exfiltration'],
      ARRAY['T1059','T1027','T1071','T1048'],
      ARRAY['EDR Telemetry','Network Flow','SIEM Alerts','Threat Intel','Identity Logs'],
      jsonb_build_object('pseudo_code', pc, 'ensemble_type', ensemble_types[((i-1)%5)+1], 'model_count', 4 + (i%3), 'voting_strategy', CASE (i-1)%3 WHEN 0 THEN 'majority_vote' WHEN 1 THEN 'stacked_meta' ELSE 'cascade' END, 'detection_type', 'ensemble_multi_model'),
      random() < 0.3, ARRAY['ensemble','multi-model','voting','consensus','robust','meta-learner'], auths[((i-1)%5)+1],
      'ensemble_multi_model', rcomp, floor(random()*1800)::int, round((random()*2.5)::numeric, 2),
      now() - (random()*180||' days')::interval, now() - (random()*30||' days')::interval
    );
  END LOOP;

  -- ═══════════════════════════════════════════
  -- ADVERSARIAL SIMULATION RULES (25)
  -- ═══════════════════════════════════════════
  FOR i IN 1..25 LOOP
    rcat := cats[((i-1) % 10) + 1];
    rsev := sevs[((i-1) % 5) + 1];
    rconf := 83 + (i % 15);
    rcomp := 7 + (i % 3);

    pc := CASE (i-1) % 5
      WHEN 0 THEN E'# MITRE CALDERA APT29 Playbook Correlation\n# Adversary: Cozy Bear | Campaign: SolarWinds-style Supply Chain\n# Tests: 47 atomic techniques | Coverage: 12 MITRE tactics\n\nSIMULATION_MATCH caldera_apt29 {\n  PLAYBOOK := LOAD("caldera/apt29_full_chain")\n\n  TECHNIQUE_MATCHES := []\n  FOR EACH step IN PLAYBOOK.steps {\n    PATTERN := step.detection_signature\n    OBSERVED := SEARCH(\n      events, WHERE\n        mitre_technique = step.technique_id\n        AND process.command MATCHES step.command_pattern\n        AND WITHIN step.expected_timeframe\n    )\n\n    IF COUNT(OBSERVED) > 0 THEN\n      TECHNIQUE_MATCHES.append({\n        step: step.name,\n        technique: step.technique_id,\n        evidence: OBSERVED,\n        time_delta: OBSERVED[0].timestamp - PLAYBOOK.start_time\n      })\n    END IF\n  }\n\n  CHAIN_COVERAGE := LEN(TECHNIQUE_MATCHES) / LEN(PLAYBOOK.steps)\n  ORDERED_MATCH := IS_ORDERED(TECHNIQUE_MATCHES.timestamps)\n\n  WHEN CHAIN_COVERAGE > 0.4 AND ORDERED_MATCH = true\n  THEN\n    ALERT("APT29 Playbook Match: " + ROUND(CHAIN_COVERAGE*100) + "% coverage")\n    ATTACH(kill_chain_coverage_map, technique_timeline)\n    INVOKE(incident_response_playbook="apt_state_sponsored")\n    NOTIFY(CISO, threat_level="nation_state")\n}'
      WHEN 1 THEN E'# Atomic Red Team: Detection Coverage Gap Analysis\n# Tests: 200+ atomic tests | Validation: Continuous\n\nSIMULATION_MATCH atomic_coverage_gaps {\n  LAST_RUN := LOAD("atomic_red_team/latest_execution")\n\n  FOR EACH test IN LAST_RUN.tests {\n    EXPECTED_ALERT := test.expected_detection\n    ACTUAL_ALERTS := SEARCH(\n      siem.alerts, WHERE\n        timestamp BETWEEN test.start_time AND test.end_time + 5m\n        AND mitre_technique = test.technique_id\n    )\n\n    test.detected := COUNT(ACTUAL_ALERTS) > 0\n    test.detection_latency := MIN(ACTUAL_ALERTS.timestamp) - test.execution_time\n    test.false_negatives := EXPECTED_ALERT AND NOT test.detected\n  }\n\n  GAPS := FILTER(LAST_RUN.tests, WHERE false_negatives = true)\n  CRITICAL_GAPS := FILTER(GAPS, WHERE technique.severity >= "high")\n\n  WHEN COUNT(CRITICAL_GAPS) > 0\n  THEN\n    ALERT("Detection Coverage Gap: " + COUNT(CRITICAL_GAPS) + " critical blind spots")\n    FOR EACH gap IN CRITICAL_GAPS {\n      GENERATE_RULE_SUGGESTION(gap.technique_id)\n      CREATE_TICKET(engineering_backlog, priority="high")\n    }\n    REPORT(coverage_matrix, gap_analysis_dashboard)\n}'
      WHEN 2 THEN E'# SCYTHE Campaign Simulation: Multi-Stage Attack Correlation\n# Campaign: Custom adversary profile | Phases: 5\n\nSIMULATION_MATCH scythe_campaign {\n  CAMPAIGN := LOAD("scythe/custom_campaign_q4")\n  ENTITY_SCOPE := CAMPAIGN.target_assets\n\n  PHASE_RESULTS := []\n  FOR EACH phase IN CAMPAIGN.phases {\n    INDICATORS := phase.expected_indicators\n    DETECTIONS := []\n\n    FOR EACH indicator IN INDICATORS {\n      EVIDENCE := CORRELATE(\n        source = indicator.data_source,\n        pattern = indicator.detection_pattern,\n        window = phase.time_window,\n        scope = ENTITY_SCOPE\n      )\n      IF EVIDENCE.found THEN DETECTIONS.append(EVIDENCE)\n    }\n\n    PHASE_RESULTS.append({\n      phase: phase.name,\n      detection_rate: LEN(DETECTIONS) / LEN(INDICATORS),\n      mean_detection_time: AVG(DETECTIONS.latency),\n      missed: FILTER(INDICATORS, NOT IN DETECTIONS)\n    })\n  }\n\n  OVERALL := AVG(phase.detection_rate for phase in PHASE_RESULTS)\n  WHEN OVERALL < 0.8\n  THEN\n    ALERT("Campaign Simulation Coverage: " + ROUND(OVERALL*100) + "%")\n    REMEDIATION_PLAN(gaps=FLATTEN(phase.missed for phase in PHASE_RESULTS))\n}'
      WHEN 3 THEN E'# Purple Team Live Exercise Validation\n# Exercise: Concurrent red+blue | Duration: 4h window\n\nSIMULATION_MATCH purple_team_exercise {\n  EXERCISE := LOAD("purple_team/exercise_" + CURRENT_EXERCISE_ID)\n  RED_ACTIONS := EXERCISE.red_team_actions  -- timestamped attack log\n  BLUE_DETECTIONS := EXERCISE.blue_team_detections\n\n  CORRELATION_MATRIX := []\n  FOR EACH red_action IN RED_ACTIONS {\n    MATCHING_DETECTIONS := FILTER(BLUE_DETECTIONS, WHERE\n      technique = red_action.technique\n      AND timestamp BETWEEN red_action.time AND red_action.time + 15m\n      AND target_asset = red_action.target\n    )\n\n    CORRELATION_MATRIX.append({\n      attack: red_action,\n      detected: LEN(MATCHING_DETECTIONS) > 0,\n      time_to_detect: MIN(MATCHING_DETECTIONS.timestamp) - red_action.time,\n      detection_source: MATCHING_DETECTIONS[0].source\n    })\n  }\n\n  TTD_AVG := AVG(c.time_to_detect for c in CORRELATION_MATRIX WHERE c.detected)\n  COVERAGE := COUNT(c WHERE c.detected) / LEN(CORRELATION_MATRIX)\n\n  WHEN COVERAGE < 0.7 OR TTD_AVG > 30 minutes\n  THEN\n    ALERT("Purple Team Gap: Coverage=" + COVERAGE + " TTD=" + TTD_AVG)\n    GENERATE_IMPROVEMENT_REPORT(CORRELATION_MATRIX)\n}'
      ELSE E'# Breach & Attack Simulation: Continuous Validation\n# Platform: Automated BAS | Frequency: Every 6 hours\n\nSIMULATION_MATCH bas_continuous_validation {\n  BAS_RESULTS := LOAD("bas/latest_cycle")\n\n  SECURITY_STACK := [\n    { layer: "perimeter", controls: ["firewall","waf","ips"] },\n    { layer: "network", controls: ["ndr","segmentation","dns_security"] },\n    { layer: "endpoint", controls: ["edr","av","dlp"] },\n    { layer: "identity", controls: ["mfa","pam","sso"] },\n    { layer: "data", controls: ["encryption","masking","backup"] }\n  ]\n\n  FOR EACH layer IN SECURITY_STACK {\n    layer.tests := FILTER(BAS_RESULTS, WHERE target_layer = layer.name)\n    layer.blocked := COUNT(layer.tests WHERE result = "blocked")\n    layer.bypassed := COUNT(layer.tests WHERE result = "bypassed")\n    layer.effectiveness := layer.blocked / (layer.blocked + layer.bypassed)\n  }\n\n  WEAKEST := MIN(SECURITY_STACK, by=effectiveness)\n  OVERALL := MEAN(layer.effectiveness for layer in SECURITY_STACK)\n\n  WHEN WEAKEST.effectiveness < 0.6\n    OR OVERALL < 0.8\n    OR ANY(layer WHERE layer.bypassed > previous_cycle.bypassed)\n  THEN\n    ALERT("BAS Regression: " + WEAKEST.name + " at " + WEAKEST.effectiveness)\n    TICKET_CREATE(remediation, controls=WEAKEST.bypassed_controls)\n    TREND_REPORT(effectiveness_over_time, regression_analysis)\n}'
    END;

    rname := 'ADVSIM-' || lpad(i::text, 3, '0') || ' ' || adversarial_types[((i-1)%5)+1] || ' ' || rcat;
    rdesc := 'Adversarial simulation rule derived from ' || adversarial_types[((i-1)%5)+1] || '. Correlates observed telemetry against known attack playbooks and simulation results to validate detection coverage, measure time-to-detect, and identify critical blind spots in the security stack.';

    INSERT INTO correlation_rules_library (rule_name, rule_description, category, subcategory, severity, confidence_score, mitre_tactics, mitre_techniques, data_sources, rule_logic, enabled, tags, author, rule_type, complexity_score, trigger_count, false_positive_rate, created_at, updated_at)
    VALUES (
      rname, rdesc, rcat, 'Adversarial Simulation', rsev, rconf,
      ARRAY['Initial Access','Execution','Persistence','Defense Evasion','Lateral Movement'],
      ARRAY['T1190','T1059','T1547','T1027','T1021'],
      ARRAY['EDR Telemetry','Network Flow','BAS Platform','SIEM Alerts','Red Team Logs'],
      jsonb_build_object('pseudo_code', pc, 'simulation_type', adversarial_types[((i-1)%5)+1], 'playbook_techniques', 30 + (i*2), 'detection_type', 'adversarial_simulation'),
      random() < 0.35, ARRAY['adversarial','simulation','red-team','purple-team','attack-emulation','caldera','atomic'], auths[((i-1)%5)+1],
      'adversarial_simulation', rcomp, floor(random()*1200)::int, round((random()*2)::numeric, 2),
      now() - (random()*180||' days')::interval, now() - (random()*30||' days')::interval
    );
  END LOOP;

  -- ═══════════════════════════════════════════
  -- CROSS-DOMAIN FUSION RULES (25)
  -- ═══════════════════════════════════════════
  FOR i IN 1..25 LOOP
    rcat := cats[((i-1) % 10) + 1];
    rsev := sevs[((i-1) % 5) + 1];
    rconf := 84 + (i % 14);
    rcomp := 8 + (i % 2);

    pc := CASE (i-1) % 5
      WHEN 0 THEN E'# Physical + Cyber Convergence: Badge Access + VPN Geolocation\n# Domains: Physical Security (PACS) + Network Security + HR\n\nCROSS_DOMAIN_FUSION physical_cyber_convergence {\n  PHYSICAL := QUERY(badge_access_system, {\n    entity: user.employee_id,\n    window: 24 hours,\n    fields: [badge_timestamp, facility, gate, direction]\n  })\n\n  CYBER := QUERY(vpn_gateway + auth_logs, {\n    entity: user.username,\n    window: 24 hours,\n    fields: [login_timestamp, source_ip, geo_location, device_id]\n  })\n\n  HR := QUERY(hr_system, {\n    entity: user.employee_id,\n    fields: [travel_requests, pto_calendar, work_location, termination_date]\n  })\n\n  -- Impossible travel detection across physical and cyber\n  FOR EACH cyber_event IN CYBER {\n    NEAREST_BADGE := CLOSEST_IN_TIME(PHYSICAL, cyber_event.timestamp)\n    GEO_DISTANCE := HAVERSINE(NEAREST_BADGE.facility.coords, cyber_event.geo_location)\n    TIME_DELTA := ABS(cyber_event.timestamp - NEAREST_BADGE.badge_timestamp)\n    REQUIRED_TRAVEL_TIME := GEO_DISTANCE / MAX_TRAVEL_SPEED\n\n    IF TIME_DELTA < REQUIRED_TRAVEL_TIME THEN\n      FLAG("impossible_travel", evidence=[NEAREST_BADGE, cyber_event])\n    END IF\n  }\n\n  WHEN COUNT(FLAGS) > 0\n    AND user.termination_date IS NOT NULL\n    AND user.termination_date < NOW() + 30 days\n  THEN\n    ALERT("Physical-Cyber Convergence: Impossible Travel + Termination Risk")\n    DISABLE_BADGE(user, immediate=true)\n    SESSION_TERMINATE(user, all_sessions=true)\n    FORENSIC_PRESERVE(user, all_domains=true)\n}'
      WHEN 1 THEN E'# HR Termination + Data Activity Correlation\n# Domains: HR System + Database Audit + Email + Endpoint DLP\n\nCROSS_DOMAIN_FUSION hr_security_correlation {\n  HR_EVENTS := QUERY(hr_system, {\n    type: ["resignation_submitted","termination_initiated","pip_started",\n           "demotion","transfer_denied","negative_review"],\n    window: 90 days\n  })\n\n  FOR EACH hr_event IN HR_EVENTS {\n    user := hr_event.employee\n    event_date := hr_event.date\n\n    -- Measure behavioral changes AFTER HR event\n    PRE_BASELINE := AGGREGATE(user.activity, RANGE(event_date - 30d, event_date))\n    POST_BEHAVIOR := AGGREGATE(user.activity, RANGE(event_date, NOW()))\n\n    METRICS := {\n      data_download_change: POST_BEHAVIOR.downloads / PRE_BASELINE.downloads,\n      email_forward_change: POST_BEHAVIOR.forwards_external / PRE_BASELINE.forwards_external,\n      usb_usage_change: POST_BEHAVIOR.usb_events / PRE_BASELINE.usb_events,\n      after_hours_change: POST_BEHAVIOR.after_hours_ratio / PRE_BASELINE.after_hours_ratio,\n      cloud_upload_change: POST_BEHAVIOR.cloud_uploads / PRE_BASELINE.cloud_uploads,\n      sensitive_access_change: POST_BEHAVIOR.sensitive_files / PRE_BASELINE.sensitive_files\n    }\n  }\n\n  RISK_FACTORS := COUNT(METRICS WHERE change_ratio > 3.0)\n\n  WHEN RISK_FACTORS >= 3\n    AND hr_event.type IN ["resignation_submitted","termination_initiated"]\n  THEN\n    ALERT("Insider Threat: HR Event + Data Activity Spike")\n    DLP_ENHANCED_MONITORING(user, level="maximum")\n    MANAGER_BRIEFING(user.manager, confidential=true)\n}'
      WHEN 2 THEN E'# Financial Anomaly + Network Exfiltration Correlation\n# Domains: ERP/Financial System + Network DLP + Email DLP + Trading Platform\n\nCROSS_DOMAIN_FUSION financial_network_fusion {\n  FINANCIAL := QUERY(erp_system + trading_platform, {\n    anomalies: [\n      "unusual_wire_transfer", "large_invoice_modification",\n      "vendor_bank_account_change", "purchase_order_split",\n      "expense_report_spike", "unusual_trading_pattern"\n    ],\n    window: 48 hours\n  })\n\n  NETWORK := QUERY(network_dlp + proxy_logs, {\n    entity: financial.user_ids,\n    indicators: [\n      "large_upload_external", "encrypted_tunnel_new_dest",\n      "personal_email_attachment", "cloud_storage_upload",\n      "screenshot_tool_active", "data_staging_detected"\n    ],\n    window: 48 hours\n  })\n\n  CORRELATION := TEMPORAL_JOIN(\n    FINANCIAL, NETWORK,\n    join_key = "user_id",\n    time_tolerance = 4 hours\n  )\n\n  WHEN COUNT(CORRELATION) > 0\n    AND FINANCIAL.total_value > 50000\n    AND NETWORK.data_volume > 100 MB\n  THEN\n    ALERT("Financial + Network Exfil Correlation: $" + FINANCIAL.total_value)\n    FREEZE(financial_transactions, pending_review=true)\n    BLOCK(NETWORK.external_destinations)\n    ESCALATE(CFO + CISO, joint_investigation=true)\n}'
      WHEN 3 THEN E'# Threat Intel + Vulnerability + Asset Criticality Fusion\n# Domains: Threat Intel Feeds + Vuln Scanner + CMDB + Business Impact\n\nCROSS_DOMAIN_FUSION threat_vuln_asset_fusion {\n  ACTIVE_THREATS := QUERY(threat_intel_platform, {\n    filter: [active_campaigns, targeting_our_sector],\n    fields: [cves_exploited, ttps, iocs, target_industries]\n  })\n\n  VULN_EXPOSURE := QUERY(vulnerability_scanner, {\n    filter: [unpatched, exploitable],\n    join: asset_inventory ON host_id\n  })\n\n  ASSET_CRITICALITY := QUERY(cmdb + bia_database, {\n    fields: [business_impact_score, data_classification,\n             revenue_dependency, compliance_scope]\n  })\n\n  -- Cross-domain risk matrix\n  FOR EACH threat IN ACTIVE_THREATS {\n    EXPOSED_ASSETS := FILTER(VULN_EXPOSURE, WHERE\n      cve_id IN threat.cves_exploited\n      AND asset.reachable_from_internet = true\n    )\n\n    FOR EACH asset IN EXPOSED_ASSETS {\n      COMPOSITE_RISK := (\n        threat.likelihood * 0.3 +\n        asset.vuln_severity * 0.3 +\n        asset.business_impact * 0.4\n      )\n    }\n  }\n\n  CRITICAL_EXPOSURES := FILTER(results, WHERE COMPOSITE_RISK > 8.5)\n  WHEN COUNT(CRITICAL_EXPOSURES) > 0\n  THEN\n    ALERT("Active Threat + Unpatched Vuln + Critical Asset")\n    EMERGENCY_PATCH(CRITICAL_EXPOSURES, sla=4h)\n    VIRTUAL_PATCH(waf_rules, auto_generate=true)\n    WAR_ROOM(security_team + it_ops + business_owners)\n}'
      ELSE E'# Supply Chain + Code Repository + Build Pipeline Fusion\n# Domains: SCA Scanner + Git Audit + CI/CD Pipeline + Package Registry\n\nCROSS_DOMAIN_FUSION supply_chain_fusion {\n  SCA := QUERY(software_composition_analysis, {\n    findings: ["malicious_package","typosquat","dependency_confusion",\n               "known_vuln_critical","license_violation"],\n    window: 7 days\n  })\n\n  GIT := QUERY(git_audit_log, {\n    suspicious: ["force_push_main","branch_protection_disabled",\n                 "new_contributor_sensitive_path","commit_unsigned",\n                 "ci_config_modified","secret_pattern_detected"],\n    window: 7 days\n  })\n\n  CICD := QUERY(build_pipeline_logs, {\n    anomalies: ["build_step_added","artifact_hash_mismatch",\n                "dependency_source_changed","build_env_modified",\n                "post_build_network_call","unsigned_artifact_published"],\n    window: 7 days\n  })\n\n  REGISTRY := QUERY(package_registry, {\n    events: ["new_maintainer","version_yank","metadata_change",\n             "download_spike","unexpected_binary_content"],\n    window: 7 days\n  })\n\n  SUPPLY_CHAIN_RISK := CORRELATE(\n    SCA, GIT, CICD, REGISTRY,\n    temporal_window = 48 hours,\n    min_domain_overlap = 2\n  )\n\n  WHEN SUPPLY_CHAIN_RISK.score > 7.5\n    AND SUPPLY_CHAIN_RISK.domains_affected >= 2\n  THEN\n    ALERT("Supply Chain Attack Indicator: " + SUPPLY_CHAIN_RISK.summary)\n    QUARANTINE_BUILD(affected_artifacts)\n    ROLLBACK(to=last_verified_good_build)\n    SBOM_DIFF(current_build, last_verified_build)\n    NOTIFY(engineering_leads + security_champions)\n}'
    END;

    rname := 'FUSION-' || lpad(i::text, 3, '0') || ' ' || fusion_types[((i-1)%5)+1] || ' ' || rcat;
    rdesc := 'Cross-domain data fusion rule implementing ' || fusion_types[((i-1)%5)+1] || '. Correlates signals across traditionally siloed security domains to detect sophisticated attacks that are invisible when analyzing any single domain in isolation.';

    INSERT INTO correlation_rules_library (rule_name, rule_description, category, subcategory, severity, confidence_score, mitre_tactics, mitre_techniques, data_sources, rule_logic, enabled, tags, author, rule_type, complexity_score, trigger_count, false_positive_rate, created_at, updated_at)
    VALUES (
      rname, rdesc, rcat, 'Cross-Domain Fusion', rsev, rconf,
      ARRAY['Initial Access','Execution','Collection','Exfiltration','Impact'],
      ARRAY['T1195','T1059','T1074','T1048','T1486'],
      ARRAY['Physical Access Control','HR System','Financial System','Git Audit','CI/CD Pipeline','Threat Intel','Vulnerability Scanner','CMDB'],
      jsonb_build_object('pseudo_code', pc, 'fusion_type', fusion_types[((i-1)%5)+1], 'domains', CASE (i-1)%5 WHEN 0 THEN ARRAY['physical','cyber','hr'] WHEN 1 THEN ARRAY['hr','database','email','endpoint'] WHEN 2 THEN ARRAY['financial','network','dlp'] WHEN 3 THEN ARRAY['threat_intel','vuln_mgmt','cmdb'] ELSE ARRAY['sca','git','cicd','registry'] END, 'detection_type', 'cross_domain_fusion'),
      random() < 0.25, ARRAY['cross-domain','fusion','convergence','multi-source','holistic','insider-threat'], auths[((i-1)%5)+1],
      'cross_domain_fusion', rcomp, floor(random()*1000)::int, round((random()*2)::numeric, 2),
      now() - (random()*180||' days')::interval, now() - (random()*30||' days')::interval
    );
  END LOOP;

END $body$;
