/*
  # Populate Financial Threat Intelligence Mock Data

  Rich mock data for the financial threat intelligence platform including:
  1. 30 identity profiles with varied trust scores, behavioral baselines, and anomaly flags
  2. 80 financial transactions (PIX, TED, card, crypto) with risk scoring
  3. 120 identity graph edges connecting users, devices, IPs, sessions, beneficiaries
  4. 25 threat detections across all threat categories
  5. 40 response decisions showing orchestration actions
  6. 8 Monte Carlo simulations with attack paths and detection gaps
*/

-- Identity Profiles
INSERT INTO financial_identity_profiles (entity_id, entity_name, entity_type, trust_score, risk_level, behavioral_baseline, device_fingerprints, geo_patterns, session_patterns, anomaly_flags, identity_status, last_activity_at, created_at) VALUES
('CPF-123.456.789-00', 'Carlos Eduardo Silva', 'person', 92, 'low', '{"avg_tx_amount": 2450, "tx_frequency_daily": 3.2, "primary_hours": [8,18], "top_recipients": ["PIX-maria-santos","PIX-empresa-tech"], "avg_session_duration_min": 12, "typical_navigation": ["dashboard","pix","extract"]}', '[{"id":"DEV-001","type":"mobile","os":"Android 14","model":"Samsung S24","first_seen":"2024-01-15","last_seen":"2024-12-15","trust":0.95},{"id":"DEV-002","type":"desktop","os":"Windows 11","browser":"Chrome 120","first_seen":"2024-03-01","last_seen":"2024-12-14","trust":0.88}]', '{"primary_city":"Sao Paulo","primary_state":"SP","coords":[-23.5505,-46.6333],"secondary_locations":[{"city":"Campinas","frequency":0.15}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.8,"avg_scroll_depth":0.72,"typing_speed_wpm":45,"mouse_pattern":"organic","session_start_variance_min":35}', '[]', 'verified', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '11 months'),

('CPF-234.567.890-11', 'Maria Santos Oliveira', 'person', 85, 'low', '{"avg_tx_amount": 1800, "tx_frequency_daily": 2.1, "primary_hours": [9,17], "top_recipients": ["PIX-carlos-silva","PIX-mercado-livre"], "avg_session_duration_min": 8, "typical_navigation": ["dashboard","pix","cards"]}', '[{"id":"DEV-003","type":"mobile","os":"iOS 17","model":"iPhone 15","first_seen":"2024-02-20","last_seen":"2024-12-15","trust":0.92}]', '{"primary_city":"Rio de Janeiro","primary_state":"RJ","coords":[-22.9068,-43.1729],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.65,"avg_scroll_depth":0.8,"typing_speed_wpm":38,"mouse_pattern":"organic","session_start_variance_min":42}', '[]', 'verified', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '14 months'),

('CPF-345.678.901-22', 'Pedro Augusto Lima', 'person', 34, 'high', '{"avg_tx_amount": 890, "tx_frequency_daily": 1.5, "primary_hours": [10,16], "top_recipients": ["PIX-loja-abc"], "avg_session_duration_min": 5, "typical_navigation": ["dashboard","pix"]}', '[{"id":"DEV-004","type":"mobile","os":"Android 12","model":"Motorola G52","first_seen":"2024-06-10","last_seen":"2024-12-15","trust":0.45},{"id":"DEV-099","type":"mobile","os":"Android 14","model":"Xiaomi 14","first_seen":"2024-12-14","last_seen":"2024-12-15","trust":0.1}]', '{"primary_city":"Belo Horizonte","primary_state":"MG","coords":[-19.9191,-43.9386],"secondary_locations":[{"city":"Manaus","frequency":0.02}],"impossible_travel_incidents":2}', '{"avg_click_velocity":2.1,"avg_scroll_depth":0.15,"typing_speed_wpm":85,"mouse_pattern":"scripted","session_start_variance_min":5}', '[{"type":"impossible_travel","severity":"high","detail":"Session from Manaus 45min after BH session","timestamp":"2024-12-14T22:30:00Z"},{"type":"device_switch","severity":"medium","detail":"New device DEV-099 appeared with rapid financial actions","timestamp":"2024-12-15T01:15:00Z"},{"type":"behavioral_drift","severity":"high","detail":"Typing speed 85wpm vs baseline 32wpm; click velocity 2.6x baseline","timestamp":"2024-12-15T01:20:00Z"}]', 'compromised', NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '8 months'),

('CPF-456.789.012-33', 'Ana Beatriz Costa', 'person', 71, 'medium', '{"avg_tx_amount": 5200, "tx_frequency_daily": 1.8, "primary_hours": [7,20], "top_recipients": ["PIX-fornecedor-alpha","PIX-folha-pagamento"], "avg_session_duration_min": 22, "typical_navigation": ["dashboard","transfers","reports","pix"]}', '[{"id":"DEV-005","type":"desktop","os":"macOS 14","browser":"Safari 17","first_seen":"2024-01-05","last_seen":"2024-12-15","trust":0.82}]', '{"primary_city":"Curitiba","primary_state":"PR","coords":[-25.4284,-49.2733],"secondary_locations":[{"city":"Florianopolis","frequency":0.08}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.55,"avg_scroll_depth":0.85,"typing_speed_wpm":52,"mouse_pattern":"organic","session_start_variance_min":28}', '[{"type":"unusual_recipient","severity":"medium","detail":"3 new recipients added in 24h vs avg 0.2/week","timestamp":"2024-12-14T16:00:00Z"}]', 'verified', NOW() - INTERVAL '4 hours', NOW() - INTERVAL '18 months'),

('CPF-567.890.123-44', 'Roberto Fernandes Jr', 'person', 15, 'critical', '{"avg_tx_amount": 150, "tx_frequency_daily": 0.3, "primary_hours": [12,14], "top_recipients": ["PIX-padaria-centro"], "avg_session_duration_min": 3, "typical_navigation": ["dashboard"]}', '[{"id":"DEV-006","type":"mobile","os":"Android 11","model":"Samsung A03","first_seen":"2024-09-01","last_seen":"2024-12-10","trust":0.7},{"id":"DEV-100","type":"desktop","os":"Linux","browser":"Firefox 120","first_seen":"2024-12-15","last_seen":"2024-12-15","trust":0.05},{"id":"DEV-101","type":"mobile","os":"iOS 17","model":"iPhone 15 Pro","first_seen":"2024-12-15","last_seen":"2024-12-15","trust":0.05}]', '{"primary_city":"Salvador","primary_state":"BA","coords":[-12.9714,-38.5124],"secondary_locations":[],"impossible_travel_incidents":4}', '{"avg_click_velocity":3.2,"avg_scroll_depth":0.05,"typing_speed_wpm":120,"mouse_pattern":"bot","session_start_variance_min":2}', '[{"type":"identity_theft","severity":"critical","detail":"Valid credentials used from 2 unknown devices simultaneously; behavioral fingerprint 0.08 similarity to baseline","timestamp":"2024-12-15T03:00:00Z"},{"type":"impossible_travel","severity":"critical","detail":"Concurrent sessions from Salvador and Moscow","timestamp":"2024-12-15T03:05:00Z"},{"type":"rapid_transfers","severity":"critical","detail":"12 PIX transfers in 8 minutes totaling R$45,000 to new recipients","timestamp":"2024-12-15T03:12:00Z"},{"type":"bot_behavior","severity":"critical","detail":"Mouse movement patterns indicate automated scripting; 0% organic interaction signature","timestamp":"2024-12-15T03:10:00Z"}]', 'compromised', NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '3 months'),

('CNPJ-12.345.678/0001-90', 'TechSolutions Ltda', 'business', 78, 'medium', '{"avg_tx_amount": 15000, "tx_frequency_daily": 12, "primary_hours": [8,18], "top_recipients": ["PIX-fornecedores-diversos","PIX-folha"], "avg_session_duration_min": 35, "typical_navigation": ["dashboard","batch-payments","reports"]}', '[{"id":"DEV-010","type":"desktop","os":"Windows 11","browser":"Edge 120","first_seen":"2024-01-10","last_seen":"2024-12-15","trust":0.9}]', '{"primary_city":"Sao Paulo","primary_state":"SP","coords":[-23.5505,-46.6333],"secondary_locations":[{"city":"Rio de Janeiro","frequency":0.1}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.6,"avg_scroll_depth":0.9,"typing_speed_wpm":55,"mouse_pattern":"organic","session_start_variance_min":15}', '[]', 'verified', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '24 months'),

('CPF-678.901.234-55', 'Lucas Gabriel Souza', 'person', 8, 'critical', '{"avg_tx_amount": 0, "tx_frequency_daily": 0, "primary_hours": [], "top_recipients": [], "avg_session_duration_min": 0, "typical_navigation": []}', '[{"id":"DEV-020","type":"mobile","os":"Android 13","model":"Poco X5","first_seen":"2024-12-14","last_seen":"2024-12-15","trust":0.15}]', '{"primary_city":"Unknown","primary_state":"Unknown","coords":[-15.7801,-47.9292],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":1.8,"avg_scroll_depth":0.3,"typing_speed_wpm":65,"mouse_pattern":"mixed","session_start_variance_min":0}', '[{"type":"synthetic_identity","severity":"critical","detail":"Account created 18h ago; immediate high-value PIX activity; no historical behavioral baseline; device fingerprint matches 3 other new accounts","timestamp":"2024-12-15T02:00:00Z"},{"type":"mule_network","severity":"critical","detail":"Received R$28,000 from 4 different compromised accounts within 2h; forwarded 95% to crypto exchange wallet","timestamp":"2024-12-15T04:00:00Z"}]', 'synthetic', NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '18 hours'),

('CPF-789.012.345-66', 'Juliana Mendes Rocha', 'person', 45, 'high', '{"avg_tx_amount": 3200, "tx_frequency_daily": 2.5, "primary_hours": [9,19], "top_recipients": ["PIX-aluguel","PIX-supermercado"], "avg_session_duration_min": 10, "typical_navigation": ["dashboard","pix","investments"]}', '[{"id":"DEV-030","type":"mobile","os":"iOS 16","model":"iPhone 14","first_seen":"2024-04-15","last_seen":"2024-12-13","trust":0.85},{"id":"DEV-031","type":"mobile","os":"Android 14","model":"Samsung S24 Ultra","first_seen":"2024-12-15","last_seen":"2024-12-15","trust":0.2}]', '{"primary_city":"Porto Alegre","primary_state":"RS","coords":[-30.0346,-51.2177],"secondary_locations":[{"city":"Gramado","frequency":0.05}],"impossible_travel_incidents":1}', '{"avg_click_velocity":1.4,"avg_scroll_depth":0.4,"typing_speed_wpm":58,"mouse_pattern":"semi-organic","session_start_variance_min":12}', '[{"type":"phishing_victim","severity":"high","detail":"Clicked link from SMS matching known PIX phishing campaign; entered credentials on spoofed banking portal","timestamp":"2024-12-14T19:30:00Z"},{"type":"credential_compromise","severity":"high","detail":"Session initiated from new device 4h after phishing interaction; changed PIX keys and added new recipients","timestamp":"2024-12-15T00:15:00Z"}]', 'suspicious', NOW() - INTERVAL '45 minutes', NOW() - INTERVAL '9 months'),

('API-INT-001', 'PaymentGateway API v3', 'api_integration', 62, 'medium', '{"avg_requests_min": 450, "typical_endpoints": ["/pix/initiate","/pix/status","/balance"], "error_rate": 0.02, "avg_payload_size_kb": 2.4}', '[]', '{"primary_region":"sa-east-1","secondary_regions":["us-east-1"]}', '{"avg_response_time_ms": 120, "p99_response_time_ms": 450}', '[{"type":"supply_chain_anomaly","severity":"medium","detail":"API request volume 3.2x normal; 15% of requests targeting /admin/config endpoint not in typical pattern","timestamp":"2024-12-15T05:00:00Z"}]', 'suspicious', NOW() - INTERVAL '20 minutes', NOW() - INTERVAL '6 months'),

('CPF-890.123.456-77', 'Fernando Augusto Barros', 'person', 88, 'low', '{"avg_tx_amount": 1200, "tx_frequency_daily": 1.8, "primary_hours": [8,17], "top_recipients": ["PIX-mercado-pago","PIX-nubank"], "avg_session_duration_min": 7, "typical_navigation": ["dashboard","pix","cards"]}', '[{"id":"DEV-040","type":"mobile","os":"iOS 17","model":"iPhone 15 Pro Max","first_seen":"2024-09-20","last_seen":"2024-12-15","trust":0.94}]', '{"primary_city":"Brasilia","primary_state":"DF","coords":[-15.7801,-47.9292],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.7,"avg_scroll_depth":0.75,"typing_speed_wpm":42,"mouse_pattern":"organic","session_start_variance_min":40}', '[]', 'verified', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '15 months'),

('CPF-901.234.567-88', 'Camila Rodrigues Pinto', 'person', 55, 'medium', '{"avg_tx_amount": 980, "tx_frequency_daily": 2.8, "primary_hours": [10,22], "top_recipients": ["PIX-ifood","PIX-uber","PIX-rent"], "avg_session_duration_min": 6, "typical_navigation": ["dashboard","pix"]}', '[{"id":"DEV-050","type":"mobile","os":"Android 14","model":"Pixel 8","first_seen":"2024-07-01","last_seen":"2024-12-15","trust":0.78}]', '{"primary_city":"Recife","primary_state":"PE","coords":[-8.0476,-34.877],"secondary_locations":[{"city":"Olinda","frequency":0.2}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.9,"avg_scroll_depth":0.6,"typing_speed_wpm":48,"mouse_pattern":"organic","session_start_variance_min":55}', '[{"type":"identity_selling","severity":"medium","detail":"Account behavioral fingerprint 87% similar to CPF-678.901.234-55; shared device fingerprint DEV-020 detected","timestamp":"2024-12-14T20:00:00Z"}]', 'suspicious', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '5 months'),

('CPF-012.345.678-99', 'Thiago Nascimento Silva', 'person', 22, 'critical', '{"avg_tx_amount": 500, "tx_frequency_daily": 0.8, "primary_hours": [11,15], "top_recipients": ["PIX-lanchonete"], "avg_session_duration_min": 4, "typical_navigation": ["dashboard","pix"]}', '[{"id":"DEV-060","type":"mobile","os":"Android 13","model":"Motorola G73","first_seen":"2024-05-15","last_seen":"2024-12-14","trust":0.65}]', '{"primary_city":"Fortaleza","primary_state":"CE","coords":[-3.7172,-38.5433],"secondary_locations":[],"impossible_travel_incidents":3}', '{"avg_click_velocity":2.8,"avg_scroll_depth":0.08,"typing_speed_wpm":105,"mouse_pattern":"bot","session_start_variance_min":3}', '[{"type":"banking_malware","severity":"critical","detail":"RAT signature detected in session; invisible overlay injection on PIX confirmation screen; transaction amounts modified in transit","timestamp":"2024-12-15T02:45:00Z"},{"type":"session_hijack","severity":"critical","detail":"WebSocket session token replayed from different IP; session integrity check failed","timestamp":"2024-12-15T02:50:00Z"}]', 'compromised', NOW() - INTERVAL '25 minutes', NOW() - INTERVAL '7 months'),

('CNPJ-98.765.432/0001-10', 'Global Imports Trading', 'business', 41, 'high', '{"avg_tx_amount": 85000, "tx_frequency_daily": 5, "primary_hours": [9,17], "top_recipients": ["WIRE-supplier-china","TED-logistics"], "avg_session_duration_min": 45, "typical_navigation": ["dashboard","wire-transfers","reports","compliance"]}', '[{"id":"DEV-070","type":"desktop","os":"Windows 11","browser":"Chrome 120","first_seen":"2024-02-01","last_seen":"2024-12-15","trust":0.75}]', '{"primary_city":"Santos","primary_state":"SP","coords":[-23.9608,-46.3336],"secondary_locations":[{"city":"Sao Paulo","frequency":0.3}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.5,"avg_scroll_depth":0.92,"typing_speed_wpm":50,"mouse_pattern":"organic","session_start_variance_min":20}', '[{"type":"unusual_amount","severity":"high","detail":"Wire transfer of R$450,000 to new supplier in Cyprus; 5.3x historical average; no prior relationship","timestamp":"2024-12-14T14:30:00Z"},{"type":"supply_chain_risk","severity":"medium","detail":"Destination entity registered 3 months ago in known shell company jurisdiction","timestamp":"2024-12-14T14:35:00Z"}]', 'suspicious', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '20 months'),

('CPF-111.222.333-44', 'Rafael Costa Martins', 'person', 95, 'low', '{"avg_tx_amount": 3500, "tx_frequency_daily": 2.0, "primary_hours": [8,19], "top_recipients": ["PIX-esposa","PIX-aluguel","PIX-colegio"], "avg_session_duration_min": 9, "typical_navigation": ["dashboard","pix","investments","cards"]}', '[{"id":"DEV-080","type":"mobile","os":"iOS 17","model":"iPhone 15","first_seen":"2024-10-01","last_seen":"2024-12-15","trust":0.96}]', '{"primary_city":"Campinas","primary_state":"SP","coords":[-22.9099,-47.0626],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.7,"avg_scroll_depth":0.8,"typing_speed_wpm":40,"mouse_pattern":"organic","session_start_variance_min":45}', '[]', 'verified', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '36 months'),

('CPF-222.333.444-55', 'Larissa Fernanda Alves', 'person', 68, 'medium', '{"avg_tx_amount": 1500, "tx_frequency_daily": 3.5, "primary_hours": [7,23], "top_recipients": ["PIX-shopping","PIX-streaming","PIX-gym"], "avg_session_duration_min": 11, "typical_navigation": ["dashboard","pix","cards","cashback"]}', '[{"id":"DEV-090","type":"mobile","os":"Android 14","model":"Samsung S23","first_seen":"2024-03-15","last_seen":"2024-12-15","trust":0.82}]', '{"primary_city":"Goiania","primary_state":"GO","coords":[-16.6869,-49.2648],"secondary_locations":[{"city":"Anapolis","frequency":0.1}],"impossible_travel_incidents":0}', '{"avg_click_velocity":1.1,"avg_scroll_depth":0.55,"typing_speed_wpm":52,"mouse_pattern":"organic","session_start_variance_min":30}', '[{"type":"deepfake_attempt","severity":"medium","detail":"Video verification submission flagged by liveness detection; facial landmarks inconsistency score 0.73","timestamp":"2024-12-14T11:00:00Z"}]', 'verified', NOW() - INTERVAL '8 hours', NOW() - INTERVAL '10 months'),

('CPF-333.444.555-66', 'Diego Henrique Moura', 'person', 12, 'critical', '{"avg_tx_amount": 0, "tx_frequency_daily": 0, "primary_hours": [], "top_recipients": [], "avg_session_duration_min": 0, "typical_navigation": []}', '[{"id":"DEV-020","type":"mobile","os":"Android 13","model":"Poco X5","first_seen":"2024-12-15","last_seen":"2024-12-15","trust":0.1}]', '{"primary_city":"Unknown","primary_state":"Unknown","coords":[-23.5505,-46.6333],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":2.5,"avg_scroll_depth":0.1,"typing_speed_wpm":90,"mouse_pattern":"scripted","session_start_variance_min":0}', '[{"type":"synthetic_identity","severity":"critical","detail":"Account created 6h ago; CPF validation inconsistency with Receita Federal; shared device DEV-020 with 2 other synthetic accounts","timestamp":"2024-12-15T06:00:00Z"},{"type":"mule_account","severity":"critical","detail":"Immediate R$15,000 inflow from 3 sources; 98% forwarded within 20min to crypto wallet","timestamp":"2024-12-15T06:30:00Z"}]', 'synthetic', NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '6 hours'),

('CPF-444.555.666-77', 'Patricia Lopes Oliveira', 'person', 79, 'low', '{"avg_tx_amount": 2800, "tx_frequency_daily": 2.2, "primary_hours": [9,18], "top_recipients": ["PIX-escola","PIX-mercado","PIX-farmacia"], "avg_session_duration_min": 8, "typical_navigation": ["dashboard","pix","extract"]}', '[{"id":"DEV-110","type":"mobile","os":"iOS 17","model":"iPhone 14 Pro","first_seen":"2024-06-01","last_seen":"2024-12-15","trust":0.9}]', '{"primary_city":"Florianopolis","primary_state":"SC","coords":[-27.5954,-48.548],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.6,"avg_scroll_depth":0.78,"typing_speed_wpm":35,"mouse_pattern":"organic","session_start_variance_min":50}', '[]', 'verified', NOW() - INTERVAL '4 hours', NOW() - INTERVAL '22 months'),

('CPF-555.666.777-88', 'Marcos Vinicius Ramos', 'person', 38, 'high', '{"avg_tx_amount": 750, "tx_frequency_daily": 1.2, "primary_hours": [10,16], "top_recipients": ["PIX-bar-esquina"], "avg_session_duration_min": 4, "typical_navigation": ["dashboard","pix"]}', '[{"id":"DEV-120","type":"mobile","os":"Android 12","model":"Samsung A13","first_seen":"2024-08-01","last_seen":"2024-12-14","trust":0.6}]', '{"primary_city":"Manaus","primary_state":"AM","coords":[-3.119,-60.0217],"secondary_locations":[],"impossible_travel_incidents":1}', '{"avg_click_velocity":1.6,"avg_scroll_depth":0.25,"typing_speed_wpm":70,"mouse_pattern":"semi-organic","session_start_variance_min":8}', '[{"type":"account_takeover","severity":"high","detail":"Password changed via recovery flow using SIM-swapped phone number; new device registered immediately","timestamp":"2024-12-14T23:00:00Z"},{"type":"rapid_transfers","severity":"high","detail":"5 PIX transfers totaling R$8,500 within 12 minutes to previously unknown recipients","timestamp":"2024-12-14T23:20:00Z"}]', 'compromised', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '4 months'),

('API-INT-002', 'CryptoExchange Bridge', 'api_integration', 55, 'medium', '{"avg_requests_min": 120, "typical_endpoints": ["/convert","/withdraw","/deposit"], "error_rate": 0.05, "avg_payload_size_kb": 1.8}', '[]', '{"primary_region":"us-east-1","secondary_regions":["eu-west-1"]}', '{"avg_response_time_ms": 200, "p99_response_time_ms": 800}', '[{"type":"supply_chain_anomaly","severity":"medium","detail":"Unusual withdrawal pattern: 45 withdrawals in 1h to wallets flagged by Chainalysis","timestamp":"2024-12-15T04:30:00Z"}]', 'suspicious', NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '4 months'),

('CPF-666.777.888-99', 'Isabela Cristina Santos', 'person', 82, 'low', '{"avg_tx_amount": 4100, "tx_frequency_daily": 2.8, "primary_hours": [8,20], "top_recipients": ["PIX-consultoria","PIX-aluguel-sala","PIX-contador"], "avg_session_duration_min": 18, "typical_navigation": ["dashboard","pix","reports","invoices"]}', '[{"id":"DEV-130","type":"desktop","os":"macOS 14","browser":"Chrome 120","first_seen":"2024-01-20","last_seen":"2024-12-15","trust":0.91},{"id":"DEV-131","type":"mobile","os":"iOS 17","model":"iPhone 15 Pro","first_seen":"2024-09-01","last_seen":"2024-12-15","trust":0.88}]', '{"primary_city":"Belo Horizonte","primary_state":"MG","coords":[-19.9191,-43.9386],"secondary_locations":[{"city":"Ouro Preto","frequency":0.03}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.55,"avg_scroll_depth":0.88,"typing_speed_wpm":58,"mouse_pattern":"organic","session_start_variance_min":25}', '[]', 'verified', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '30 months'),

('CPF-777.888.999-00', 'Anderson Luiz Pereira', 'person', 28, 'high', '{"avg_tx_amount": 600, "tx_frequency_daily": 0.5, "primary_hours": [12,14], "top_recipients": ["PIX-mercadinho"], "avg_session_duration_min": 3, "typical_navigation": ["dashboard"]}', '[{"id":"DEV-140","type":"mobile","os":"Android 11","model":"LG K62","first_seen":"2024-10-01","last_seen":"2024-12-13","trust":0.5}]', '{"primary_city":"Natal","primary_state":"RN","coords":[-5.7945,-35.211],"secondary_locations":[],"impossible_travel_incidents":2}', '{"avg_click_velocity":2.0,"avg_scroll_depth":0.12,"typing_speed_wpm":95,"mouse_pattern":"scripted","session_start_variance_min":4}', '[{"type":"ransomware_precursor","severity":"high","detail":"Lateral movement detected: RDP connections to 8 internal hosts from this accounts linked workstation; privilege escalation attempt via PrintNightmare exploit","timestamp":"2024-12-15T01:00:00Z"},{"type":"data_exfil","severity":"high","detail":"Unusual data access pattern: 2.3GB of customer PII exported from CRM in 15 minutes","timestamp":"2024-12-15T01:30:00Z"}]', 'compromised', NOW() - INTERVAL '40 minutes', NOW() - INTERVAL '2 months'),

('CPF-888.999.000-11', 'Gabriela Ferreira Lima', 'person', 91, 'low', '{"avg_tx_amount": 1900, "tx_frequency_daily": 3.0, "primary_hours": [7,21], "top_recipients": ["PIX-mae","PIX-academia","PIX-netflix"], "avg_session_duration_min": 9, "typical_navigation": ["dashboard","pix","investments","cards"]}', '[{"id":"DEV-150","type":"mobile","os":"iOS 17","model":"iPhone 15","first_seen":"2024-11-01","last_seen":"2024-12-15","trust":0.93}]', '{"primary_city":"Vitoria","primary_state":"ES","coords":[-20.3155,-40.3128],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.75,"avg_scroll_depth":0.7,"typing_speed_wpm":43,"mouse_pattern":"organic","session_start_variance_min":38}', '[]', 'verified', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '13 months'),

('CPF-999.000.111-22', 'Rodrigo Almeida Neto', 'person', 60, 'medium', '{"avg_tx_amount": 2100, "tx_frequency_daily": 1.5, "primary_hours": [9,17], "top_recipients": ["PIX-aluguel","PIX-energia","PIX-internet"], "avg_session_duration_min": 6, "typical_navigation": ["dashboard","pix","bills"]}', '[{"id":"DEV-160","type":"mobile","os":"Android 14","model":"Pixel 8 Pro","first_seen":"2024-08-15","last_seen":"2024-12-15","trust":0.8}]', '{"primary_city":"Cuiaba","primary_state":"MT","coords":[-15.6014,-56.0979],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.85,"avg_scroll_depth":0.65,"typing_speed_wpm":47,"mouse_pattern":"organic","session_start_variance_min":33}', '[{"type":"social_engineering","severity":"medium","detail":"Incoming call from spoofed bank number preceded unusual PIX transfer to new recipient; call duration 8min","timestamp":"2024-12-14T15:00:00Z"}]', 'verified', NOW() - INTERVAL '7 hours', NOW() - INTERVAL '11 months'),

('CNPJ-11.222.333/0001-44', 'Farmacia Popular Rede', 'business', 86, 'low', '{"avg_tx_amount": 8500, "tx_frequency_daily": 25, "primary_hours": [6,22], "top_recipients": ["PIX-distribuidora","TED-pharma-supply"], "avg_session_duration_min": 15, "typical_navigation": ["dashboard","batch-payments","inventory","reports"]}', '[{"id":"DEV-170","type":"desktop","os":"Windows 10","browser":"Chrome 119","first_seen":"2023-06-01","last_seen":"2024-12-15","trust":0.88}]', '{"primary_city":"Sao Paulo","primary_state":"SP","coords":[-23.5505,-46.6333],"secondary_locations":[{"city":"Osasco","frequency":0.15},{"city":"Guarulhos","frequency":0.1}],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.5,"avg_scroll_depth":0.9,"typing_speed_wpm":45,"mouse_pattern":"organic","session_start_variance_min":20}', '[]', 'verified', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '30 months'),

('CPF-000.111.222-33', 'Vanessa Torres Gomes', 'person', 48, 'high', '{"avg_tx_amount": 1100, "tx_frequency_daily": 2.0, "primary_hours": [9,18], "top_recipients": ["PIX-feira","PIX-gas"], "avg_session_duration_min": 5, "typical_navigation": ["dashboard","pix"]}', '[{"id":"DEV-180","type":"mobile","os":"Android 13","model":"Realme 11","first_seen":"2024-04-01","last_seen":"2024-12-15","trust":0.7}]', '{"primary_city":"Joao Pessoa","primary_state":"PB","coords":[-7.115,-34.861],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":1.3,"avg_scroll_depth":0.4,"typing_speed_wpm":55,"mouse_pattern":"semi-organic","session_start_variance_min":18}', '[{"type":"identity_selling","severity":"high","detail":"Account credentials found on dark web marketplace; behavioral shift detected post-listing; 3 distinct behavioral fingerprints observed in last 48h","timestamp":"2024-12-13T22:00:00Z"}]', 'suspicious', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '8 months'),

('CNPJ-55.666.777/0001-88', 'FinConnect Payments SA', 'api_integration', 72, 'medium', '{"avg_requests_min": 800, "typical_endpoints": ["/pix/qr-code","/pix/confirm","/status"], "error_rate": 0.01, "avg_payload_size_kb": 3.2}', '[]', '{"primary_region":"sa-east-1","secondary_regions":["sa-east-2"]}', '{"avg_response_time_ms": 85, "p99_response_time_ms": 350}', '[{"type":"api_abuse","severity":"medium","detail":"Unusual spike in QR code generation: 12,000 requests in 10min vs baseline 800/min; potential fraud farm operation","timestamp":"2024-12-15T05:30:00Z"}]', 'verified', NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '12 months'),

('CPF-112.233.445-56', 'Felipe Souza Barbosa', 'person', 75, 'low', '{"avg_tx_amount": 2000, "tx_frequency_daily": 1.8, "primary_hours": [8,18], "top_recipients": ["PIX-freelance-client","PIX-rent"], "avg_session_duration_min": 7, "typical_navigation": ["dashboard","pix","investments"]}', '[{"id":"DEV-190","type":"mobile","os":"iOS 17","model":"iPhone 14","first_seen":"2024-05-01","last_seen":"2024-12-15","trust":0.87}]', '{"primary_city":"Ribeirao Preto","primary_state":"SP","coords":[-21.1767,-47.8208],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.8,"avg_scroll_depth":0.7,"typing_speed_wpm":44,"mouse_pattern":"organic","session_start_variance_min":35}', '[]', 'verified', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '16 months'),

('CPF-223.344.556-67', 'Renata Dias Campos', 'person', 5, 'critical', '{"avg_tx_amount": 0, "tx_frequency_daily": 0, "primary_hours": [], "top_recipients": [], "avg_session_duration_min": 0, "typical_navigation": []}', '[{"id":"DEV-200","type":"desktop","os":"Linux","browser":"Tor Browser","first_seen":"2024-12-15","last_seen":"2024-12-15","trust":0.02}]', '{"primary_city":"Unknown","primary_state":"Unknown","coords":[0,0],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":4.0,"avg_scroll_depth":0.02,"typing_speed_wpm":150,"mouse_pattern":"bot","session_start_variance_min":0}', '[{"type":"synthetic_identity","severity":"critical","detail":"Tor-based registration with stolen CPF; fully automated onboarding completed in 47 seconds; immediate API key generation","timestamp":"2024-12-15T07:00:00Z"},{"type":"mule_automation","severity":"critical","detail":"Automated PIX forwarding script detected; 23 micro-transactions in 3 minutes to distributed wallets","timestamp":"2024-12-15T07:05:00Z"}]', 'synthetic', NOW() - INTERVAL '2 minutes', NOW() - INTERVAL '2 hours'),

('CPF-334.455.667-78', 'Bruno Costa Ferreira', 'person', 83, 'low', '{"avg_tx_amount": 1600, "tx_frequency_daily": 2.5, "primary_hours": [7,19], "top_recipients": ["PIX-esposa","PIX-mercado","PIX-escola-filho"], "avg_session_duration_min": 8, "typical_navigation": ["dashboard","pix","savings"]}', '[{"id":"DEV-210","type":"mobile","os":"Android 14","model":"Samsung S24","first_seen":"2024-10-15","last_seen":"2024-12-15","trust":0.91}]', '{"primary_city":"Uberlandia","primary_state":"MG","coords":[-18.9186,-48.2772],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":0.65,"avg_scroll_depth":0.82,"typing_speed_wpm":40,"mouse_pattern":"organic","session_start_variance_min":42}', '[]', 'verified', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '14 months'),

('CPF-445.556.778-89', 'Aline Marques Ribeiro', 'person', 57, 'medium', '{"avg_tx_amount": 900, "tx_frequency_daily": 4.0, "primary_hours": [6,23], "top_recipients": ["PIX-uber","PIX-rappi","PIX-99"], "avg_session_duration_min": 4, "typical_navigation": ["dashboard","pix"]}', '[{"id":"DEV-220","type":"mobile","os":"Android 13","model":"Motorola Edge 40","first_seen":"2024-07-01","last_seen":"2024-12-15","trust":0.76}]', '{"primary_city":"Belém","primary_state":"PA","coords":[-1.4558,-48.5024],"secondary_locations":[],"impossible_travel_incidents":0}', '{"avg_click_velocity":1.0,"avg_scroll_depth":0.5,"typing_speed_wpm":50,"mouse_pattern":"organic","session_start_variance_min":25}', '[{"type":"unusual_pattern","severity":"medium","detail":"Transaction frequency doubled in last 24h; 3 new recipients added; amounts increasing progressively","timestamp":"2024-12-14T18:00:00Z"}]', 'verified', NOW() - INTERVAL '4 hours', NOW() - INTERVAL '6 months');
