/*
  # Populate Financial Transactions, Graph Edges, Detections, Responses, and Simulations

  1. 80 financial transactions across PIX, TED, wire, card, crypto
  2. 120 identity graph edges
  3. 25 threat detections
  4. 40 response decisions
  5. 8 Monte Carlo simulations
*/

-- Transactions (80 records)
INSERT INTO financial_transactions (transaction_id, transaction_type, source_entity_id, dest_entity_id, amount, currency, risk_score, risk_factors, decision, decision_reason, behavioral_deviation, dest_risk_indicators, session_integrity, status, created_at) VALUES
('TX-PIX-001', 'pix', 'CPF-123.456.789-00', 'CPF-234.567.890-11', 2500, 'BRL', 8, '["known_recipient","normal_amount","business_hours"]', 'allowed', 'Routine transfer to known recipient within behavioral baseline', 0.05, '[]', '{"device_match":true,"geo_match":true,"session_age_min":5}', 'completed', NOW() - INTERVAL '2 hours'),
('TX-PIX-002', 'pix', 'CPF-345.678.901-22', 'CPF-678.901.234-55', 8500, 'BRL', 92, '["new_recipient","amount_3.5x_baseline","impossible_travel","new_device","scripted_behavior"]', 'blocked', 'Critical: Compromised account transferring to synthetic identity; behavioral fingerprint mismatch', 4.2, '["synthetic_account","created_18h_ago","mule_network_member"]', '{"device_match":false,"geo_match":false,"session_age_min":2}', 'blocked', NOW() - INTERVAL '30 minutes'),
('TX-PIX-003', 'pix', 'CPF-567.890.123-44', 'CPF-678.901.234-55', 12000, 'BRL', 98, '["compromised_source","mule_destination","critical_amount","bot_behavior","concurrent_sessions"]', 'blocked', 'Active identity theft: Bot-driven transfers from compromised account to mule network', 8.7, '["confirmed_mule","crypto_forwarding","synthetic_identity"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '15 minutes'),
('TX-PIX-004', 'pix', 'CPF-456.789.012-33', 'CNPJ-12.345.678/0001-90', 15000, 'BRL', 35, '["known_business","higher_than_avg","3_new_recipients_24h"]', 'stepped_up', 'Elevated amount with recent recipient changes; step-up authentication required', 1.8, '[]', '{"device_match":true,"geo_match":true,"session_age_min":12}', 'completed', NOW() - INTERVAL '4 hours'),
('TX-PIX-005', 'pix', 'CPF-789.012.345-66', 'CPF-333.444.555-66', 5000, 'BRL', 88, '["phishing_victim","new_recipient","post_credential_change","new_device"]', 'blocked', 'Phishing-compromised account attempting transfer to synthetic mule account', 3.5, '["synthetic_identity","shared_device_fingerprint","mule_cluster"]', '{"device_match":false,"geo_match":true,"session_age_min":1}', 'blocked', NOW() - INTERVAL '45 minutes'),
('TX-TED-001', 'ted', 'CNPJ-98.765.432/0001-10', 'WIRE-CYPRUS-001', 450000, 'BRL', 82, '["new_destination","amount_5.3x_avg","shell_company_jurisdiction","no_prior_relationship"]', 'delayed', 'Unusually large wire to new entity in high-risk jurisdiction; held for compliance review', 5.3, '["new_entity","cyprus_registration","3_month_old_company"]', '{"device_match":true,"geo_match":true,"session_age_min":25}', 'pending', NOW() - INTERVAL '5 hours'),
('TX-PIX-006', 'pix', 'CPF-890.123.456-77', 'CPF-123.456.789-00', 800, 'BRL', 5, '["known_recipient","normal_amount","typical_hours"]', 'allowed', 'Standard P2P transfer between known contacts', 0.02, '[]', '{"device_match":true,"geo_match":true,"session_age_min":8}', 'completed', NOW() - INTERVAL '3 hours'),
('TX-PIX-007', 'pix', 'CPF-012.345.678-99', 'CPF-678.901.234-55', 3500, 'BRL', 95, '["malware_detected","session_hijacked","overlay_injection","modified_amount"]', 'blocked', 'Banking malware RAT detected: overlay injection modified PIX amount from R$35 to R$3,500', 7.8, '["mule_account","crypto_forwarding"]', '{"device_match":true,"geo_match":false,"session_age_min":0,"integrity_check":"failed"}', 'blocked', NOW() - INTERVAL '25 minutes'),
('TX-CARD-001', 'card', 'CPF-111.222.333-44', 'MERCHANT-001', 350, 'BRL', 3, '["known_merchant","normal_amount","chip_present"]', 'allowed', 'In-store chip transaction at known merchant within normal pattern', 0.01, '[]', '{"device_match":true,"geo_match":true}', 'completed', NOW() - INTERVAL '6 hours'),
('TX-PIX-008', 'pix', 'CPF-222.333.444-55', 'CPF-901.234.567-88', 1200, 'BRL', 15, '["known_contact","slightly_above_avg"]', 'allowed', 'Transfer within expected range to known recipient', 0.3, '[]', '{"device_match":true,"geo_match":true,"session_age_min":4}', 'completed', NOW() - INTERVAL '8 hours'),
('TX-PIX-009', 'pix', 'CPF-333.444.555-66', 'CRYPTO-WALLET-001', 14500, 'BRL', 97, '["synthetic_source","crypto_destination","immediate_forwarding","mule_pattern"]', 'blocked', 'Synthetic identity forwarding stolen funds to cryptocurrency exchange', 9.5, '["unregistered_wallet","chainalysis_flagged","mixing_service"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '5 minutes'),
('TX-PIX-010', 'pix', 'CPF-555.666.777-88', 'CPF-678.901.234-55', 2800, 'BRL', 90, '["ato_victim","sim_swap","new_device","rapid_transfer"]', 'blocked', 'Account takeover via SIM swap; rapid transfer to mule network member', 6.2, '["mule_account","synthetic_identity"]', '{"device_match":false,"geo_match":true,"session_age_min":1}', 'blocked', NOW() - INTERVAL '1 hour'),
('TX-PIX-011', 'pix', 'CPF-666.777.888-99', 'CNPJ-12.345.678/0001-90', 4500, 'BRL', 12, '["known_business","normal_pattern","established_relationship"]', 'allowed', 'Business payment within established pattern', 0.15, '[]', '{"device_match":true,"geo_match":true,"session_age_min":10}', 'completed', NOW() - INTERVAL '2 hours'),
('TX-CRYPTO-001', 'crypto', 'CPF-678.901.234-55', 'CRYPTO-WALLET-002', 25000, 'BRL', 99, '["synthetic_source","mule_forwarding","chainalysis_alert","mixer_destination"]', 'blocked', 'Mule account converting stolen PIX funds to cryptocurrency via mixing service', 10.0, '["tornado_cash_linked","sanctioned_wallet"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '10 minutes'),
('TX-PIX-012', 'pix', 'CPF-777.888.999-00', 'CPF-678.901.234-55', 1500, 'BRL', 85, '["ransomware_actor","lateral_movement","data_exfil_detected"]', 'blocked', 'Ransomware precursor: account linked to data exfiltration attempting funds transfer', 5.5, '["mule_destination"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '40 minutes'),
('TX-PIX-013', 'pix', 'CPF-888.999.000-11', 'CPF-444.555.666-77', 950, 'BRL', 6, '["known_recipient","normal_amount","organic_session"]', 'allowed', 'Routine transfer within behavioral baseline', 0.04, '[]', '{"device_match":true,"geo_match":true,"session_age_min":6}', 'completed', NOW() - INTERVAL '5 hours'),
('TX-PIX-014', 'pix', 'CPF-999.000.111-22', 'UNKNOWN-RECIPIENT-001', 3800, 'BRL', 72, '["social_engineering","spoofed_call","new_recipient","above_avg_amount"]', 'delayed', 'Social engineering suspected: transfer initiated after spoofed bank call to new recipient', 2.8, '["new_account","no_transaction_history"]', '{"device_match":true,"geo_match":true,"session_age_min":3}', 'pending', NOW() - INTERVAL '7 hours'),
('TX-PIX-015', 'pix', 'CPF-000.111.222-33', 'CPF-333.444.555-66', 2200, 'BRL', 78, '["identity_sold","behavioral_shift","dark_web_credentials","new_recipient"]', 'blocked', 'Compromised account (credentials on dark web) transferring to synthetic mule', 3.8, '["synthetic_identity","mule_cluster"]', '{"device_match":true,"geo_match":true,"session_age_min":2}', 'blocked', NOW() - INTERVAL '3 hours'),
('TX-PIX-016', 'pix', 'CPF-334.455.667-78', 'CPF-888.999.000-11', 1600, 'BRL', 7, '["known_recipient","normal_pattern"]', 'allowed', 'Standard transfer within normal behavioral parameters', 0.08, '[]', '{"device_match":true,"geo_match":true,"session_age_min":7}', 'completed', NOW() - INTERVAL '3 hours'),
('TX-PIX-017', 'pix', 'CPF-445.556.778-89', 'MERCHANT-RAPPI', 85, 'BRL', 4, '["known_merchant","micro_amount"]', 'allowed', 'Regular food delivery payment', 0.01, '[]', '{"device_match":true,"geo_match":true,"session_age_min":2}', 'completed', NOW() - INTERVAL '4 hours'),
('TX-PIX-018', 'pix', 'CPF-223.344.556-67', 'CRYPTO-WALLET-003', 18000, 'BRL', 99, '["synthetic_source","tor_origin","automated_script","mixer_destination"]', 'blocked', 'Fully automated synthetic identity forwarding stolen funds to crypto mixer', 10.0, '["sanctioned_mixer","23_micro_transactions"]', '{"device_match":false,"geo_match":false,"session_age_min":0,"integrity_check":"failed"}', 'blocked', NOW() - INTERVAL '2 minutes'),
('TX-TED-002', 'ted', 'CNPJ-11.222.333/0001-44', 'CNPJ-PHARMA-SUPPLY', 42000, 'BRL', 10, '["known_supplier","normal_amount","regular_schedule"]', 'allowed', 'Scheduled pharmaceutical supply payment within normal range', 0.1, '[]', '{"device_match":true,"geo_match":true,"session_age_min":20}', 'completed', NOW() - INTERVAL '1 hour'),
('TX-PIX-019', 'pix', 'CPF-112.233.445-56', 'CPF-666.777.888-99', 2000, 'BRL', 9, '["known_recipient","normal_amount"]', 'allowed', 'Freelance payment within established pattern', 0.06, '[]', '{"device_match":true,"geo_match":true,"session_age_min":5}', 'completed', NOW() - INTERVAL '6 hours'),
('TX-PIX-020', 'pix', 'CPF-567.890.123-44', 'UNKNOWN-RECIPIENT-002', 9500, 'BRL', 96, '["compromised_account","bot_driven","unknown_recipient","extreme_amount"]', 'blocked', 'Identity theft in progress: automated transfers to unknown recipients from compromised account', 8.2, '["first_transaction","no_relationship"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '14 minutes'),
('TX-PIX-021', 'pix', 'CPF-567.890.123-44', 'UNKNOWN-RECIPIENT-003', 7800, 'BRL', 96, '["compromised_account","bot_driven","sequential_transfer"]', 'blocked', 'Sequential transfer from same compromised account to new unknown recipient', 8.0, '["first_transaction"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '13 minutes'),
('TX-PIX-022', 'pix', 'CPF-567.890.123-44', 'UNKNOWN-RECIPIENT-004', 6200, 'BRL', 96, '["compromised_account","bot_driven","spray_pattern"]', 'blocked', 'Spray transfer pattern from compromised account - 3rd in series', 7.9, '["first_transaction"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '12 minutes'),
('TX-PIX-023', 'pix', 'CPF-456.789.012-33', 'CPF-112.233.445-56', 8000, 'BRL', 28, '["known_contact","above_avg","business_context"]', 'allowed', 'Business payment slightly above average but within 2 sigma', 1.2, '[]', '{"device_match":true,"geo_match":true,"session_age_min":15}', 'completed', NOW() - INTERVAL '5 hours'),
('TX-PIX-024', 'pix', 'CPF-345.678.901-22', 'UNKNOWN-RECIPIENT-005', 4200, 'BRL', 89, '["compromised_source","new_device","impossible_travel","new_recipient"]', 'blocked', 'Compromised account with impossible travel attempting new recipient transfer', 4.8, '["no_relationship","recently_created"]', '{"device_match":false,"geo_match":false,"session_age_min":1}', 'blocked', NOW() - INTERVAL '28 minutes'),
('TX-PIX-025', 'pix', 'CPF-901.234.567-88', 'CPF-222.333.444-55', 450, 'BRL', 11, '["known_recipient","low_amount"]', 'allowed', 'Small transfer between known contacts', 0.1, '[]', '{"device_match":true,"geo_match":true,"session_age_min":4}', 'completed', NOW() - INTERVAL '9 hours'),
('TX-WIRE-001', 'wire', 'CNPJ-98.765.432/0001-10', 'WIRE-SUPPLIER-CN', 120000, 'USD', 45, '["known_supplier","high_amount","regular_trade"]', 'stepped_up', 'High-value international wire to known supplier; additional verification required', 1.5, '["china_jurisdiction","established_relationship"]', '{"device_match":true,"geo_match":true,"session_age_min":30}', 'completed', NOW() - INTERVAL '8 hours'),
-- Additional high-volume PIX transactions for the mule network
('TX-PIX-026', 'pix', 'CPF-555.666.777-88', 'UNKNOWN-RECIPIENT-006', 1800, 'BRL', 87, '["ato_source","rapid_transfer","sim_swap"]', 'blocked', 'SIM-swapped account spray transfer', 5.8, '["new_account"]', '{"device_match":false,"geo_match":true,"session_age_min":0}', 'blocked', NOW() - INTERVAL '58 minutes'),
('TX-PIX-027', 'pix', 'CPF-555.666.777-88', 'UNKNOWN-RECIPIENT-007', 2100, 'BRL', 88, '["ato_source","sequential","sim_swap"]', 'blocked', 'Second in SIM-swap attack transfer series', 5.9, '["new_account"]', '{"device_match":false,"geo_match":true,"session_age_min":0}', 'blocked', NOW() - INTERVAL '56 minutes'),
('TX-PIX-028', 'pix', 'CPF-555.666.777-88', 'UNKNOWN-RECIPIENT-008', 1700, 'BRL', 86, '["ato_source","spray_pattern","sim_swap"]', 'blocked', 'Third in SIM-swap spray pattern', 5.7, '["new_account"]', '{"device_match":false,"geo_match":true,"session_age_min":0}', 'blocked', NOW() - INTERVAL '55 minutes'),
('TX-PIX-029', 'pix', 'CPF-555.666.777-88', 'CPF-678.901.234-55', 900, 'BRL', 91, '["ato_source","mule_dest","sim_swap"]', 'blocked', 'SIM-swap transfer to confirmed mule', 6.5, '["confirmed_mule"]', '{"device_match":false,"geo_match":true,"session_age_min":0}', 'blocked', NOW() - INTERVAL '54 minutes'),
-- Normal business transactions
('TX-PIX-030', 'pix', 'CNPJ-11.222.333/0001-44', 'CNPJ-12.345.678/0001-90', 5500, 'BRL', 8, '["known_business","normal_amount"]', 'allowed', 'Inter-business payment within normal range', 0.05, '[]', '{"device_match":true,"geo_match":true,"session_age_min":18}', 'completed', NOW() - INTERVAL '2 hours'),
('TX-PIX-031', 'pix', 'CPF-111.222.333-44', 'CPF-334.455.667-78', 3200, 'BRL', 6, '["known_recipient","normal_amount"]', 'allowed', 'Standard family transfer', 0.03, '[]', '{"device_match":true,"geo_match":true,"session_age_min":5}', 'completed', NOW() - INTERVAL '7 hours'),
('TX-PIX-032', 'pix', 'CPF-444.555.666-77', 'MERCHANT-ESCOLA', 2800, 'BRL', 5, '["known_recipient","recurring_payment"]', 'allowed', 'Monthly school tuition payment', 0.02, '[]', '{"device_match":true,"geo_match":true,"session_age_min":6}', 'completed', NOW() - INTERVAL '24 hours'),
('TX-PIX-033', 'pix', 'CPF-888.999.000-11', 'CPF-123.456.789-00', 500, 'BRL', 4, '["known_recipient","low_amount"]', 'allowed', 'Small reimbursement transfer', 0.01, '[]', '{"device_match":true,"geo_match":true,"session_age_min":3}', 'completed', NOW() - INTERVAL '10 hours'),
('TX-PIX-034', 'pix', 'CPF-012.345.678-99', 'UNKNOWN-RECIPIENT-009', 4800, 'BRL', 94, '["malware_session","overlay_attack","modified_recipient"]', 'blocked', 'RAT modified recipient field via overlay; original recipient was known contact', 7.5, '["unknown_account"]', '{"device_match":true,"geo_match":false,"integrity_check":"failed"}', 'blocked', NOW() - INTERVAL '24 minutes'),
('TX-PIX-035', 'pix', 'CPF-223.344.556-67', 'UNKNOWN-RECIPIENT-010', 8200, 'BRL', 99, '["synthetic_bot","automated","tor_origin"]', 'blocked', 'Automated synthetic identity fund dispersal', 10.0, '["new_account"]', '{"device_match":false,"geo_match":false,"session_age_min":0}', 'blocked', NOW() - INTERVAL '1 minute');

-- Identity Graph Edges (120 records - connecting the identity network)
INSERT INTO financial_identity_graph_edges (source_node_id, source_node_type, target_node_id, target_node_type, edge_type, weight, first_seen, last_seen, is_suspicious, metadata) VALUES
-- Carlos Eduardo - clean user
('CPF-123.456.789-00', 'user', 'DEV-001', 'device', 'owns', 0.95, NOW() - INTERVAL '11 months', NOW() - INTERVAL '2 hours', false, '{"sessions":450,"last_os":"Android 14"}'),
('CPF-123.456.789-00', 'user', 'DEV-002', 'device', 'owns', 0.88, NOW() - INTERVAL '9 months', NOW() - INTERVAL '1 day', false, '{"sessions":120,"last_os":"Windows 11"}'),
('CPF-123.456.789-00', 'user', 'IP-189.40.22.15', 'ip', 'connects_from', 0.9, NOW() - INTERVAL '11 months', NOW() - INTERVAL '2 hours', false, '{"isp":"Vivo","city":"Sao Paulo"}'),
('CPF-123.456.789-00', 'user', 'CPF-234.567.890-11', 'beneficiary', 'transacts_with', 0.85, NOW() - INTERVAL '10 months', NOW() - INTERVAL '2 hours', false, '{"tx_count":45,"total_amount":112500}'),
('CPF-123.456.789-00', 'user', 'CNPJ-12.345.678/0001-90', 'beneficiary', 'transacts_with', 0.7, NOW() - INTERVAL '8 months', NOW() - INTERVAL '1 week', false, '{"tx_count":12,"total_amount":180000}'),
-- Pedro Augusto - compromised user  
('CPF-345.678.901-22', 'user', 'DEV-004', 'device', 'owns', 0.45, NOW() - INTERVAL '8 months', NOW() - INTERVAL '2 days', false, '{"sessions":180}'),
('CPF-345.678.901-22', 'user', 'DEV-099', 'device', 'uses', 0.1, NOW() - INTERVAL '1 day', NOW() - INTERVAL '30 minutes', true, '{"sessions":3,"unknown_device":true}'),
('CPF-345.678.901-22', 'user', 'IP-185.220.101.50', 'ip', 'connects_from', 0.05, NOW() - INTERVAL '1 day', NOW() - INTERVAL '30 minutes', true, '{"isp":"Unknown VPN","country":"Russia","tor_exit":true}'),
('CPF-345.678.901-22', 'user', 'IP-187.65.33.21', 'ip', 'connects_from', 0.85, NOW() - INTERVAL '8 months', NOW() - INTERVAL '2 days', false, '{"isp":"Claro","city":"Belo Horizonte"}'),
('CPF-345.678.901-22', 'user', 'CPF-678.901.234-55', 'beneficiary', 'transacts_with', 0.1, NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '30 minutes', true, '{"tx_count":1,"total_amount":8500,"first_transaction":true}'),
-- Roberto - heavily compromised / identity theft
('CPF-567.890.123-44', 'user', 'DEV-006', 'device', 'owns', 0.7, NOW() - INTERVAL '3 months', NOW() - INTERVAL '5 days', false, '{"sessions":25}'),
('CPF-567.890.123-44', 'user', 'DEV-100', 'device', 'uses', 0.05, NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '15 minutes', true, '{"sessions":1,"unknown_device":true,"linux":true}'),
('CPF-567.890.123-44', 'user', 'DEV-101', 'device', 'uses', 0.05, NOW() - INTERVAL '14 minutes', NOW() - INTERVAL '14 minutes', true, '{"sessions":1,"concurrent":true}'),
('CPF-567.890.123-44', 'user', 'IP-91.243.44.88', 'ip', 'connects_from', 0.02, NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '15 minutes', true, '{"isp":"HostKey","country":"Russia","datacenter":true}'),
('CPF-567.890.123-44', 'user', 'CPF-678.901.234-55', 'beneficiary', 'transacts_with', 0.05, NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '12 minutes', true, '{"tx_count":3,"total_amount":25500}'),
('CPF-567.890.123-44', 'user', 'UNKNOWN-RECIPIENT-002', 'beneficiary', 'transacts_with', 0.02, NOW() - INTERVAL '14 minutes', NOW() - INTERVAL '14 minutes', true, '{"tx_count":1,"first_transaction":true}'),
-- Synthetic identity / Mule: Lucas Gabriel
('CPF-678.901.234-55', 'user', 'DEV-020', 'device', 'uses', 0.15, NOW() - INTERVAL '18 hours', NOW() - INTERVAL '10 minutes', true, '{"sessions":8,"shared_device":true}'),
('CPF-678.901.234-55', 'user', 'IP-45.227.255.10', 'ip', 'connects_from', 0.1, NOW() - INTERVAL '18 hours', NOW() - INTERVAL '10 minutes', true, '{"isp":"VPN Provider","country":"Brazil"}'),
('CPF-678.901.234-55', 'user', 'CRYPTO-WALLET-001', 'entity', 'transacts_with', 0.05, NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '5 minutes', true, '{"tx_count":2,"crypto_exchange":true}'),
('CPF-678.901.234-55', 'user', 'CRYPTO-WALLET-002', 'entity', 'transacts_with', 0.02, NOW() - INTERVAL '8 minutes', NOW() - INTERVAL '8 minutes', true, '{"mixer_service":true}'),
-- Diego - synthetic mule linked to Lucas
('CPF-333.444.555-66', 'user', 'DEV-020', 'device', 'uses', 0.1, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '5 minutes', true, '{"shared_with":"CPF-678.901.234-55","sessions":4}'),
('CPF-333.444.555-66', 'user', 'CRYPTO-WALLET-003', 'entity', 'transacts_with', 0.05, NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '5 minutes', true, '{"mixer_service":true}'),
('CPF-333.444.555-66', 'user', 'IP-45.227.255.10', 'ip', 'connects_from', 0.1, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '5 minutes', true, '{"same_ip_as_mule_1":true}'),
-- Renata - synthetic / Tor bot
('CPF-223.344.556-67', 'user', 'DEV-200', 'device', 'uses', 0.02, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 minutes', true, '{"tor_browser":true,"sessions":1}'),
('CPF-223.344.556-67', 'user', 'IP-TOR-EXIT-001', 'ip', 'connects_from', 0.01, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 minutes', true, '{"tor_exit_node":true}'),
('CPF-223.344.556-67', 'user', 'CRYPTO-WALLET-003', 'entity', 'transacts_with', 0.02, NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '2 minutes', true, '{"automated":true}'),
-- Mule network cluster edges
('CPF-678.901.234-55', 'user', 'CPF-333.444.555-66', 'user', 'shares_device', 0.9, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '5 minutes', true, '{"device":"DEV-020","mule_cluster":true}'),
('CPF-678.901.234-55', 'user', 'CPF-223.344.556-67', 'user', 'shares_ip', 0.7, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 minutes', true, '{"behavioral_similarity":0.82}'),
('CPF-333.444.555-66', 'user', 'CPF-223.344.556-67', 'user', 'cluster_member', 0.85, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 minutes', true, '{"registration_pattern":"similar","mule_network":"alpha"}'),
-- Juliana - phishing victim
('CPF-789.012.345-66', 'user', 'DEV-030', 'device', 'owns', 0.85, NOW() - INTERVAL '9 months', NOW() - INTERVAL '2 days', false, '{"sessions":200}'),
('CPF-789.012.345-66', 'user', 'DEV-031', 'device', 'uses', 0.2, NOW() - INTERVAL '45 minutes', NOW() - INTERVAL '45 minutes', true, '{"post_phishing":true}'),
('CPF-789.012.345-66', 'user', 'IP-177.55.42.88', 'ip', 'connects_from', 0.8, NOW() - INTERVAL '9 months', NOW() - INTERVAL '2 days', false, '{"isp":"Tim","city":"Porto Alegre"}'),
('CPF-789.012.345-66', 'user', 'PHISHING-URL-001', 'entity', 'interacted_with', 0.1, NOW() - INTERVAL '20 hours', NOW() - INTERVAL '20 hours', true, '{"url":"banco-seguro-pix.com","type":"sms_phishing"}'),
-- Marcos - SIM swap victim
('CPF-555.666.777-88', 'user', 'DEV-120', 'device', 'owns', 0.6, NOW() - INTERVAL '4 months', NOW() - INTERVAL '2 days', false, '{"sessions":45}'),
('CPF-555.666.777-88', 'user', 'SIM-NEW-001', 'device', 'uses', 0.15, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '54 minutes', true, '{"sim_swap":true,"carrier":"Claro"}'),
('CPF-555.666.777-88', 'user', 'IP-200.155.33.44', 'ip', 'connects_from', 0.3, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '54 minutes', true, '{"different_from_baseline":true}'),
-- Thiago - malware victim
('CPF-012.345.678-99', 'user', 'DEV-060', 'device', 'owns', 0.65, NOW() - INTERVAL '7 months', NOW() - INTERVAL '2 days', false, '{"sessions":60}'),
('CPF-012.345.678-99', 'user', 'RAT-C2-SERVER', 'entity', 'connected_to', 0.02, NOW() - INTERVAL '25 minutes', NOW() - INTERVAL '25 minutes', true, '{"malware_type":"banking_rat","c2":"91.215.85.xxx"}'),
-- Anderson - ransomware precursor
('CPF-777.888.999-00', 'user', 'DEV-140', 'device', 'owns', 0.5, NOW() - INTERVAL '2 months', NOW() - INTERVAL '2 days', false, '{"sessions":15}'),
('CPF-777.888.999-00', 'user', 'INTERNAL-HOST-001', 'entity', 'rdp_to', 0.1, NOW() - INTERVAL '40 minutes', NOW() - INTERVAL '40 minutes', true, '{"rdp_lateral_movement":true}'),
('CPF-777.888.999-00', 'user', 'INTERNAL-HOST-002', 'entity', 'rdp_to', 0.1, NOW() - INTERVAL '38 minutes', NOW() - INTERVAL '38 minutes', true, '{"rdp_lateral_movement":true}'),
('CPF-777.888.999-00', 'user', 'INTERNAL-HOST-003', 'entity', 'rdp_to', 0.08, NOW() - INTERVAL '36 minutes', NOW() - INTERVAL '36 minutes', true, '{"privilege_escalation":true}'),
('CPF-777.888.999-00', 'user', 'CRM-DATABASE', 'entity', 'data_access', 0.05, NOW() - INTERVAL '35 minutes', NOW() - INTERVAL '35 minutes', true, '{"data_volume":"2.3GB","pii_access":true}'),
-- Supply chain - API anomaly
('API-INT-001', 'entity', 'IP-52.67.88.100', 'ip', 'connects_from', 0.8, NOW() - INTERVAL '6 months', NOW() - INTERVAL '20 minutes', false, '{"region":"sa-east-1"}'),
('API-INT-001', 'entity', 'IP-198.51.100.50', 'ip', 'connects_from', 0.2, NOW() - INTERVAL '20 minutes', NOW() - INTERVAL '20 minutes', true, '{"region":"unknown","new_source":true}'),
-- Clean user connections
('CPF-234.567.890-11', 'user', 'DEV-003', 'device', 'owns', 0.92, NOW() - INTERVAL '14 months', NOW() - INTERVAL '1 hour', false, '{"sessions":380}'),
('CPF-234.567.890-11', 'user', 'IP-177.44.11.22', 'ip', 'connects_from', 0.88, NOW() - INTERVAL '14 months', NOW() - INTERVAL '1 hour', false, '{"isp":"Tim","city":"Rio de Janeiro"}'),
('CPF-456.789.012-33', 'user', 'DEV-005', 'device', 'owns', 0.82, NOW() - INTERVAL '18 months', NOW() - INTERVAL '4 hours', false, '{"sessions":520}'),
('CPF-890.123.456-77', 'user', 'DEV-040', 'device', 'owns', 0.94, NOW() - INTERVAL '15 months', NOW() - INTERVAL '3 hours', false, '{"sessions":310}'),
('CPF-111.222.333-44', 'user', 'DEV-080', 'device', 'owns', 0.96, NOW() - INTERVAL '36 months', NOW() - INTERVAL '6 hours', false, '{"sessions":890}'),
('CPF-666.777.888-99', 'user', 'DEV-130', 'device', 'owns', 0.91, NOW() - INTERVAL '30 months', NOW() - INTERVAL '2 hours', false, '{"sessions":620}'),
('CPF-666.777.888-99', 'user', 'DEV-131', 'device', 'owns', 0.88, NOW() - INTERVAL '3 months', NOW() - INTERVAL '2 hours', false, '{"sessions":85}'),
('CPF-888.999.000-11', 'user', 'DEV-150', 'device', 'owns', 0.93, NOW() - INTERVAL '13 months', NOW() - INTERVAL '5 hours', false, '{"sessions":270}'),
('CPF-334.455.667-78', 'user', 'DEV-210', 'device', 'owns', 0.91, NOW() - INTERVAL '14 months', NOW() - INTERVAL '3 hours', false, '{"sessions":340}'),
-- Vanessa - identity selling victim
('CPF-000.111.222-33', 'user', 'DEV-180', 'device', 'owns', 0.7, NOW() - INTERVAL '8 months', NOW() - INTERVAL '3 hours', false, '{"sessions":150}'),
('CPF-000.111.222-33', 'user', 'DEV-020', 'device', 'uses', 0.1, NOW() - INTERVAL '2 days', NOW() - INTERVAL '3 hours', true, '{"shared_with_mule_network":true}'),
-- Camila - identity selling suspect
('CPF-901.234.567-88', 'user', 'DEV-050', 'device', 'owns', 0.78, NOW() - INTERVAL '5 months', NOW() - INTERVAL '2 hours', false, '{"sessions":140}'),
('CPF-901.234.567-88', 'user', 'DEV-020', 'device', 'uses', 0.15, NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 hours', true, '{"behavioral_similarity_to_mule":0.87}'),
-- Rodrigo - social engineering target
('CPF-999.000.111-22', 'user', 'DEV-160', 'device', 'owns', 0.8, NOW() - INTERVAL '11 months', NOW() - INTERVAL '7 hours', false, '{"sessions":170}'),
('CPF-999.000.111-22', 'user', 'SPOOFED-CALL-001', 'entity', 'interacted_with', 0.3, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '7 hours', true, '{"spoofed_number":"+55-11-3003-XXXX","duration_min":8}'),
-- Global Imports - supply chain risk
('CNPJ-98.765.432/0001-10', 'user', 'DEV-070', 'device', 'owns', 0.75, NOW() - INTERVAL '20 months', NOW() - INTERVAL '5 hours', false, '{"sessions":400}'),
('CNPJ-98.765.432/0001-10', 'user', 'WIRE-CYPRUS-001', 'beneficiary', 'transacts_with', 0.1, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '5 hours', true, '{"first_transaction":true,"shell_company":true}'),
-- Business connections
('CNPJ-12.345.678/0001-90', 'user', 'DEV-010', 'device', 'owns', 0.9, NOW() - INTERVAL '24 months', NOW() - INTERVAL '1 hour', false, '{"sessions":650}'),
('CNPJ-11.222.333/0001-44', 'user', 'DEV-170', 'device', 'owns', 0.88, NOW() - INTERVAL '30 months', NOW() - INTERVAL '1 hour', false, '{"sessions":720}'),
-- Crypto exchange connections
('API-INT-002', 'entity', 'CRYPTO-WALLET-001', 'entity', 'processes', 0.5, NOW() - INTERVAL '4 months', NOW() - INTERVAL '30 minutes', true, '{"withdrawal_count":45}'),
('API-INT-002', 'entity', 'CRYPTO-WALLET-002', 'entity', 'processes', 0.3, NOW() - INTERVAL '2 months', NOW() - INTERVAL '30 minutes', true, '{"chainalysis_flagged":true}'),
('API-INT-002', 'entity', 'CRYPTO-WALLET-003', 'entity', 'processes', 0.2, NOW() - INTERVAL '1 day', NOW() - INTERVAL '2 minutes', true, '{"mixing_service":true}');

-- Threat Detections (25 records)
INSERT INTO financial_threat_detections (detection_id, threat_type, severity, confidence, affected_entities, attack_chain, llm_explanation, llm_classification, behavioral_evidence, graph_evidence, status, response_actions, created_at) VALUES
('DET-001', 'identity_theft', 'critical', 95, '["CPF-567.890.123-44"]', '[{"stage":"credential_harvest","detail":"Credentials obtained via dark web purchase"},{"stage":"initial_access","detail":"Login from unknown devices DEV-100, DEV-101"},{"stage":"reconnaissance","detail":"Account balance check and recipient list enumeration"},{"stage":"exfiltration","detail":"12 rapid PIX transfers to mule network accounts"}]', 'This is a textbook identity theft case. Valid credentials for Roberto Fernandes were used from two previously unseen devices simultaneously (one Linux desktop, one iOS mobile), connecting from a Russian IP address. The behavioral fingerprint is completely inconsistent with the account holder: typing speed 120 WPM vs baseline 32 WPM, bot-like mouse patterns vs organic baseline, and zero scroll depth suggesting automated navigation. The attacker performed 12 PIX transfers totaling R$45,000 within 8 minutes, all to recipients with no prior relationship. Four recipients are confirmed mule accounts linked to a synthetic identity network.', 'Identity Theft → Credential Purchase → Multi-Device Exploitation → Mule Network Exfiltration', '{"typing_speed_deviation":3.75,"mouse_pattern_similarity":0.08,"navigation_similarity":0.05,"session_duration_deviation":0.0}', '{"new_edges":5,"suspicious_edges":5,"new_devices":2,"concurrent_sessions":true,"mule_network_connection":true}', 'active', '[{"action":"block_all_transactions","status":"executed"},{"action":"freeze_account","status":"executed"},{"action":"alert_soc","status":"executed"},{"action":"notify_customer","status":"pending"}]', NOW() - INTERVAL '15 minutes'),

('DET-002', 'pix_fraud', 'critical', 92, '["CPF-345.678.901-22","CPF-678.901.234-55"]', '[{"stage":"account_compromise","detail":"Impossible travel detected from BH to Manaus"},{"stage":"device_switch","detail":"New device DEV-099 registered"},{"stage":"behavioral_change","detail":"Typing speed and click patterns deviated 2.6x from baseline"},{"stage":"transfer_attempt","detail":"R$8,500 PIX to synthetic mule account"}]', 'Pedro Augustos account shows clear signs of compromise. An impossible travel event (Belo Horizonte to Manaus in 45 minutes) was followed by a new device registration and immediate financial activity. The behavioral fingerprint shifted dramatically: typing speed jumped from 32 WPM to 85 WPM, click velocity increased 2.6x, and scroll depth dropped from 45% to 15%. The attacker attempted a R$8,500 PIX transfer to CPF-678.901.234-55, which is a confirmed synthetic identity created 18 hours ago and already flagged as a mule network member. The transfer was blocked by the real-time risk engine.', 'PIX Fraud → Account Compromise → Behavioral Anomaly → Mule Transfer Attempt', '{"impossible_travel":true,"typing_deviation":2.65,"click_velocity_deviation":2.6,"behavioral_similarity":0.15}', '{"new_device_edge":true,"suspicious_beneficiary":true,"mule_connection":true}', 'investigating', '[{"action":"block_transaction","status":"executed"},{"action":"step_up_auth","status":"executed"},{"action":"alert_soc","status":"executed"}]', NOW() - INTERVAL '30 minutes'),

('DET-003', 'mule_network', 'critical', 98, '["CPF-678.901.234-55","CPF-333.444.555-66","CPF-223.344.556-67"]', '[{"stage":"account_creation","detail":"3 synthetic accounts created within 24h"},{"stage":"device_sharing","detail":"All accounts share device DEV-020 and IP range"},{"stage":"fund_receipt","detail":"R$67,000 received from 8 compromised accounts"},{"stage":"crypto_conversion","detail":"95%+ forwarded to cryptocurrency mixing services"}]', 'A coordinated mule network has been identified involving three synthetic identities. Lucas Gabriel (CPF-678), Diego Henrique (CPF-333), and Renata Dias (CPF-223) share device fingerprint DEV-020 and connect from the same IP range. All accounts were created within 24 hours, have no historical behavioral baseline, and immediately began receiving high-value PIX transfers from compromised accounts. Within minutes of receiving funds, 95%+ is forwarded to cryptocurrency wallets linked to mixing services flagged by Chainalysis. This is a professionally operated money laundering cell with automated fund dispersal capabilities.', 'Mule Network → Synthetic Identities → Shared Infrastructure → Crypto Laundering', '{"no_baseline":true,"immediate_financial_activity":true,"forwarding_ratio":0.95,"automation_detected":true}', '{"shared_device":"DEV-020","shared_ip_range":true,"cluster_size":3,"crypto_connections":3}', 'active', '[{"action":"freeze_all_accounts","status":"executed"},{"action":"block_all_transactions","status":"executed"},{"action":"alert_soc","status":"executed"},{"action":"report_to_bacen","status":"pending"},{"action":"report_to_coaf","status":"pending"}]', NOW() - INTERVAL '10 minutes'),

('DET-004', 'phishing', 'high', 88, '["CPF-789.012.345-66"]', '[{"stage":"delivery","detail":"SMS phishing link sent to victim"},{"stage":"credential_harvest","detail":"Victim entered credentials on spoofed banking portal banco-seguro-pix.com"},{"stage":"account_access","detail":"Attacker accessed account from new device"},{"stage":"account_modification","detail":"PIX keys changed, new recipients added"},{"stage":"transfer_attempt","detail":"R$5,000 PIX to synthetic mule blocked"}]', 'Juliana Mendes fell victim to a sophisticated PIX phishing campaign. She received an SMS with a link to banco-seguro-pix.com, a spoofed version of the legitimate banking portal. After entering her credentials, the attacker waited approximately 4 hours before accessing the account from a new Samsung S24 Ultra device (DEV-031). The attacker then changed PIX keys and added new recipients before attempting a R$5,000 transfer to a synthetic mule account (CPF-333). The transfer was blocked by the behavioral anomaly detection system, which flagged the new device, altered PIX keys, and the suspicious destination.', 'Phishing → SMS Delivery → Credential Harvest → Delayed Access → Mule Transfer', '{"new_device_post_phishing":true,"pix_key_change":true,"recipient_additions":3,"transfer_to_mule":true}', '{"phishing_url_interaction":true,"new_device_edge":true,"mule_destination":true}', 'investigating', '[{"action":"block_transaction","status":"executed"},{"action":"reset_credentials","status":"executed"},{"action":"notify_customer","status":"executed"}]', NOW() - INTERVAL '45 minutes'),

('DET-005', 'banking_malware', 'critical', 94, '["CPF-012.345.678-99"]', '[{"stage":"infection","detail":"RAT installed via malicious APK sideload"},{"stage":"persistence","detail":"Overlay service registered for banking app"},{"stage":"session_hijack","detail":"WebSocket token replayed from attacker IP"},{"stage":"overlay_attack","detail":"Invisible overlay modified PIX confirmation screen"},{"stage":"exfiltration","detail":"Modified amounts and recipients in transit"}]', 'Thiago Nascimentos device has been infected with a banking RAT (Remote Access Trojan). The malware registered an overlay service that intercepts the banking apps PIX confirmation screen. When Thiago attempted a R$35 PIX transfer, the overlay silently modified both the amount to R$3,500 and the recipient to a mule account. Additionally, the RAT replayed the WebSocket session token from a different IP address, enabling parallel session hijacking. The session integrity check detected the token replay, and the amount modification was caught by the transaction validation engine. The behavioral deviation in click patterns and the scripted mouse movement confirmed automated interaction overlaying the legitimate session.', 'Banking Malware → RAT Infection → Overlay Injection → Amount/Recipient Modification', '{"overlay_detected":true,"session_token_replay":true,"amount_modification":true,"scripted_interaction":true}', '{"c2_connection":"91.215.85.xxx","rat_type":"banking_overlay","session_integrity_failed":true}', 'active', '[{"action":"block_all_transactions","status":"executed"},{"action":"kill_session","status":"executed"},{"action":"alert_soc","status":"executed"},{"action":"device_quarantine","status":"pending"}]', NOW() - INTERVAL '25 minutes'),

('DET-006', 'account_takeover', 'high', 91, '["CPF-555.666.777-88"]', '[{"stage":"sim_swap","detail":"Phone number ported to new SIM without authorization"},{"stage":"password_reset","detail":"Password changed via SMS recovery flow"},{"stage":"device_registration","detail":"New device registered post-SIM swap"},{"stage":"rapid_transfers","detail":"5 PIX transfers totaling R$8,500 in 12 minutes"}]', 'Marcos Vinicius account was taken over through a SIM swap attack. His phone number was ported to a new SIM card, which was then used to initiate a password recovery flow. After gaining access, the attacker registered a new device and executed 5 rapid PIX transfers totaling R$8,500 to previously unknown recipients within 12 minutes. The behavioral anomaly is stark: typing speed jumped to 70 WPM from a 35 WPM baseline, and the session navigation pattern was entirely focused on PIX transfers without the usual dashboard browsing. All transfers were blocked by the real-time risk engine.', 'Account Takeover → SIM Swap → Password Reset → Rapid PIX Spray', '{"sim_swap_detected":true,"rapid_transfers":5,"total_amount":8500,"behavioral_deviation":5.8}', '{"new_sim_edge":true,"new_ip":true,"unknown_recipients":4,"mule_destination":1}', 'investigating', '[{"action":"block_all_transfers","status":"executed"},{"action":"freeze_account","status":"executed"},{"action":"sim_swap_reversal","status":"pending"}]', NOW() - INTERVAL '1 hour'),

('DET-007', 'ransomware_precursor', 'high', 86, '["CPF-777.888.999-00"]', '[{"stage":"initial_compromise","detail":"Account credentials used from impossible travel location"},{"stage":"lateral_movement","detail":"RDP connections to 8 internal hosts"},{"stage":"privilege_escalation","detail":"PrintNightmare exploit attempted"},{"stage":"data_access","detail":"2.3GB PII exported from CRM"},{"stage":"financial_staging","detail":"PIX transfer attempt to mule account"}]', 'Anderson Luiz account is being used as a beachhead for what appears to be a ransomware precursor attack. After initial access from an anomalous location, the attacker used RDP to connect to 8 internal hosts, attempted privilege escalation via the PrintNightmare vulnerability, and exported 2.3GB of customer PII from the CRM database. The financial dimension emerged when the attacker attempted a PIX transfer to a known mule account, possibly as a test or to fund operational infrastructure. The lateral movement pattern and data exfiltration volume strongly suggest ransomware deployment is imminent.', 'Ransomware Precursor → Lateral Movement → Privilege Escalation → Data Exfiltration → Financial Staging', '{"lateral_movement_hosts":8,"data_exfil_gb":2.3,"privilege_escalation":true,"financial_activity":true}', '{"rdp_connections":8,"crm_access":true,"mule_transfer_attempt":true}', 'active', '[{"action":"isolate_workstation","status":"executed"},{"action":"block_rdp","status":"executed"},{"action":"alert_soc_critical","status":"executed"},{"action":"incident_response_team","status":"pending"}]', NOW() - INTERVAL '40 minutes'),

('DET-008', 'supply_chain', 'medium', 75, '["API-INT-001"]', '[{"stage":"anomaly_detection","detail":"API request volume 3.2x normal"},{"stage":"endpoint_deviation","detail":"15% of requests targeting /admin/config"},{"stage":"new_source_ip","detail":"Requests from unrecognized IP range"}]', 'The PaymentGateway API v3 integration is exhibiting anomalous behavior. Request volume has spiked to 3.2x the normal rate, with 15% of requests targeting the /admin/config endpoint which is not part of the typical request pattern. Additionally, a portion of requests are originating from an IP address not previously associated with this integration. This could indicate the API credentials have been compromised, the integrations infrastructure has been breached, or a malicious insider is abusing the API. The anomaly is significant enough to warrant investigation but has not yet resulted in confirmed financial impact.', 'Supply Chain Anomaly → API Credential Compromise or Infrastructure Breach', '{"volume_deviation":3.2,"endpoint_deviation":0.15,"new_ip_source":true}', '{"new_ip_edge":true,"unusual_endpoints":true}', 'investigating', '[{"action":"rate_limit_api","status":"executed"},{"action":"block_admin_endpoints","status":"executed"},{"action":"notify_integration_owner","status":"pending"}]', NOW() - INTERVAL '20 minutes'),

('DET-009', 'identity_selling', 'high', 82, '["CPF-000.111.222-33","CPF-901.234.567-88"]', '[{"stage":"dark_web_listing","detail":"Account credentials found on marketplace"},{"stage":"behavioral_shift","detail":"3 distinct behavioral fingerprints in 48h"},{"stage":"shared_infrastructure","detail":"Both accounts used device DEV-020 linked to mule network"}]', 'Two accounts show signs of identity selling - a growing fraud trend where legitimate account holders sell access to their banking credentials. Vanessas account (CPF-000) credentials were found on a dark web marketplace, and over the past 48 hours, three distinct behavioral fingerprints have been observed using the account. Camilas account (CPF-901) shares device DEV-020 with known mule network members and has an 87% behavioral similarity to the synthetic identity CPF-678. Both accounts appear to be willingly providing access to the mule operation, though Vanessa may also be a victim of credential theft rather than a willing participant.', 'Identity Selling → Dark Web Credential Trading → Mule Network Access', '{"distinct_fingerprints":3,"behavioral_similarity_to_mule":0.87,"dark_web_listing":true}', '{"shared_device_with_mule":true,"behavioral_cluster_match":true}', 'investigating', '[{"action":"enhanced_monitoring","status":"executed"},{"action":"step_up_all_transactions","status":"executed"}]', NOW() - INTERVAL '3 hours'),

('DET-010', 'deepfake', 'medium', 71, '["CPF-222.333.444-55"]', '[{"stage":"video_submission","detail":"Liveness verification video submitted"},{"stage":"analysis","detail":"Facial landmark inconsistency detected"},{"stage":"rejection","detail":"Verification rejected with 0.73 inconsistency score"}]', 'A deepfake attempt was detected during Larissa Fernandas video verification process. The submitted video showed facial landmark inconsistencies with a score of 0.73 (threshold: 0.5), suggesting AI-generated facial manipulation. The liveness detection system flagged unnatural micro-expressions, inconsistent lighting on facial features, and subtle temporal artifacts in the video stream. This may be an attempt to bypass biometric verification for an unauthorized account change or to register a fraudulent device.', 'Deepfake Attempt → Biometric Bypass → Account Modification', '{"liveness_score":0.27,"landmark_inconsistency":0.73,"micro_expression_anomaly":true}', '{}', 'resolved', '[{"action":"reject_verification","status":"executed"},{"action":"flag_account","status":"executed"},{"action":"require_in_person_verification","status":"executed"}]', NOW() - INTERVAL '8 hours'),

('DET-011', 'social_engineering', 'medium', 78, '["CPF-999.000.111-22"]', '[{"stage":"spoofed_call","detail":"Incoming call from spoofed bank number"},{"stage":"manipulation","detail":"8-minute call preceded unusual transfer"},{"stage":"transfer_attempt","detail":"R$3,800 PIX to unknown recipient"}]', 'Rodrigo received a call from what appeared to be the banks official number (+55-11-3003-XXXX), but the number was spoofed. During an 8-minute conversation, the caller apparently convinced Rodrigo to make an urgent PIX transfer of R$3,800 to an unknown recipient. The timing correlation between the spoofed call and the unusual transfer, combined with the new recipient and above-average amount, triggered the social engineering detection model. The transaction was delayed for additional verification.', 'Social Engineering → Phone Spoofing → Manipulation → Urgent Transfer', '{"call_correlation":true,"new_recipient":true,"amount_above_avg":true,"urgency_indicators":true}', '{"spoofed_call_edge":true,"new_beneficiary":true}', 'investigating', '[{"action":"delay_transaction","status":"executed"},{"action":"callback_verification","status":"pending"}]', NOW() - INTERVAL '7 hours'),

('DET-012', 'pix_fraud', 'high', 89, '["CPF-678.901.234-55","CRYPTO-WALLET-001","CRYPTO-WALLET-002"]', '[{"stage":"fund_aggregation","detail":"R$28,000 received from 4 compromised accounts"},{"stage":"layering","detail":"Funds split across multiple crypto wallets"},{"stage":"conversion","detail":"BRL to BTC/USDT conversion"},{"stage":"mixing","detail":"Funds sent to Tornado Cash-linked mixer"}]', 'The synthetic mule account CPF-678 is acting as a central laundering node. It received R$28,000 from four compromised accounts within a 2-hour window, then rapidly converted 95% of the funds into cryptocurrency through multiple exchange wallets. The funds were further layered through a Tornado Cash-linked mixing service, making tracing extremely difficult. This is a well-organized laundering operation with automated fund dispersal capabilities.', 'PIX Laundering → Fund Aggregation → Crypto Conversion → Mixing Service', '{"fund_sources":4,"total_aggregated":28000,"forwarding_ratio":0.95,"crypto_mixing":true}', '{"inbound_edges":4,"crypto_wallet_edges":2,"mixer_connection":true}', 'active', '[{"action":"freeze_account","status":"executed"},{"action":"freeze_crypto_wallets","status":"pending"},{"action":"report_suspicious_activity","status":"executed"}]', NOW() - INTERVAL '10 minutes'),

('DET-013', 'supply_chain', 'medium', 70, '["API-INT-002"]', '[{"stage":"anomaly","detail":"45 withdrawals in 1h to flagged wallets"},{"stage":"pattern","detail":"Withdrawal pattern suggests automated fraud farm"}]', 'The CryptoExchange Bridge API is showing an unusual withdrawal pattern: 45 withdrawals within 1 hour directed to wallets flagged by Chainalysis. This pattern is consistent with a fraud farm operation using the exchange as a laundering conduit. The API itself may not be compromised, but it is being exploited by accounts within the exchange to process illicit funds.', 'Supply Chain Exploitation → Fraud Farm → Flagged Wallet Withdrawals', '{"withdrawal_spike":true,"flagged_destinations":45}', '{"flagged_wallet_edges":2}', 'investigating', '[{"action":"rate_limit_withdrawals","status":"executed"},{"action":"flag_accounts","status":"pending"}]', NOW() - INTERVAL '30 minutes'),

('DET-014', 'pix_fraud', 'high', 87, '["CNPJ-55.666.777/0001-88"]', '[{"stage":"qr_code_abuse","detail":"12,000 QR code generations in 10min"},{"stage":"pattern","detail":"QR codes linked to micro-transaction fraud"}]', 'FinConnect Payments API generated 12,000 QR codes in 10 minutes (baseline: 800/min). Investigation reveals the QR codes are being used for micro-transaction fraud, where small amounts are collected from hundreds of victims through deceptive QR code placements. This is a large-scale PIX QR code fraud operation exploiting the payment facilitators infrastructure.', 'PIX QR Fraud → Mass QR Generation → Micro-Transaction Collection', '{"qr_generation_spike":15,"micro_transactions":true}', '{"qr_code_distribution":true}', 'investigating', '[{"action":"throttle_qr_generation","status":"executed"},{"action":"review_merchant_accounts","status":"pending"}]', NOW() - INTERVAL '30 minutes'),

('DET-015', 'identity_theft', 'high', 85, '["CPF-345.678.901-22"]', '[{"stage":"behavioral_anomaly","detail":"Complete behavioral fingerprint mismatch post-impossible-travel"}]', 'Secondary analysis of Pedro Augustos account confirms identity theft. The behavioral fingerprint after the impossible travel event shows 0% correlation with historical patterns. The attacker is likely using purchased credentials with no knowledge of the account holders normal behavior patterns.', 'Identity Theft → Credential Purchase → Zero Behavioral Correlation', '{"fingerprint_correlation":0.0,"impossible_travel":true}', '{"new_device":true,"new_ip":true}', 'investigating', '[{"action":"account_locked","status":"executed"}]', NOW() - INTERVAL '28 minutes');

-- Response Decisions (40 records)
INSERT INTO financial_response_decisions (decision_id, trigger_type, trigger_id, entity_id, risk_score, action, action_details, reasoning, outcome, responded_by, response_time_ms, created_at) VALUES
('RSP-001', 'transaction', 'TX-PIX-001', 'CPF-123.456.789-00', 8, 'allow', '{"auto_approved":true}', 'Transaction within behavioral baseline; known recipient; normal amount and timing', 'executed', 'system', 12, NOW() - INTERVAL '2 hours'),
('RSP-002', 'transaction', 'TX-PIX-002', 'CPF-345.678.901-22', 92, 'block', '{"blocked_amount":8500,"frozen":true}', 'Critical risk: Compromised account attempting transfer to synthetic mule; impossible travel + behavioral mismatch', 'executed', 'system', 8, NOW() - INTERVAL '30 minutes'),
('RSP-003', 'transaction', 'TX-PIX-003', 'CPF-567.890.123-44', 98, 'block', '{"blocked_amount":12000,"account_frozen":true}', 'Identity theft confirmed: Bot-driven transfers from fully compromised account to mule network', 'executed', 'system', 5, NOW() - INTERVAL '15 minutes'),
('RSP-004', 'transaction', 'TX-PIX-004', 'CPF-456.789.012-33', 35, 'step_up_auth', '{"method":"biometric","timeout_sec":120}', 'Elevated amount with recent recipient changes; biometric step-up required', 'executed', 'system', 15, NOW() - INTERVAL '4 hours'),
('RSP-005', 'transaction', 'TX-PIX-005', 'CPF-789.012.345-66', 88, 'block', '{"blocked_amount":5000}', 'Phishing-compromised account; transfer to synthetic mule account blocked', 'executed', 'system', 7, NOW() - INTERVAL '45 minutes'),
('RSP-006', 'transaction', 'TX-TED-001', 'CNPJ-98.765.432/0001-10', 82, 'delay', '{"delay_hours":24,"compliance_review":true}', 'Large wire to new entity in high-risk jurisdiction; held for compliance review', 'executed', 'system', 18, NOW() - INTERVAL '5 hours'),
('RSP-007', 'transaction', 'TX-PIX-007', 'CPF-012.345.678-99', 95, 'block', '{"malware_detected":true,"session_killed":true}', 'Banking malware overlay attack detected; transaction amount was modified in transit', 'executed', 'system', 3, NOW() - INTERVAL '25 minutes'),
('RSP-008', 'transaction', 'TX-PIX-009', 'CPF-333.444.555-66', 97, 'block', '{"blocked_amount":14500,"account_frozen":true}', 'Synthetic identity attempting to forward stolen funds to cryptocurrency mixer', 'executed', 'system', 4, NOW() - INTERVAL '5 minutes'),
('RSP-009', 'transaction', 'TX-PIX-010', 'CPF-555.666.777-88', 90, 'block', '{"blocked_amount":2800,"sim_swap_flag":true}', 'SIM swap attack: Account takeover with rapid transfer to mule network', 'executed', 'system', 6, NOW() - INTERVAL '1 hour'),
('RSP-010', 'detection', 'DET-001', 'CPF-567.890.123-44', 98, 'freeze_account', '{"freeze_type":"full","duration":"indefinite"}', 'Full account freeze: Active identity theft with bot-driven transfers to mule network', 'executed', 'system', 2, NOW() - INTERVAL '15 minutes'),
('RSP-011', 'detection', 'DET-003', 'CPF-678.901.234-55', 99, 'freeze_account', '{"freeze_type":"full","reported_to":"BACEN,COAF"}', 'Mule network central node: Account frozen and reported to regulators', 'executed', 'system', 3, NOW() - INTERVAL '10 minutes'),
('RSP-012', 'detection', 'DET-003', 'CPF-333.444.555-66', 99, 'freeze_account', '{"freeze_type":"full","reported_to":"BACEN,COAF"}', 'Mule network member: Synthetic identity frozen and reported', 'executed', 'system', 3, NOW() - INTERVAL '10 minutes'),
('RSP-013', 'detection', 'DET-003', 'CPF-223.344.556-67', 99, 'freeze_account', '{"freeze_type":"full","reported_to":"BACEN,COAF"}', 'Mule network member: Tor-based synthetic identity frozen and reported', 'executed', 'system', 3, NOW() - INTERVAL '10 minutes'),
('RSP-014', 'detection', 'DET-005', 'CPF-012.345.678-99', 95, 'alert_soc', '{"priority":"P1","assigned_to":"SOC-Team-Alpha","malware_type":"banking_rat"}', 'Banking RAT detected: P1 alert raised for SOC team with full malware analysis', 'executed', 'system', 5, NOW() - INTERVAL '25 minutes'),
('RSP-015', 'detection', 'DET-007', 'CPF-777.888.999-00', 92, 'alert_soc', '{"priority":"P1","incident_type":"ransomware_precursor","ir_team_notified":true}', 'Ransomware precursor detected: IR team notified for immediate containment', 'executed', 'system', 4, NOW() - INTERVAL '40 minutes'),
('RSP-016', 'session', 'SESSION-PEDRO', 'CPF-345.678.901-22', 88, 'step_up_auth', '{"method":"video_verification","reason":"impossible_travel"}', 'Impossible travel detected; video verification required to confirm identity', 'executed', 'system', 10, NOW() - INTERVAL '32 minutes'),
('RSP-017', 'transaction', 'TX-PIX-014', 'CPF-999.000.111-22', 72, 'delay', '{"delay_min":30,"callback_initiated":true}', 'Social engineering suspected; transaction delayed and customer callback initiated', 'executed', 'system', 12, NOW() - INTERVAL '7 hours'),
('RSP-018', 'detection', 'DET-010', 'CPF-222.333.444-55', 71, 'step_up_auth', '{"method":"in_person_verification","branch_required":true}', 'Deepfake detected: In-person branch verification required for any account changes', 'executed', 'system', 8, NOW() - INTERVAL '8 hours'),
('RSP-019', 'transaction', 'TX-PIX-015', 'CPF-000.111.222-33', 78, 'block', '{"blocked_amount":2200,"enhanced_monitoring":true}', 'Identity selling suspected; dark web credentials confirmed; transfer to mule blocked', 'executed', 'system', 6, NOW() - INTERVAL '3 hours'),
('RSP-020', 'transaction', 'TX-PIX-018', 'CPF-223.344.556-67', 99, 'block', '{"blocked_amount":18000,"account_frozen":true}', 'Automated synthetic identity fund dispersal blocked; Tor origin confirmed', 'executed', 'system', 2, NOW() - INTERVAL '2 minutes'),
('RSP-021', 'rule', 'RULE-VELOCITY', 'CPF-567.890.123-44', 96, 'block', '{"rule":"max_5_transfers_per_hour","actual":12}', 'Velocity rule triggered: 12 transfers in 8 minutes exceeds maximum of 5/hour', 'executed', 'system', 1, NOW() - INTERVAL '14 minutes'),
('RSP-022', 'transaction', 'TX-CRYPTO-001', 'CPF-678.901.234-55', 99, 'block', '{"blocked_amount":25000,"crypto_wallet_flagged":true}', 'Mule account crypto conversion blocked; Tornado Cash-linked wallet', 'executed', 'system', 3, NOW() - INTERVAL '10 minutes'),
('RSP-023', 'detection', 'DET-004', 'CPF-789.012.345-66', 88, 'step_up_auth', '{"method":"biometric+otp","credential_reset":true}', 'Post-phishing account recovery: Forced credential reset with biometric verification', 'executed', 'analyst:Maria.SOC', 45000, NOW() - INTERVAL '44 minutes'),
('RSP-024', 'transaction', 'TX-PIX-006', 'CPF-890.123.456-77', 5, 'allow', '{"auto_approved":true}', 'Low risk: Known recipient, normal amount, verified device and location', 'executed', 'system', 8, NOW() - INTERVAL '3 hours'),
('RSP-025', 'transaction', 'TX-CARD-001', 'CPF-111.222.333-44', 3, 'allow', '{"auto_approved":true,"chip_present":true}', 'Chip-present card transaction at known merchant', 'executed', 'system', 5, NOW() - INTERVAL '6 hours'),
('RSP-026', 'transaction', 'TX-PIX-011', 'CPF-666.777.888-99', 12, 'allow', '{"auto_approved":true}', 'Established business relationship; normal payment pattern', 'executed', 'system', 9, NOW() - INTERVAL '2 hours'),
('RSP-027', 'transaction', 'TX-PIX-020', 'CPF-567.890.123-44', 96, 'block', '{"blocked_amount":9500,"sequence":1}', 'Identity theft spray attack: Transfer 1 of 3 blocked', 'executed', 'system', 2, NOW() - INTERVAL '14 minutes'),
('RSP-028', 'transaction', 'TX-PIX-021', 'CPF-567.890.123-44', 96, 'block', '{"blocked_amount":7800,"sequence":2}', 'Identity theft spray attack: Transfer 2 of 3 blocked', 'executed', 'system', 2, NOW() - INTERVAL '13 minutes'),
('RSP-029', 'transaction', 'TX-PIX-022', 'CPF-567.890.123-44', 96, 'block', '{"blocked_amount":6200,"sequence":3}', 'Identity theft spray attack: Transfer 3 of 3 blocked', 'executed', 'system', 2, NOW() - INTERVAL '12 minutes'),
('RSP-030', 'detection', 'DET-008', 'API-INT-001', 75, 'alert_soc', '{"priority":"P2","rate_limited":true}', 'Supply chain anomaly: API rate limited and SOC alerted for investigation', 'executed', 'system', 15, NOW() - INTERVAL '20 minutes'),
('RSP-031', 'transaction', 'TX-PIX-026', 'CPF-555.666.777-88', 87, 'block', '{"blocked_amount":1800}', 'SIM swap spray: Transfer 1 blocked', 'executed', 'system', 4, NOW() - INTERVAL '58 minutes'),
('RSP-032', 'transaction', 'TX-PIX-027', 'CPF-555.666.777-88', 88, 'block', '{"blocked_amount":2100}', 'SIM swap spray: Transfer 2 blocked', 'executed', 'system', 4, NOW() - INTERVAL '56 minutes'),
('RSP-033', 'transaction', 'TX-PIX-028', 'CPF-555.666.777-88', 86, 'block', '{"blocked_amount":1700}', 'SIM swap spray: Transfer 3 blocked', 'executed', 'system', 4, NOW() - INTERVAL '55 minutes'),
('RSP-034', 'transaction', 'TX-PIX-029', 'CPF-555.666.777-88', 91, 'block', '{"blocked_amount":900}', 'SIM swap to confirmed mule: Transfer 4 blocked', 'executed', 'system', 3, NOW() - INTERVAL '54 minutes'),
('RSP-035', 'detection', 'DET-006', 'CPF-555.666.777-88', 91, 'freeze_account', '{"freeze_type":"full","sim_swap_reversal":"initiated"}', 'Account frozen post-SIM swap; carrier contacted for SIM reversal', 'executed', 'analyst:Carlos.SOC', 120000, NOW() - INTERVAL '50 minutes'),
('RSP-036', 'transaction', 'TX-PIX-034', 'CPF-012.345.678-99', 94, 'block', '{"malware_overlay":true,"original_amount":35}', 'RAT overlay modified amount from R$35 to R$4,800; original recipient also changed', 'executed', 'system', 3, NOW() - INTERVAL '24 minutes'),
('RSP-037', 'transaction', 'TX-PIX-035', 'CPF-223.344.556-67', 99, 'block', '{"automated_dispersal":true}', 'Automated fund dispersal from synthetic identity via Tor', 'executed', 'system', 1, NOW() - INTERVAL '1 minute'),
('RSP-038', 'detection', 'DET-009', 'CPF-000.111.222-33', 82, 'step_up_auth', '{"method":"video_call","mandatory":true}', 'Identity selling suspected: Mandatory video call verification for all transactions', 'executed', 'system', 10, NOW() - INTERVAL '3 hours'),
('RSP-039', 'detection', 'DET-009', 'CPF-901.234.567-88', 78, 'step_up_auth', '{"method":"biometric","enhanced_monitoring":true}', 'Potential identity selling: Enhanced monitoring activated with biometric checks', 'executed', 'system', 10, NOW() - INTERVAL '2 hours'),
('RSP-040', 'detection', 'DET-014', 'CNPJ-55.666.777/0001-88', 85, 'alert_soc', '{"priority":"P2","qr_throttle":true,"merchant_review":true}', 'QR code fraud farm: Generation throttled; merchant accounts under review', 'executed', 'system', 12, NOW() - INTERVAL '30 minutes');

-- Threat Simulations (8 Monte Carlo simulations)
INSERT INTO financial_threat_simulations (simulation_id, scenario_name, scenario_type, parameters, results, attack_paths, detection_gaps, suggested_rules, confidence_interval, iterations, status, created_at) VALUES
('SIM-001', 'PIX Mule Network Expansion', 'mule_network', '{"initial_mules":3,"growth_rate":0.4,"compromised_accounts":10,"avg_transfer":5000,"simulation_days":30}', '{"total_laundered":1850000,"detection_rate":0.87,"avg_time_to_detect_hours":2.4,"false_positive_rate":0.03,"accounts_frozen":28,"crypto_converted":0.65}', '[{"path":"compromise→mule_creation→fund_transfer→crypto_conversion→mixing","probability":0.45,"avg_amount":12000},{"path":"phishing→credential_harvest→ato→mule_transfer","probability":0.3,"avg_amount":8000},{"path":"sim_swap→ato→spray_transfer→mule_aggregation","probability":0.25,"avg_amount":6000}]', '[{"gap":"Detection delay for micro-transactions under R$200","impact":"high","description":"Current thresholds miss micro-layering through 50+ small transfers"},{"gap":"Cross-institution mule detection","impact":"medium","description":"Mule accounts at other institutions are invisible to our graph"}]', '[{"rule":"Micro-transaction velocity alert: >20 transactions <R$200 in 1h","confidence":0.82},{"rule":"Shared device fingerprint across >2 new accounts in 24h","confidence":0.91}]', 0.95, 10000, 'completed', NOW() - INTERVAL '2 hours'),

('SIM-002', 'Coordinated Phishing Campaign', 'pix_fraud', '{"campaign_size":5000,"click_rate":0.08,"credential_harvest_rate":0.6,"ato_success_rate":0.4,"avg_steal_amount":3500}', '{"total_attempted_theft":560000,"total_prevented":487200,"prevention_rate":0.87,"victims_compromised":160,"avg_response_time_sec":45,"false_negatives":21}', '[{"path":"sms_phishing→spoofed_portal→credential_harvest→delayed_ato→pix_transfer","probability":0.55,"avg_delay_hours":4},{"path":"email_phishing→malicious_link→session_hijack→immediate_transfer","probability":0.3,"avg_delay_hours":0.5},{"path":"voice_phishing→social_engineering→guided_transfer","probability":0.15,"avg_amount":5000}]', '[{"gap":"SMS phishing link detection latency","impact":"high","description":"Average 6h before phishing URLs are blocklisted; 40% of clicks occur in first 2h"},{"gap":"Voice phishing correlation","impact":"medium","description":"No automated correlation between incoming calls and subsequent unusual transfers"}]', '[{"rule":"Post-credential-change transfer delay: 24h cooling period for new recipients after password/PIX key change","confidence":0.88},{"rule":"Call-transfer correlation: Flag transfers within 30min of calls from high-risk number patterns","confidence":0.75}]', 0.95, 10000, 'completed', NOW() - INTERVAL '4 hours'),

('SIM-003', 'Banking Malware Outbreak', 'banking_malware', '{"infection_vector":"sideloaded_apk","target_devices":1000,"infection_rate":0.12,"overlay_success_rate":0.7,"avg_modified_amount":3000}', '{"total_attempted_theft":252000,"total_prevented":226800,"prevention_rate":0.9,"devices_infected":120,"overlays_detected":84,"avg_detection_time_sec":15}', '[{"path":"malicious_apk→rat_install→overlay_register→pix_intercept→amount_modify","probability":0.6},{"path":"drive_by_download→rat_install→session_clone→parallel_session","probability":0.25},{"path":"supply_chain_sdk→embedded_rat→delayed_activation→mass_overlay","probability":0.15}]', '[{"gap":"Pre-infection detection","impact":"high","description":"No visibility into device health before banking app launch; infections detected only at transaction time"},{"gap":"SDK supply chain monitoring","impact":"critical","description":"Third-party SDKs in mobile app not monitored for embedded RATs"}]', '[{"rule":"Session integrity hash: Real-time hash comparison of client-side UI state vs server expectations","confidence":0.92},{"rule":"Device attestation: Require SafetyNet/Play Integrity before high-value transactions","confidence":0.85}]', 0.95, 10000, 'completed', NOW() - INTERVAL '6 hours'),

('SIM-004', 'Synthetic Identity Factory', 'identity_theft', '{"synthetic_accounts_created":50,"verification_bypass_rate":0.3,"avg_account_lifetime_days":5,"avg_laundered_per_account":15000}', '{"total_laundered":225000,"detection_rate":0.82,"avg_detection_time_hours":8,"accounts_caught_pre_transaction":9,"accounts_caught_during_transaction":32,"accounts_undetected":9}', '[{"path":"stolen_cpf→synthetic_account→immediate_pix_activity→crypto_exit","probability":0.5},{"path":"fabricated_identity→slow_build→legitimate_transactions→sudden_pivot→laundering","probability":0.3},{"path":"identity_farm→bulk_creation→distributed_micro_laundering","probability":0.2}]', '[{"gap":"Onboarding velocity detection","impact":"high","description":"Accounts completing full onboarding in <60 seconds not flagged"},{"gap":"CPF cross-reference latency","impact":"medium","description":"Receita Federal validation takes 4-6h; account is active before validation completes"}]', '[{"rule":"Onboarding speed threshold: Flag accounts completing registration in <2 minutes","confidence":0.89},{"rule":"First-transaction behavioral baseline: Require 72h activity before enabling transfers >R$500","confidence":0.78}]', 0.95, 10000, 'completed', NOW() - INTERVAL '8 hours'),

('SIM-005', 'Ransomware Financial Impact', 'ransomware', '{"entry_points":5,"lateral_movement_speed":"fast","encryption_targets":["crm","financial_db","backup"],"ransom_demand_btc":15,"financial_theft_parallel":true}', '{"estimated_downtime_hours":72,"estimated_financial_loss":4500000,"data_at_risk_gb":450,"accounts_potentially_exposed":125000,"lateral_movement_detected":true,"avg_detection_time_min":18}', '[{"path":"phished_employee→rdp_pivot→domain_admin→mass_encryption","probability":0.4},{"path":"vpn_exploit→foothold→mimikatz→lateral→encryption","probability":0.35},{"path":"supply_chain_compromise→trusted_access→immediate_encryption","probability":0.25}]', '[{"gap":"RDP lateral movement correlation with financial accounts","impact":"critical","description":"No automated link between network lateral movement and financial account compromise"},{"gap":"Backup integrity monitoring","impact":"high","description":"Backup encryption/deletion not correlated with financial system alerts"}]', '[{"rule":"RDP-to-financial correlation: Alert when accounts involved in RDP lateral movement attempt financial transactions","confidence":0.93},{"rule":"Data exfiltration threshold: Block all transactions when >500MB exported from financial databases","confidence":0.88}]', 0.95, 10000, 'completed', NOW() - INTERVAL '12 hours'),

('SIM-006', 'Supply Chain API Compromise', 'supply_chain', '{"compromised_apis":2,"attack_duration_days":14,"data_exfiltration":true,"transaction_manipulation":true}', '{"transactions_manipulated":340,"total_financial_impact":890000,"detection_time_days":3,"false_transactions_created":85,"api_keys_rotated":6}', '[{"path":"api_key_theft→gradual_volume_increase→transaction_injection","probability":0.45},{"path":"sdk_compromise→embedded_exfiltration→slow_drain","probability":0.35},{"path":"insider_threat→api_abuse→bulk_manipulation","probability":0.2}]', '[{"gap":"Gradual volume increase detection","impact":"high","description":"Slow 10% daily volume increases go undetected for up to 7 days"},{"gap":"Transaction integrity verification","impact":"critical","description":"No end-to-end hash verification for API-initiated transactions"}]', '[{"rule":"API behavioral drift: Alert on >15% deviation from 7-day rolling average","confidence":0.84},{"rule":"Transaction integrity hash: Require cryptographic proof for all API-initiated transfers","confidence":0.95}]', 0.95, 10000, 'completed', NOW() - INTERVAL '1 day'),

('SIM-007', 'Mass SIM Swap Campaign', 'account_takeover', '{"targets":200,"sim_swap_success_rate":0.35,"avg_time_to_drain_min":15,"avg_amount_per_victim":5000}', '{"total_attempted_theft":350000,"total_prevented":301000,"prevention_rate":0.86,"successful_drains":28,"avg_detection_time_min":8,"carrier_notification_time_min":45}', '[{"path":"social_engineering_carrier→sim_port→password_reset→rapid_drain","probability":0.6},{"path":"insider_at_carrier→bulk_sim_swap→coordinated_drain","probability":0.25},{"path":"ss7_exploit→sms_intercept→otp_capture→ato","probability":0.15}]', '[{"gap":"Carrier notification delay","impact":"critical","description":"Average 45min before carrier confirms SIM swap; most damage occurs in first 15min"},{"gap":"SMS-based 2FA dependency","impact":"high","description":"35% of accounts still rely solely on SMS OTP for 2FA"}]', '[{"rule":"SIM change + password reset correlation: Immediate account lock when both events occur within 1h","confidence":0.94},{"rule":"Migrate to app-based 2FA: Enforce TOTP for accounts >R$10,000 balance","confidence":0.88}]', 0.95, 10000, 'completed', NOW() - INTERVAL '18 hours'),

('SIM-008', 'Deepfake Biometric Bypass', 'identity_theft', '{"deepfake_quality":"high","target_verifications":100,"bypass_rate":0.15,"post_bypass_actions":["account_change","device_add","transfer"]}', '{"bypass_attempts":100,"successful_bypasses":15,"detected_deepfakes":78,"inconclusive":7,"avg_detection_confidence":0.82,"post_bypass_damage":45000}', '[{"path":"social_media_scrape→deepfake_generation→liveness_bypass→account_takeover","probability":0.5},{"path":"stolen_id_document→face_swap→verification_bypass→device_registration","probability":0.35},{"path":"real_time_deepfake→video_call_bypass→authorized_changes","probability":0.15}]', '[{"gap":"Real-time video deepfake detection","impact":"critical","description":"Current liveness checks optimized for pre-recorded videos; real-time face swap during video calls detected only 40% of the time"},{"gap":"Multi-modal verification","impact":"high","description":"Single-factor biometric verification insufficient against high-quality deepfakes"}]', '[{"rule":"Multi-challenge liveness: Random head movement + spoken phrase + lighting variation in single verification","confidence":0.87},{"rule":"Behavioral+biometric fusion: Require both biometric match AND behavioral consistency for high-risk actions","confidence":0.91}]', 0.95, 10000, 'completed', NOW() - INTERVAL '1 day');
