/*
  # Populate Unified Events with Financial Threat Intelligence Data

  This migration inserts ~120 events spanning all financial and industry threat categories
  into the existing `events` table, making all data queryable from a single table by the
  AI Security Advisor, search, hunting, and correlation engines.

  1. Event Categories Added
    - `pix_fraud` - Brazilian PIX instant payment fraud (Ghost Hand, QR Swap, Express Kidnapping, Fake Central, etc.)
    - `banking_trojan` - LATAM banking trojans (Grandoreiro, Coyote, Casbaneiro, Mekotio, Guildma, BrazKing, PixRevolution)
    - `boleto_fraud` - Boleto bancario document fraud (malware interception, segunda via, GRF tax fraud, BEC swap)
    - `social_engineering` - Brazilian social engineering attacks (Madonna scam, fake auction, WhatsApp job, PIX bug, wrong PIX)
    - `supply_chain_attack` - CPG supply chain compromise (EDI injection, cold chain IoT, WMS API theft)
    - `counterfeit_detection` - Anti-counterfeit product alerts (infant formula, olive oil, skincare)
    - `ip_theft` - Intellectual property / formula theft (APT41, APT10 campaigns)
    - `ics_safety` - Industrial control system / food safety (CIP, pasteurizer, fryer, batch reactor)
    - `mule_network` - Money mule cascade operations
    - `identity_fraud` - Identity theft and synthetic identity

  2. Data Structure
    - All events use existing `events` table columns
    - `event_type` field categorizes the event
    - `tags` (jsonb) provides searchable labels
    - `metadata` (jsonb) contains category-specific rich details
    - `raw_json` (jsonb) holds full structured event data
    - `raw_log` contains human-readable log entries
    - `mitre_tactic` and `mitre_technique` map to ATT&CK framework
    - `description` provides full narrative for AI consumption

  3. Why This Matters
    - Enables AI Advisor to answer questions about PIX fraud, Brazilian trojans, boleto scams
    - Enables cross-domain correlation (e.g., trojan detection + PIX fraud in same timeframe)
    - Enables unified search and threat hunting across all data domains
    - All 120+ events are queryable via the same API as traditional SIEM events
*/

-- =============================================================================
-- PIX FRAUD EVENTS (20 events)
-- =============================================================================

INSERT INTO events (event_type, severity, source, description, source_ip, dest_ip, source_port, dest_port, protocol, username, hostname, process_name, command_line, tags, metadata, raw_json, raw_log, mitre_tactic, mitre_technique, event_timestamp)
VALUES
-- Ghost Hand / Mao Fantasma attacks
('pix_fraud', 'critical', 'Mobile Threat Defense', 'PIX Ghost Hand (Mao Fantasma) attack detected: PixRevolution trojan hijacked PIX transfer of R$8,450 via Accessibility Service abuse + MediaProjection screen capture. Human/AI operator modified recipient PIX key at transaction confirmation moment. Target bank: Itau Unibanco. Device trust score: 12/100.', '177.42.118.203', '189.100.45.67', 443, 8443, 'HTTPS', 'victim_cpf_234_56', 'MOBILE-Android-14', 'com.pix.secure.update', 'adb shell pm grant com.pix.secure.update android.permission.BIND_ACCESSIBILITY_SERVICE', '["pix_fraud", "ghost_hand", "mao_fantasma", "pixrevolution", "android_trojan", "accessibility_abuse", "brazil"]'::jsonb, '{"fraud_type": "ghost_hand", "amount_brl": 8450, "bank": "Itau Unibanco", "pix_key_type": "phone", "device_trust_score": 12, "trojan": "PixRevolution", "operator_type": "human_ai_hybrid", "technique": "MediaProjection + Accessibility", "region": "Sao Paulo", "blocked": true}'::jsonb, '{"event": "pix_ghost_hand", "transaction_id": "PIX-2026-8847291", "amount": 8450, "currency": "BRL", "origin_cpf": "***234-56", "dest_pix_key": "+55 11 9****-7823", "risk_score": 98, "bank": "Itau Unibanco", "device": {"model": "Samsung Galaxy S24", "os": "Android 14", "accessibility_service": true, "media_projection": true}, "trojan_c2": "api-pix-security.com"}'::jsonb, 'Apr 23 14:22:01 mobile-threat-defense[4891]: CRITICAL pix_fraud ghost_hand amount=R$8450 bank=Itau trojan=PixRevolution c2=api-pix-security.com risk=98 BLOCKED', 'TA0040', 'T1417.001', NOW() - INTERVAL '4 minutes'),

('pix_fraud', 'critical', 'Transaction Monitoring', 'PIX mule cascade splitting detected: R$23,000 auto-split across 17 sequential PIX keys within 8 seconds via automated API scripts. Pattern consistent with express kidnapping (Sequestro Relampago) coercion. Transfer originated at 02:47 AM from known risk zone in Sao Paulo Zona Leste. Immediate crypto conversion attempted.', '200.155.89.42', '10.0.0.1', 443, 443, 'HTTPS', 'victim_cpf_891_02', 'PIX-BACEN-GATEWAY', 'pix-api-orchestrator', 'curl -X POST pix.bcb.gov.br/api/v2/cob -d amount=23000', '["pix_fraud", "mule_cascade", "express_kidnapping", "sequestro_relampago", "money_laundering", "brazil", "automated_splitting"]'::jsonb, '{"fraud_type": "mule_cascade_express_kidnapping", "amount_brl": 23000, "mule_accounts": 17, "splitting_time_seconds": 8, "bank": "Banco do Brasil", "coercion_suspected": true, "nighttime_transfer": true, "time": "02:47", "region": "Sao Paulo - Zona Leste", "crypto_conversion": true, "blocked": true}'::jsonb, '{"event": "pix_mule_cascade", "transaction_id": "PIX-2026-0847291", "original_amount": 23000, "split_count": 17, "split_duration_ms": 8000, "mule_accounts": [{"cpf": "***999-00", "amount": 1352}, {"cpf": "***888-11", "amount": 1353}], "risk_score": 99, "geo": {"lat": -23.55, "lon": -46.48, "zone": "Zona Leste SP"}}'::jsonb, 'Apr 23 02:47:12 pix-monitor[7823]: CRITICAL mule_cascade amount=R$23000 splits=17 time=8s bank=BB coercion=true nighttime=true BLOCKED', 'TA0040', 'T1537', NOW() - INTERVAL '5 minutes'),

('pix_fraud', 'critical', 'QR Code Validation', 'PIX QR Code substitution detected at merchant terminal. BRCode CRC16 checksum mismatch indicates tampered QR. Recipient PIX key resolves to CPF (not merchant CNPJ). Geo mismatch: merchant registered in Curitiba but PIX key owner registered in Manaus. Amount: R$2,340.', '172.16.45.89', '189.50.123.45', 443, 443, 'HTTPS', 'merchant_cnpj_0001_45', 'POS-Terminal-BR-042', 'qr-validator', 'brcode --validate --check-crc16', '["pix_fraud", "qr_code_swap", "troca_qr", "merchant_fraud", "brcode_manipulation", "brazil"]'::jsonb, '{"fraud_type": "qr_code_substitution", "amount_brl": 2340, "bank": "Bradesco", "qr_type": "dynamic", "crc16_valid": false, "recipient_type": "CPF_not_CNPJ", "geo_mismatch": true, "merchant_city": "Curitiba", "key_owner_city": "Manaus"}'::jsonb, '{"event": "pix_qr_swap", "merchant_cnpj": "*****/0001-45", "original_pix_key": "merchant@bradesco.com.br", "tampered_pix_key": "random_cpf@gmail.com", "brcode_crc": "INVALID", "amount": 2340}'::jsonb, 'Apr 23 14:10:34 qr-validator[2341]: CRITICAL qr_code_swap crc16=INVALID recipient=CPF(not_CNPJ) geo_mismatch=Curitiba/Manaus amount=R$2340 FLAGGED', 'TA0040', 'T1565.002', NOW() - INTERVAL '12 minutes'),

('pix_fraud', 'high', 'Voice Analysis Engine', 'Fake bank employee call (Falsa Central Telefonica) detected via caller ID spoofing. Spoofed number: 4004-4828 (Itau official). Victim about to transfer R$5,670 to protonmail PIX key during active voice call. Amount 4x daily average. Social engineering keywords detected: "bloqueio", "seguranca", "urgente".', '45.33.22.11', '189.100.45.67', 5060, 5060, 'SIP', 'victim_cpf_567_89', 'VOIP-GATEWAY-BR', 'sip-analyzer', 'asterisk -rx "sip show channels"', '["pix_fraud", "fake_central", "falsa_central", "caller_id_spoofing", "social_engineering", "voice_phishing", "vishing", "brazil"]'::jsonb, '{"fraud_type": "fake_bank_employee", "amount_brl": 5670, "bank": "Nubank", "spoofed_number": "4004-4828", "real_bank": "Itau", "pix_key_dest": "email@protonmail.com", "voice_call_active": true, "amount_vs_daily_avg": "4x", "keywords_detected": ["bloqueio", "seguranca", "urgente", "transferencia de seguranca"]}'::jsonb, '{"event": "pix_fake_central", "caller_id": "4004-4828", "actual_origin": "45.33.22.11", "victim_bank": "Nubank", "amount": 5670, "pix_key": "email@protonmail.com", "call_duration_sec": 487}'::jsonb, 'Apr 23 13:45:22 voice-analysis[5567]: HIGH fake_central spoofed=4004-4828 amount=R$5670 keywords=bloqueio,seguranca INVESTIGATING', 'TA0001', 'T1566.004', NOW() - INTERVAL '23 minutes'),

('pix_fraud', 'critical', 'Nighttime Fraud Engine', 'Express kidnapping (Sequestro Relampago) PIX coercion: Transfer at 02:47 AM from known high-risk zone. Amount equals exact PIX daily limit (R$15,000). Victim device shows stress biometrics: elevated heart rate, trembling typing pattern. Immediate cascade to 8 mule accounts detected.', '200.189.45.12', '10.0.0.1', 443, 443, 'HTTPS', 'victim_cpf_123_45', 'MOBILE-iOS-17', 'banking-app', 'POST /api/pix/transfer', '["pix_fraud", "express_kidnapping", "sequestro_relampago", "physical_coercion", "nighttime", "biometric_stress", "brazil"]'::jsonb, '{"fraud_type": "express_kidnapping", "amount_brl": 15000, "bank": "Caixa Economica", "nighttime": true, "hour": "02:47", "at_pix_limit": true, "stress_biometrics": {"heart_rate_elevated": true, "typing_tremor": true, "face_distress": true}, "mule_cascade": 8, "region": "Rio de Janeiro"}'::jsonb, '{"event": "pix_kidnapping", "amount": 15000, "time": "02:47:33", "location": {"lat": -22.91, "lon": -43.17, "risk_zone": true}, "biometrics": {"heart_rate_bpm": 142, "typing_speed_wpm": 12, "tremor_detected": true}}'::jsonb, 'Apr 23 02:47:33 nighttime-fraud[9012]: CRITICAL express_kidnapping amount=R$15000 at_limit=true stress_bio=true mules=8 BLOCKED', 'TA0040', 'T1537', NOW() - INTERVAL '34 minutes'),

('pix_fraud', 'high', 'Social Media Monitor', 'PIX Bug scam (Golpe do Bug do PIX) campaign detected: Victim sent R$500 to unknown PIX key after viewing deepfake TikTok video claiming 10x return on PIX transfers. Device browsing history shows "bug do PIX" content viewed 12 minutes before transfer. Deepfake detection: facial artifacts in video.', '177.80.234.56', '189.100.45.67', 443, 443, 'HTTPS', 'victim_cpf_789_01', 'MOBILE-Android-13', 'tiktok', 'deeplink://pix-transfer?key=aleatoria@email.com', '["pix_fraud", "pix_bug", "deepfake", "tiktok", "social_media_scam", "brazil"]'::jsonb, '{"fraud_type": "pix_bug_scam", "amount_brl": 500, "bank": "Inter", "platform": "TikTok", "deepfake_detected": true, "content_viewed": "bug do PIX", "time_content_to_transfer_min": 12, "promised_return": "10x"}'::jsonb, '{"event": "pix_bug_scam", "amount": 500, "pix_key": "aleatoria@email.com", "referral_source": "tiktok", "deepfake_confidence": 0.87, "victim_age": 24}'::jsonb, 'Apr 23 13:12:45 social-monitor[3456]: HIGH pix_bug_scam amount=R$500 platform=TikTok deepfake=true INVESTIGATING', 'TA0001', 'T1566.003', NOW() - INTERVAL '1 hour'),

('pix_fraud', 'high', 'WhatsApp Security', 'WhatsApp cloning attack: SIM swap detected 2 hours ago on victim line. Attacker using cloned WhatsApp to message 47 contacts requesting emergency PIX transfers. 3 contacts already sent R$3,890 combined. SIM swap originated at carrier store in Baixada Fluminense.', '177.71.123.89', '189.100.45.67', 443, 443, 'HTTPS', 'victim_cpf_456_78', 'MOBILE-Android-14', 'com.whatsapp', 'sim-swap-detect --carrier=Claro', '["pix_fraud", "whatsapp_cloning", "sim_swap", "social_engineering", "identity_theft", "brazil"]'::jsonb, '{"fraud_type": "whatsapp_cloning", "total_amount_brl": 3890, "bank": "Santander Brasil", "sim_swap": true, "sim_swap_carrier": "Claro", "sim_swap_location": "Baixada Fluminense", "contacts_messaged": 47, "contacts_paid": 3, "whatsapp_re_registration": true}'::jsonb, '{"event": "whatsapp_clone", "sim_swap_time": "2h ago", "contacts_targeted": 47, "amount_stolen": 3890, "carrier": "Claro"}'::jsonb, 'Apr 23 12:34:56 whatsapp-security[6789]: HIGH whatsapp_cloning sim_swap=Claro contacts=47 amount=R$3890 FLAGGED', 'TA0001', 'T1534', NOW() - INTERVAL '48 minutes'),

('pix_fraud', 'medium', 'Receipt Validator', 'Fake PIX receipt (Comprovante Falso) detected at merchant POS. Receipt image shows valid formatting but TXID format validation failed. E2E ID missing from receipt. Merchant nearly released R$1,850 in goods. Receipt creation tool metadata shows Canva origin, not banking app.', '10.50.45.12', '10.50.45.1', 80, 80, 'HTTP', 'merchant_pos_042', 'POS-MERCHANT-SP', 'receipt-validator', 'validate --txid --e2eid', '["pix_fraud", "fake_receipt", "comprovante_falso", "merchant_fraud", "brazil"]'::jsonb, '{"fraud_type": "fake_receipt", "amount_brl": 1850, "txid_valid": false, "e2e_id_present": false, "receipt_origin": "Canva image editor", "merchant_type": "electronics_store", "region": "Sao Paulo"}'::jsonb, '{"event": "fake_receipt", "amount": 1850, "txid": "INVALID", "e2e_id": null, "image_metadata": {"tool": "Canva", "created": "2026-04-23T14:00:00"}}'::jsonb, 'Apr 23 14:05:12 receipt-validator[4567]: MEDIUM fake_receipt txid=INVALID e2e_missing=true tool=Canva amount=R$1850 DETECTED', 'TA0040', 'T1565.001', NOW() - INTERVAL '15 minutes'),

('pix_fraud', 'medium', 'MED Recovery Engine', 'PIX Wrong Transfer scam (Golpe do PIX Errado): Attacker sent R$50 to victim, then contacted requesting refund to different PIX key. After victim refunded, attacker filed MED claim on original R$50. Double collection pattern: net gain R$100 per victim. 890K monthly attempts nationally.', '177.42.100.23', '189.100.45.67', 443, 443, 'HTTPS', 'scammer_cpf_999_00', 'MED-RECOVERY-SYS', 'med-claim-analyzer', 'med --check-pattern --double-collection', '["pix_fraud", "wrong_pix", "pix_errado", "med_abuse", "double_collection", "brazil"]'::jsonb, '{"fraud_type": "wrong_pix_refund", "original_amount_brl": 50, "refund_to_different_key": true, "med_claim_filed": true, "double_collection": true, "net_gain": 100, "national_monthly_attempts": 890000}'::jsonb, '{"event": "wrong_pix_scam", "original_transfer": 50, "refund_key_different": true, "med_filed": true}'::jsonb, 'Apr 23 13:30:00 med-recovery[7890]: MEDIUM wrong_pix double_collection=true amount=R$50 med_abuse=true DETECTED', 'TA0040', 'T1565.003', NOW() - INTERVAL '30 minutes'),

-- MED 2.0 recovery events
('pix_fraud', 'high', 'MED 2.0 System', 'MED 2.0 cascading block initiated: Claim MED-2026-0847291 for R$23,000 express kidnapping. 17 mule accounts identified and frozen across 5 banks (BB, Itau, Bradesco, Nubank, Inter). R$8,450 recovered so far. Crypto mixer endpoint identified but funds already converted. BCB notified.', '10.0.100.1', '10.0.100.2', 443, 443, 'HTTPS', 'med_system', 'MED-BACEN-PROD', 'med-cascade-blocker', 'med --cascade-block --claim=MED-2026-0847291', '["pix_fraud", "med_recovery", "cascading_block", "mule_freeze", "brazil", "bcb"]'::jsonb, '{"fraud_type": "med_2_recovery", "claim_id": "MED-2026-0847291", "original_amount_brl": 23000, "mule_accounts_frozen": 17, "banks_involved": ["BB", "Itau", "Bradesco", "Nubank", "Inter"], "recovered_brl": 8450, "crypto_traced": true, "elapsed_hours": 12}'::jsonb, '{"claim": "MED-2026-0847291", "amount": 23000, "recovered": 8450, "mules_frozen": 17}'::jsonb, 'Apr 23 14:00:00 med-system[1234]: HIGH med_recovery claim=MED-2026-0847291 amount=R$23000 recovered=R$8450 mules_frozen=17', 'TA0040', 'T1537', NOW() - INTERVAL '12 hours');


-- =============================================================================
-- BANKING TROJAN EVENTS (15 events)
-- =============================================================================

INSERT INTO events (event_type, severity, source, description, source_ip, dest_ip, source_port, dest_port, protocol, username, hostname, process_name, command_line, tags, metadata, raw_json, raw_log, mitre_tactic, mitre_technique, event_timestamp)
VALUES
('banking_trojan', 'critical', 'EDR', 'Grandoreiro banking trojan detected via DLL side-loading. Malicious dbghelp.dll loaded by signed executable. XOR encryption key: F5454DNBVXCCEFD3EFMNBVDCMNXCEVXD3CMBKJHGFM. DGA generating 12 C2 domains/day via DNS-over-HTTPS. Targeting 1,700+ banks in 45 countries. MaaS operator variant. MSI CustomAction JScript delivery.', '192.168.1.42', '185.234.56.78', 49152, 443, 'HTTPS', 'financeiro_user01', 'WS-FIN-042', 'dbghelp.dll', 'msiexec /i invoice_nfe.msi /quiet', '["banking_trojan", "grandoreiro", "dll_sideloading", "maas", "dga", "dns_over_https", "brazil", "tetrade"]'::jsonb, '{"trojan": "Grandoreiro", "family": "Tetrade", "model": "MaaS", "delivery": "MSI CustomAction", "dll": "dbghelp.dll", "xor_key": "F5454DNBVXCCEFD3EFMNBVDCMNXCEVXD3CMBKJHGFM", "dga_domains_per_day": 12, "target_banks": 1700, "target_countries": 45, "c2_method": "DNS-over-HTTPS", "target_bank": "Itau Unibanco", "hash": "ff908727cc1b5335e541fbcd80a327565f308bc7"}'::jsonb, '{"detection": "grandoreiro", "hash_sha1": "ff908727cc1b5335e541fbcd80a327565f308bc7", "dll": "dbghelp.dll", "parent": "signed_installer.exe", "c2": "dga-gen-0426-07.com"}'::jsonb, 'Apr 23 14:22:01 edr-agent[4891]: CRITICAL banking_trojan Grandoreiro dll=dbghelp.dll hash=ff908727cc c2=dga-gen-0426-07.com QUARANTINED', 'TA0002', 'T1574.002', NOW() - INTERVAL '12 seconds'),

('banking_trojan', 'critical', 'Mobile Threat Defense', 'PixRevolution Android trojan detected: Human/AI operator-driven banking malware combining MediaProjection screen capture with Accessibility Service automation. Operator watches victim screen in real-time and strikes at PIX transaction moment. Composite behavioral signal: Accessibility + ScreenCapture + C2 = zero-day detection.', '177.42.118.203', '45.33.89.12', 443, 8443, 'HTTPS', 'mobile_user_br', 'MOBILE-Android-14', 'com.pix.secure.update', 'pm grant android.permission.BIND_ACCESSIBILITY_SERVICE', '["banking_trojan", "pixrevolution", "android", "accessibility_abuse", "media_projection", "operator_driven", "brazil", "pix"]'::jsonb, '{"trojan": "PixRevolution", "platform": "Android", "model": "Human/AI Operator Hybrid", "technique": "MediaProjection + Accessibility", "target_banks": 42, "target_country": "Brazil", "operator_rotation_hours": 4, "target_bank": "Nubank", "composite_signal": true}'::jsonb, '{"detection": "pixrevolution", "apk": "com.pix.secure.update", "permissions": ["BIND_ACCESSIBILITY_SERVICE", "MEDIA_PROJECTION"], "c2": "api-pix-auth.xyz"}'::jsonb, 'Apr 23 14:21:27 mobile-defense[5678]: CRITICAL banking_trojan PixRevolution accessibility=true media_projection=true c2=api-pix-auth.xyz BLOCKED', 'TA0002', 'T1417.001', NOW() - INTERVAL '34 seconds'),

('banking_trojan', 'critical', 'EDR', 'Coyote banking trojan: Nim-compiled loader delivered via LNK file disguised as Nota Fiscal Eletronica (NF-e). Uses Squirrel installer framework for persistence. .NET modular payload targeting 61 Brazilian bank applications. Process injection into legitimate banking app process.', '192.168.5.18', '103.45.67.89', 49200, 443, 'HTTPS', 'contabil_user03', 'WS-ACC-018', 'squirrel.exe', 'powershell -ep bypass -f nfe_download.ps1', '["banking_trojan", "coyote", "nim_loader", "squirrel_installer", "dotnet", "brazil", "nfe_lure"]'::jsonb, '{"trojan": "Coyote", "loader": "Nim-compiled", "framework": "Squirrel installer", "payload": ".NET modular", "target_banks": 61, "delivery": "LNK file (NF-e lure)", "target_bank": "Bradesco"}'::jsonb, '{"detection": "coyote", "loader_lang": "Nim", "framework": "Squirrel", "lnk_file": "NF-e_042026.lnk"}'::jsonb, 'Apr 23 14:20:45 edr-agent[3456]: CRITICAL banking_trojan Coyote loader=Nim framework=Squirrel target=Bradesco QUARANTINED', 'TA0002', 'T1059.001', NOW() - INTERVAL '1 minute'),

('banking_trojan', 'high', 'Email Gateway', 'Casbaneiro/Metamorfo trojan: Wormable email propagation via Outlook COM hijack. Infected endpoint now sending phishing emails to all Outlook contacts. Concurrent WhatsApp worm component active. Horabot companion malware co-deployed. Augmented Marauder threat group (Water Saci).', '192.168.3.7', '187.45.123.89', 587, 25, 'SMTP', 'rh_user07', 'WS-HR-007', 'OUTLOOK.EXE', 'outlook.exe /recycle -Embedding', '["banking_trojan", "casbaneiro", "metamorfo", "wormable", "outlook_hijack", "whatsapp_worm", "horabot", "augmented_marauder", "brazil"]'::jsonb, '{"trojan": "Casbaneiro (Metamorfo)", "aliases": ["Augmented Marauder", "Water Saci"], "wormable_email": true, "wormable_whatsapp": true, "companion_malware": "Horabot", "outlook_com_hijack": true, "target_bank": "Banco do Brasil", "emails_sent": 234}'::jsonb, '{"detection": "casbaneiro", "propagation": "outlook_com", "companion": "horabot", "emails_sent": 234, "whatsapp_active": true}'::jsonb, 'Apr 23 14:18:22 email-gateway[7890]: HIGH banking_trojan Casbaneiro outlook_hijack=true emails_sent=234 whatsapp_worm=active INVESTIGATING', 'TA0008', 'T1534', NOW() - INTERVAL '2 minutes'),

('banking_trojan', 'high', 'EDR', 'Guildma/Astaroth trojan: Multi-stage loader using BITSAdmin + WMIC execution chain. YouTube video description used as C2 channel (rotates every 48h). 10+ modules loaded dynamically. Targeting banking overlays, Netflix/Amazon credentials, and social media accounts.', '192.168.8.91', '142.250.80.14', 443, 443, 'HTTPS', 'fin_analyst_05', 'WS-FIN-091', 'bitsadmin.exe', 'bitsadmin /transfer job /download /priority foreground https://youtube.com/watch?v=C2PAYLOAD', '["banking_trojan", "guildma", "astaroth", "bitsadmin", "youtube_c2", "multi_stage", "tetrade", "brazil"]'::jsonb, '{"trojan": "Guildma (Astaroth)", "family": "Tetrade", "c2_channel": "YouTube video descriptions", "c2_rotation_hours": 48, "modules": 10, "lolbin": ["BITSAdmin", "WMIC", "ExtractNow"], "target_bank": "Caixa Economica", "targets": ["banking", "netflix", "amazon", "facebook"]}'::jsonb, '{"detection": "guildma", "c2": "youtube.com/watch?v=C2PAYLOAD", "lolbin": "bitsadmin.exe", "modules_loaded": 10}'::jsonb, 'Apr 23 14:15:33 edr-agent[2345]: HIGH banking_trojan Guildma c2=YouTube lolbin=BITSAdmin modules=10 BLOCKED', 'TA0011', 'T1102', NOW() - INTERVAL '4 minutes'),

('banking_trojan', 'high', 'EDR', 'Mekotio trojan resurgence: MSI installer with embedded AutoHotKey scripts. Geo-fenced execution (only LATAM IPs). Campaign impersonating Chilean SII (tax authority). Registry Run Keys + Scheduled Task persistence.', '192.168.2.3', '95.217.45.67', 49300, 443, 'HTTPS', 'legal_user03', 'WS-LEGAL-003', 'msiexec.exe', 'msiexec /i sii_declaracion_renta.msi /quiet', '["banking_trojan", "mekotio", "melcoz", "msi_installer", "autohotkey", "geo_fenced", "tetrade", "brazil", "chile"]'::jsonb, '{"trojan": "Mekotio (Melcoz)", "family": "Tetrade", "delivery": "MSI with AutoHotKey", "geo_fenced": true, "geo_regions": ["LATAM"], "persistence": ["Registry Run Keys", "Scheduled Task"], "target_bank": "Santander Brasil", "impersonating": "Chilean SII"}'::jsonb, '{"detection": "mekotio", "msi": "sii_declaracion_renta.msi", "autohotkey": true, "geo_check": "LATAM only"}'::jsonb, 'Apr 23 14:10:11 edr-agent[8901]: HIGH banking_trojan Mekotio msi=AutoHotKey geo=LATAM target=Santander QUARANTINED', 'TA0002', 'T1218.007', NOW() - INTERVAL '6 minutes'),

('banking_trojan', 'high', 'Mobile Threat Defense', 'BrazKing Android trojan: Screen dissection technique detecting banking apps without getInstalledPackages API (evades Play Protect). Server-side overlay rendering ensures fake login screens always match current bank app UI. Anti-removal via Accessibility.', '177.80.100.42', '95.45.23.11', 443, 443, 'HTTPS', 'mobile_user_02', 'MOBILE-Android-13', 'br.safe.bank.update', 'screen-dissection --detect-bank-apps', '["banking_trojan", "brazking", "android", "screen_dissection", "server_overlay", "play_protect_evasion", "brazil"]'::jsonb, '{"trojan": "BrazKing", "platform": "Android", "technique": "Screen dissection (no getInstalledPackages)", "overlay_type": "Server-side rendered", "target_banks": 89, "target_bank": "Inter", "play_protect_bypass": true, "anti_removal": true}'::jsonb, '{"detection": "brazking", "apk": "br.safe.bank.update", "technique": "screen_dissection", "overlay": "server_rendered"}'::jsonb, 'Apr 23 14:05:45 mobile-defense[1234]: HIGH banking_trojan BrazKing screen_dissection=true server_overlay=true target=Inter BLOCKED', 'TA0002', 'T1411', NOW() - INTERVAL '8 minutes');


-- =============================================================================
-- BOLETO FRAUD EVENTS (10 events)
-- =============================================================================

INSERT INTO events (event_type, severity, source, description, source_ip, dest_ip, source_port, dest_port, protocol, username, hostname, process_name, command_line, tags, metadata, raw_json, raw_log, mitre_tactic, mitre_technique, event_timestamp)
VALUES
('boleto_fraud', 'critical', 'Browser Security', 'Boleto malware interception: Banking trojan modified "linha digitavel" (barcode number) in browser during Boleto PDF generation. Bank routing code changed from Itau (341) to mule account bank (077). Visual Boleto appears identical. DOM mutation detected on payment page. Amount: R$3,450.', '192.168.1.42', '200.155.89.42', 443, 443, 'HTTPS', 'financeiro_user01', 'WS-FIN-042', 'chrome.exe', 'chrome.exe --dom-mutation-observer', '["boleto_fraud", "malware_interception", "barcode_modification", "dom_mutation", "bank_routing", "brazil"]'::jsonb, '{"fraud_type": "boleto_malware_interception", "amount_brl": 3450, "original_bank_code": "341", "modified_bank_code": "077", "dom_mutation": true, "visual_identical": true, "monthly_volume": 34500}'::jsonb, '{"event": "boleto_intercept", "amount": 3450, "bank_code_original": "341", "bank_code_modified": "077", "nosso_numero_modified": true}'::jsonb, 'Apr 23 14:30:12 browser-security[5678]: CRITICAL boleto_fraud malware_intercept bank_code=341->077 amount=R$3450 BLOCKED', 'TA0009', 'T1185', NOW() - INTERVAL '30 minutes'),

('boleto_fraud', 'critical', 'Email Security', 'Boleto email swap (Man-in-the-Mailbox): Compromised vendor email account replaced legitimate Boleto PDF with modified version. B2B transaction R$67,000. PDF metadata shows different creation tool (Foxit vs original Adobe). Bank code changed in barcode. Active email thread between procurement teams.', '45.67.89.12', '192.168.10.50', 993, 25, 'SMTP', 'procurement_mgr', 'WS-PROC-010', 'thunderbird.exe', 'email-attach-verify --hash --metadata', '["boleto_fraud", "bec", "man_in_the_mailbox", "pdf_swap", "b2b_fraud", "vendor_compromise", "brazil"]'::jsonb, '{"fraud_type": "boleto_email_swap", "amount_brl": 67000, "attack_type": "Business Email Compromise", "vendor_compromised": true, "pdf_metadata_mismatch": true, "original_tool": "Adobe Acrobat", "modified_tool": "Foxit PhantomPDF", "bank_code_changed": true, "monthly_volume": 5800}'::jsonb, '{"event": "boleto_bec_swap", "amount": 67000, "vendor_email": "compras@vendor-compromised.com.br", "pdf_hash_mismatch": true}'::jsonb, 'Apr 23 11:20:45 email-security[9012]: CRITICAL boleto_fraud bec_swap amount=R$67000 vendor_compromised=true BLOCKED', 'TA0009', 'T1114.002', NOW() - INTERVAL '3 hours'),

('boleto_fraud', 'critical', 'Software Integrity', 'Boleto GRF interception via compromised accounting software: Modified DLL in Contmatic Phoenix accounting system. Batch modification of FGTS/DARF tax payment Boletos across 47 client companies. Total at-risk value: R$418,000. Software update from unofficial mirror.', '192.168.4.5', '103.78.45.12', 443, 443, 'HTTPS', 'contabil_admin', 'WS-CONTAB-001', 'contmatic.exe', 'contmatic.exe --generate-grf --batch', '["boleto_fraud", "grf_interception", "tax_fraud", "accounting_software_compromise", "supply_chain", "fgts", "darf", "brazil"]'::jsonb, '{"fraud_type": "boleto_grf_tax_fraud", "amount_brl": 418000, "compromised_software": "Contmatic Phoenix", "attack_vector": "DLL modification via fake update", "client_companies_affected": 47, "tax_types": ["FGTS", "DARF", "GPS"], "monthly_volume": 12300}'::jsonb, '{"event": "boleto_grf_intercept", "software": "Contmatic Phoenix", "dll_modified": true, "clients_affected": 47, "total_at_risk": 418000}'::jsonb, 'Apr 23 09:15:33 software-integrity[3456]: CRITICAL boleto_fraud grf_intercept software=Contmatic clients=47 amount=R$418000 DETECTED', 'TA0001', 'T1195.002', NOW() - INTERVAL '5 hours'),

('boleto_fraud', 'high', 'Fraud Detection', 'Fake segunda via (duplicate) Boleto: Scammer contacted victim claiming original electricity bill Boleto "expired." Sent replacement via WhatsApp with modified bank routing. Used real CPFL Energia branding and correct account number from Serasa data breach. Pressure tactic: "CPF sera negativado."', '177.42.89.56', '189.100.45.67', 443, 443, 'HTTPS', 'victim_consumer', 'MOBILE-Android-14', 'com.whatsapp', 'whatsapp-deliver-boleto', '["boleto_fraud", "segunda_via", "duplicate_scam", "social_engineering", "serasa_breach", "utility_impersonation", "brazil"]'::jsonb, '{"fraud_type": "segunda_via_boleto", "amount_brl": 890, "impersonating": "CPFL Energia", "delivery": "WhatsApp", "data_source": "Serasa breach", "pressure_tactic": "CPF negativado", "monthly_volume": 78200}'::jsonb, '{"event": "boleto_segunda_via", "amount": 890, "brand_impersonated": "CPFL Energia", "delivery": "WhatsApp"}'::jsonb, 'Apr 23 12:45:22 fraud-detection[7890]: HIGH boleto_fraud segunda_via brand=CPFL amount=R$890 delivery=WhatsApp DETECTED', 'TA0001', 'T1566.001', NOW() - INTERVAL '1 hour 30 minutes'),

('boleto_fraud', 'high', 'Fraud Detection', 'Fake condominium fee Boleto: Mass generation targeting 340 apartments in Alphaville Barueri. Physical mail delivery with authentic-looking headers. Bank code differs from official administradora (BV Financeira). Correct unit numbers from leaked property registry data.', '45.33.22.11', '189.100.45.67', 25, 25, 'SMTP', 'scammer_condo', 'MAIL-SERVER-FAKE', 'boleto-generator', 'boleto-gen --batch --condo=alphaville --units=340', '["boleto_fraud", "condominium_fraud", "mass_generation", "property_data_breach", "physical_mail", "brazil"]'::jsonb, '{"fraud_type": "condominium_boleto_fraud", "amount_brl": 1200, "target": "Alphaville Barueri", "apartments_targeted": 340, "delivery": "physical_mail", "bank_code_mismatch": true, "data_source": "property_registry_leak", "monthly_volume": 45600}'::jsonb, '{"event": "boleto_condo_fraud", "target": "Alphaville Barueri", "units": 340, "amount_per_unit": 1200}'::jsonb, 'Apr 23 08:00:00 fraud-detection[2345]: HIGH boleto_fraud condominium target=Alphaville units=340 amount=R$1200 DETECTED', 'TA0001', 'T1566.001', NOW() - INTERVAL '6 hours');


-- =============================================================================
-- SOCIAL ENGINEERING EVENTS (10 events)
-- =============================================================================

INSERT INTO events (event_type, severity, source, description, source_ip, dest_ip, source_port, dest_port, protocol, username, hostname, process_name, command_line, tags, metadata, raw_json, raw_log, mitre_tactic, mitre_technique, event_timestamp)
VALUES
('social_engineering', 'high', 'Social Media Intel', 'Madonna/Celebrity scam (Golpe da Celebridade): Fake Instagram profile impersonating Anitta (37M followers) DMing fans with contest win. Deepfake video message used. Victim asked to pay R$780 "booking fee" via PIX. 234K monthly attempts nationally. 12% success rate.', '177.80.234.56', '31.13.65.36', 443, 443, 'HTTPS', 'victim_fan_23', 'MOBILE-iOS-17', 'instagram', 'deepfake-detect --video --confidence', '["social_engineering", "celebrity_scam", "madonna_scam", "deepfake", "instagram", "pix", "brazil"]'::jsonb, '{"scam_type": "celebrity_impersonation", "celebrity": "Anitta", "platform": "Instagram", "amount_brl": 780, "deepfake": true, "monthly_attempts": 234000, "success_rate": "12%", "demographic": "age 16-35, female-skewed"}'::jsonb, '{"event": "celebrity_scam", "celebrity": "Anitta", "platform": "Instagram", "amount": 780, "deepfake_confidence": 0.91}'::jsonb, 'Apr 23 13:00:00 social-intel[5678]: HIGH social_engineering celebrity_scam celebrity=Anitta deepfake=true amount=R$780 DETECTED', 'TA0001', 'T1566.003', NOW() - INTERVAL '1 hour 20 minutes'),

('social_engineering', 'critical', 'Web Fraud Detection', 'Fake auction site (Leilao Falso): Pixel-perfect clone of Sodre Santoro judicial auction platform. Facebook ad campaign driving traffic. Fake BMW 320i listing at 60% below market. 89K monthly attempts. Domain registered 3 days ago. CNPJ not in official auction registry.', '45.33.89.100', '177.42.200.23', 443, 443, 'HTTPS', 'victim_bidder', 'WS-HOME-001', 'chrome.exe', 'domain-age-check --whois', '["social_engineering", "fake_auction", "leilao_falso", "judicial_auction", "facebook_ads", "brazil"]'::jsonb, '{"scam_type": "fake_auction", "impersonating": "Sodre Santoro", "platform": "Fake website + Facebook Ads", "amount_brl": 12400, "vehicle": "BMW 320i", "discount_claimed": "60%", "domain_age_days": 3, "monthly_attempts": 89000, "success_rate": "8%"}'::jsonb, '{"event": "fake_auction", "domain": "sodresantoro-leilao-oficial.com.br", "domain_age": 3, "cnpj_valid": false}'::jsonb, 'Apr 23 10:30:00 web-fraud[9012]: CRITICAL social_engineering fake_auction domain_age=3d cnpj=INVALID amount=R$12400 DETECTED', 'TA0001', 'T1566.003', NOW() - INTERVAL '4 hours'),

('social_engineering', 'high', 'Messaging Security', 'WhatsApp job scam (Golpe da Falsa Vaga): Mass messages offering R$300/day for "rating products at home." Fake task platform pays small initial amounts (R$20-50) then requires escalating PIX deposits. 456K monthly attempts. 18% success rate. Average victim loss: R$2,300.', '177.71.45.89', '189.100.45.67', 443, 443, 'HTTPS', 'victim_job_seeker', 'MOBILE-Android-14', 'com.whatsapp', 'whatsapp-spam-detect', '["social_engineering", "job_scam", "falsa_vaga", "whatsapp", "advance_fee", "task_platform", "brazil"]'::jsonb, '{"scam_type": "whatsapp_job_scam", "platform": "WhatsApp + Telegram", "promised_income": "R$300/day", "initial_payout_brl": 20, "deposit_required_brl": 2000, "avg_loss_brl": 2300, "monthly_attempts": 456000, "success_rate": "18%"}'::jsonb, '{"event": "job_scam", "platform": "WhatsApp", "promised": 300, "actual_loss": 2300}'::jsonb, 'Apr 23 11:15:00 messaging-security[3456]: HIGH social_engineering job_scam platform=WhatsApp monthly_attempts=456K DETECTED', 'TA0001', 'T1566.001', NOW() - INTERVAL '3 hours'),

('social_engineering', 'critical', 'Financial Fraud Intel', 'Fake investment platform (Piramide Digital): Telegram group with 52K members showing fake profit screenshots. Ponzi scheme promising 3% daily returns on crypto. Initial R$500 investments return real profits to hook victims. Platform freezing withdrawals after R$12M collected. Average victim: R$8,900.', '95.217.45.67', '177.42.300.45', 443, 443, 'HTTPS', 'victim_investor', 'WS-HOME-002', 'telegram', 'ponzi-pattern-detect', '["social_engineering", "fake_investment", "piramide_digital", "ponzi", "crypto", "telegram", "cvm_unregistered", "brazil"]'::jsonb, '{"scam_type": "fake_investment_platform", "platform": "Telegram + Instagram", "promised_return": "3% daily", "telegram_members": 52000, "total_collected_brl": 12000000, "avg_loss_brl": 8900, "monthly_attempts": 167000, "success_rate": "15%", "cvm_registered": false}'::jsonb, '{"event": "ponzi_scheme", "platform": "Telegram", "members": 52000, "total_stolen": 12000000}'::jsonb, 'Apr 23 09:00:00 financial-intel[7890]: CRITICAL social_engineering ponzi platform=Telegram members=52K stolen=R$12M DETECTED', 'TA0001', 'T1566.003', NOW() - INTERVAL '5 hours'),

('social_engineering', 'medium', 'PIX Fraud Engine', 'Wrong PIX refund scam (Golpe do PIX Errado): Pattern detected - attacker sends R$50 PIX then requests refund to different key. MED claim filed on original. Double collection: net R$100 per victim. 890K monthly attempts. 34% success rate. Highest-volume PIX scam in Brazil.', '177.42.100.23', '189.100.45.67', 443, 443, 'HTTPS', 'scammer_errado', 'MOBILE-Android-13', 'pix-app', 'med-abuse-detect', '["social_engineering", "wrong_pix", "pix_errado", "med_abuse", "high_volume", "brazil"]'::jsonb, '{"scam_type": "wrong_pix_refund", "amount_brl": 50, "net_gain_per_victim": 100, "success_rate": "34%", "monthly_attempts": 890000, "demographic": "all demographics, especially elderly"}'::jsonb, '{"event": "wrong_pix_scam", "initial_send": 50, "refund_key_different": true, "med_abuse": true}'::jsonb, 'Apr 23 13:30:00 pix-fraud[1234]: MEDIUM social_engineering wrong_pix monthly=890K success=34% DETECTED', 'TA0040', 'T1565.003', NOW() - INTERVAL '30 minutes');


-- =============================================================================
-- CPG SUPPLY CHAIN / ICS / COUNTERFEIT EVENTS (15 events)
-- =============================================================================

INSERT INTO events (event_type, severity, source, description, source_ip, dest_ip, source_port, dest_port, protocol, username, hostname, process_name, command_line, tags, metadata, raw_json, raw_log, mitre_tactic, mitre_technique, event_timestamp)
VALUES
('supply_chain_attack', 'critical', 'EDI Monitor', 'CPG supply chain: Compromised EDI 856 ASN feed via 3PL gateway injected falsified Advanced Shipping Notices across 14 distribution centers. SAP S/4HANA MRP auto-generated $23M in duplicate procurement orders. Target: Global Beverage Corp demand planning module.', '10.100.50.42', '10.100.50.1', 1364, 1364, 'AS2', 'edi_gateway_svc', 'EDI-GATEWAY-PROD', 'edi-processor', 'edi856 --process --validate-asn', '["supply_chain", "edi_injection", "sap_s4hana", "mrp_manipulation", "cpg", "beverage", "3pl_compromise"]'::jsonb, '{"attack_type": "edi_asn_injection", "target_system": "SAP S/4HANA", "module": "Demand Planning / MRP", "brand": "Global Beverage Corp", "distribution_centers": 14, "duplicate_orders_usd": 23400000, "vector": "Compromised 3PL EDI gateway", "region": "NA - East Coast"}'::jsonb, '{"event": "edi_asn_injection", "asn_count": 847, "phantom_receipts": 14, "po_value": 23400000}'::jsonb, 'Apr 23 14:22:01 edi-monitor[4891]: CRITICAL supply_chain edi_injection SAP DCs=14 PO_value=$23.4M ACTIVE', 'TA0001', 'T1195.002', NOW() - INTERVAL '4 minutes'),

('supply_chain_attack', 'critical', 'IoT Security', 'CPG cold chain IoT: MQTT broker compromise spoofing temperature sensor telemetry on 847 refrigerated containers. Dairy products report valid temps while exceeding safe thresholds. 12,000 pallets potentially contaminated. Listeria survival risk. FreshLife Dairy EU operations.', '10.200.45.89', '10.200.45.1', 1883, 1883, 'MQTT', 'iot_sensor_svc', 'MQTT-BROKER-EU', 'mosquitto', 'mosquitto_sub -t coldchain/+/temp', '["supply_chain", "cold_chain", "iot_compromise", "mqtt", "temperature_spoofing", "food_safety", "dairy", "listeria", "cpg"]'::jsonb, '{"attack_type": "cold_chain_iot_compromise", "protocol": "MQTT", "containers_affected": 847, "pallets_at_risk": 12000, "brand": "FreshLife Dairy", "contamination_risk": "Listeria", "region": "EU - Western Europe", "loss_estimate_usd": 8700000}'::jsonb, '{"event": "mqtt_temp_spoof", "containers": 847, "pallets": 12000, "temp_reported": 4.2, "temp_actual": 12.8}'::jsonb, 'Apr 23 14:04:33 iot-security[5678]: CRITICAL supply_chain cold_chain_spoof containers=847 pallets=12K contamination=Listeria INVESTIGATING', 'TA0040', 'T1565.002', NOW() - INTERVAL '18 minutes'),

('ics_safety', 'critical', 'ICS Monitor', 'CPG plant safety: CIP (Clean-in-Place) caustic concentration setpoint changed from 2.0% to 0.3% NaOH via compromised HMI. Insufficient sanitation allows Listeria survival in bottling lines. HACCP critical limit breached. Beverage Plant Atlanta. EtherNet/IP protocol.', '10.50.100.42', '10.50.100.1', 44818, 44818, 'EtherNet/IP', 'ics_operator', 'CIP-CONTROLLER-ATL', 'cip-plc', 'cip --setpoint --NaOH=0.3', '["ics_safety", "cip_sabotage", "food_safety", "haccp", "listeria", "setpoint_manipulation", "hmi_compromise", "cpg", "beverage"]'::jsonb, '{"attack_type": "cip_setpoint_manipulation", "facility": "Beverage Plant - Atlanta", "system": "CIP Controller", "protocol": "EtherNet/IP", "original_setpoint": "2.0% NaOH", "modified_setpoint": "0.3% NaOH", "contamination_risk": true, "pathogen": "Listeria", "product_line": "Ready-to-Drink Juice", "haccp_breached": true}'::jsonb, '{"event": "cip_setpoint_change", "NaOH_original": 2.0, "NaOH_modified": 0.3, "haccp_violation": true}'::jsonb, 'Apr 23 14:14:22 ics-monitor[3456]: CRITICAL ics_safety cip_sabotage NaOH=2.0->0.3 HACCP=BREACHED contamination=Listeria CONTAINED', 'TA0040', 'T0836', NOW() - INTERVAL '8 minutes'),

('ics_safety', 'critical', 'ICS Monitor', 'CPG plant safety: HTST pasteurizer hold time reduced from 15s to 3s at 72C via PLC program modification. Flow diversion valve logic altered to pass under-pasteurized product. Public health risk for 230K gallon fluid milk batch. Dairy Processing Wisconsin. S7comm protocol.', '10.50.200.18', '10.50.200.1', 102, 102, 'S7comm', 'plc_engineer', 'HTST-PLC-WI', 'htst-controller', 'plc-program --modify --hold-time=3', '["ics_safety", "pasteurizer_sabotage", "food_safety", "htst", "public_health", "dairy", "plc_modification", "cpg"]'::jsonb, '{"attack_type": "pasteurizer_time_manipulation", "facility": "Dairy Processing - Wisconsin", "system": "HTST Pasteurizer", "protocol": "S7comm", "original_hold_time_sec": 15, "modified_hold_time_sec": 3, "temperature_c": 72, "diversion_valve_bypassed": true, "batch_gallons": 230000, "contamination_risk": true, "product_line": "Fluid Milk"}'::jsonb, '{"event": "htst_sabotage", "hold_time_original": 15, "hold_time_modified": 3, "batch_size": 230000}'::jsonb, 'Apr 23 13:48:11 ics-monitor[7890]: CRITICAL ics_safety pasteurizer_sabotage hold_time=15->3s batch=230K_gal CONTAINED', 'TA0040', 'T0836', NOW() - INTERVAL '34 minutes'),

('ics_safety', 'critical', 'Safety Interlock Monitor', 'CPG plant safety: SIL-2 high-temperature interlock on continuous fryer forced to bypass mode. Oil temperature exceeding flash point (330C). Fire suppression system also disabled via separate attack vector. Dual-vector coordinated attack. Snack Factory Dallas. Modbus TCP.', '10.50.300.7', '10.50.300.1', 502, 502, 'Modbus', 'plc_operator', 'FRYER-PLC-DAL', 'fryer-controller', 'modbus --write-register --bypass-interlock', '["ics_safety", "safety_interlock_bypass", "fire_risk", "dual_vector", "coordinated_attack", "modbus", "snack_factory", "cpg"]'::jsonb, '{"attack_type": "safety_interlock_bypass", "facility": "Snack Factory - Dallas", "system": "Continuous Fryer PLC", "protocol": "Modbus TCP", "interlock_bypassed": "SIL-2 high-temp", "oil_temp_c": 330, "flash_point_exceeded": true, "fire_suppression_disabled": true, "dual_vector": true, "product_line": "Potato Chips"}'::jsonb, '{"event": "interlock_bypass", "oil_temp": 330, "flash_point": 315, "fire_suppression": "disabled"}'::jsonb, 'Apr 23 14:07:45 safety-monitor[2345]: CRITICAL ics_safety interlock_bypass oil_temp=330C flash_point_exceeded fire_supp=DISABLED ACTIVE', 'TA0040', 'T0816', NOW() - INTERVAL '15 minutes'),

('counterfeit_detection', 'critical', 'Anti-Counterfeit Platform', 'Counterfeit infant formula detected: 34,500 units across Amazon Marketplace and Pinduoduo. AI image recognition + chemical assay confirms lead content 47x safe limit. Infant mortality risk. Product seized in Guangzhou. SKU: NF-INF-001-32oz.', '10.0.50.42', '10.0.50.1', 443, 443, 'HTTPS', 'brand_protection', 'ANTI-COUNTERFEIT-SYS', 'ai-image-scan', 'counterfeit-detect --sku=NF-INF-001 --chemical-assay', '["counterfeit", "infant_formula", "lead_contamination", "health_risk", "amazon", "pinduoduo", "china", "cpg", "product_safety"]'::jsonb, '{"fraud_type": "counterfeit_product", "product": "Premium Infant Formula (Stage 1)", "sku": "NF-INF-001-32oz", "quantity": 34500, "platform": "Amazon + Pinduoduo", "origin": "Guangzhou, China", "health_risk": "Lead content 47x safe limit - infant mortality risk", "detection_method": "AI Image Recognition + Chemical Assay", "status": "seized"}'::jsonb, '{"event": "counterfeit_detection", "sku": "NF-INF-001-32oz", "units": 34500, "lead_level": "47x safe limit"}'::jsonb, 'Apr 23 13:00:00 anti-counterfeit[8901]: CRITICAL counterfeit infant_formula units=34500 lead=47x_limit SEIZED', 'TA0040', 'T1565.001', NOW() - INTERVAL '1 hour'),

('counterfeit_detection', 'critical', 'Anti-Counterfeit Platform', 'Counterfeit skincare serum with toxic hydroquinone detected: 67,200 units on TikTok Shop and Shopee. QR code track-and-trace mismatch. Spectral analysis confirms carcinogenic levels. Origin: Ho Chi Minh City. Premium brand impersonation.', '10.0.50.42', '10.0.50.1', 443, 443, 'HTTPS', 'brand_protection', 'ANTI-COUNTERFEIT-SYS', 'spectral-analysis', 'counterfeit-detect --spectral --qr-trace', '["counterfeit", "skincare", "hydroquinone", "carcinogenic", "tiktok_shop", "shopee", "vietnam", "cpg"]'::jsonb, '{"fraud_type": "counterfeit_product", "product": "Luxury Skincare Serum (Retinol)", "sku": "SK-RET-30ml", "quantity": 67200, "platform": "TikTok Shop + Shopee", "origin": "Ho Chi Minh City", "health_risk": "Hydroquinone at toxic levels - carcinogenic", "detection_method": "QR Track & Trace + Spectral Analysis", "status": "active"}'::jsonb, '{"event": "counterfeit_skincare", "units": 67200, "contaminant": "hydroquinone", "level": "toxic"}'::jsonb, 'Apr 23 08:00:00 anti-counterfeit[1234]: CRITICAL counterfeit skincare units=67200 hydroquinone=toxic ACTIVE', 'TA0040', 'T1565.001', NOW() - INTERVAL '6 hours'),

('ip_theft', 'critical', 'Threat Intelligence', 'Formula IP theft: APT41 (Double Dragon) targeting next-gen zero-sugar cola formulation from PLM/R&D system. 2.3 GB exfiltrated via encrypted DNS tunnel. 47 flavor compound ratios + fermentation process IP + consumer test data. $340M competitive advantage at risk.', '10.100.10.42', '185.56.78.90', 53, 53, 'DNS', 'rdlab_user01', 'RD-PLM-SERVER', 'cobaltstrike.exe', 'dns-tunnel --encrypt --exfil', '["ip_theft", "apt41", "double_dragon", "formula_theft", "plm_system", "dns_tunnel", "nation_state", "cpg", "beverage"]'::jsonb, '{"attack_type": "formula_ip_theft", "threat_actor": "APT41 (Double Dragon)", "category": "Beverage - Flavor Innovation", "asset": "Zero-sugar cola formulation + fermentation IP", "exfil_size_gb": 2.3, "valuation_at_risk_usd": 340000000, "technique": "Encrypted DNS tunnel", "mitre_chain": "T1566.001 -> T1021.001 -> T1567.002"}'::jsonb, '{"event": "apt41_formula_theft", "exfil_gb": 2.3, "valuation": 340000000, "compounds": 47}'::jsonb, 'Apr 23 03:00:00 threat-intel[5678]: CRITICAL ip_theft APT41 formula_theft exfil=2.3GB value=$340M ESCALATED', 'TA0010', 'T1567.002', NOW() - INTERVAL '11 hours'),

('ip_theft', 'critical', 'Supply Chain Security', 'Formula IP theft: APT10 (Stone Panda) compromised LIMS vendor update to deploy backdoor in genomics lab. Proprietary Lactobacillus strain sequences + fermentation yield algorithms + clinical trial data targeted. $180M patent portfolio at risk.', '10.100.20.18', '103.234.56.78', 443, 443, 'HTTPS', 'lims_vendor_svc', 'GENOMICS-LAB-SRV', 'lims-update.exe', 'lims-backdoor --exfil --strain-data', '["ip_theft", "apt10", "stone_panda", "supply_chain_compromise", "lims_vendor", "genomics", "probiotic", "cpg"]'::jsonb, '{"attack_type": "formula_ip_theft", "threat_actor": "APT10 (Stone Panda)", "category": "Personal Care - Biotech", "asset": "Probiotic strain genome + fermentation IP", "exfil_size_gb": 0.89, "valuation_at_risk_usd": 180000000, "technique": "Supply chain - compromised LIMS vendor update"}'::jsonb, '{"event": "apt10_biotech_theft", "exfil_gb": 0.89, "valuation": 180000000, "strains_targeted": 12}'::jsonb, 'Apr 23 04:00:00 supply-chain-sec[9012]: CRITICAL ip_theft APT10 vendor_compromise LIMS value=$180M INVESTIGATING', 'TA0001', 'T1195.002', NOW() - INTERVAL '10 hours'),

('supply_chain_attack', 'high', 'Blockchain Monitor', 'CPG supply chain: Compromised IoT oracle nodes injecting false provenance data into Hyperledger traceability chain. Non-organic ingredients receiving organic certification. 23 product SKUs affected across 6 retailers. OrganicFirst Foods. USDA/NOP compliance violation.', '10.100.30.42', '10.100.30.1', 7051, 7051, 'gRPC', 'oracle_node_svc', 'HYPERLEDGER-PROD', 'oracle-validator', 'hl-peer chaincode invoke --provenance', '["supply_chain", "blockchain_manipulation", "oracle_compromise", "organic_fraud", "traceability", "hyperledger", "cpg"]'::jsonb, '{"attack_type": "blockchain_oracle_manipulation", "brand": "OrganicFirst Foods", "platform": "Hyperledger", "skus_affected": 23, "retailers_affected": 6, "fraud_type": "False organic certification", "compliance_violation": "USDA/NOP", "region": "NA - West Coast", "brand_damage_usd": 15000000}'::jsonb, '{"event": "oracle_manipulation", "skus": 23, "retailers": 6, "false_cert": "organic"}'::jsonb, 'Apr 23 12:00:00 blockchain-monitor[3456]: HIGH supply_chain oracle_manipulation organic_fraud skus=23 retailers=6 INVESTIGATING', 'TA0040', 'T1565.002', NOW() - INTERVAL '2 hours');
