INSERT INTO trend_prds (prd_key, title, summary, motivation, non_goals, requirements, open_questions, acceptance, owning_feature, effort_days, risk, sort_order) VALUES
  ('kleene-gf-prod',
   'Kleene-closure productionization for GraphFrames',
   'Harden the experimental GraphFrames Kleene BFS into a supported, cluster-tested library module with predicate pushdown, early termination, and Delta checkpointing for long-running offline validation runs.',
   'The custom Kleene BFS from PRD kleene-gf is the offline oracle for the hot-path NFA. If the oracle has bugs, Phase 2 correctness is meaningless. We need a production-grade library the SOC engineers can trust.',
   ARRAY['Replacing GraphFrames with a new graph library','Supporting cyclic trends in v1','Scala UDF rewrite'],
   ARRAY['Packaged as oxdsi_trend_engine.kleene (pip-installable wheel)','Predicates applied pre-expansion; early-terminate on max_paths','Mid-run checkpoints to Delta; resumable','Stress-tested at 5M edges, depth 7, fanout 10','CI regression budget <10%'],
   ARRAY['Does AggregateMessages backpressure gracefully at 5M edges?','Custom shuffle partitioner for skewed graphs?','Oracle memory safety under pressure?'],
   ARRAY['Matches networkx all_simple_paths on 12 synthetic graphs','5M edges depth 7 on 4-node cluster <10min','Used as Phase 2 oracle in CI'],
   'Feature Lab / Agent Bricks (oracle validation)', 8, 'medium', 4),
  ('stam-spark-prod',
   'Skip-till-any-match NFA hardening for 100K EPS',
   'Production hardening of the custom NFA matcher: bounded state, spill-to-Lakebase, after-match skip strategies, and parity testing against Flink CEP.',
   'The initial NFA from PRD stam-spark must survive adversarial workloads. Without hardening, state grows unbounded and the stream falls behind.',
   ARRAY['Full Flink CEP parity','Custom pattern DSL beyond YAML','Cross-pattern composition'],
   ARRAY['Hard state ceiling per key; spill oldest partials to Lakebase','SKIP_PAST_LAST_EVENT and SKIP_TO_NEXT strategies','Partial-match metrics per microbatch','Flink CEP parity harness: 10 canonical patterns','Idempotent under replay'],
   ARRAY['Spill threshold tuning without hurting throughput?','Skip strategy conflicts with any-match?','Lakebase spill at 100K EPS?'],
   ARRAY['Sustains 100K EPS 1h, state <500MB/executor p95','Flink parity within 1%','72h soak test no OOM'],
   'Correlation Rules / Detection Confluence', 14, 'high', 5),
  ('bnb-partitioner-eval',
   'BnB partitioner evaluation framework',
   'Before building the full BnB partitioner, build the measurement rig that proves whether it is worth building.',
   'The paper claims 42x on synthetic benchmarks. Building a 15-day optimizer without first proving the ceiling is malpractice. This PRD is the kill-switch.',
   ARRAY['Implementing the optimizer','Online optimization','Non-monotonic predicate support'],
   ARRAY['Replay harness over 24h of red-team events','Evaluate greedy, random, optimal, no-sharing','Quantify speedup ceiling and plan-change frequency','Decision report: build BnB yes/no'],
   ARRAY['Is our workload monotonic enough?','How often does optimal plan change?','Realistic ceiling vs graphlet-sharing alone?'],
   ARRAY['Report delivered with measured ceiling','Go/no-go signed off before bnb-partitioner','Framework reusable for any optimizer'],
   'CET Trend Engine (internal)', 5, 'low', 6),
  ('depth-tier',
   'Deep Kleene path tier beyond 7 hops',
   'When trends exceed Spark state-store depth limit (~7), tier hot windows to Neo4j or TigerGraph via Lakebase-mediated handoff.',
   'APT kill chains span 8-15 hops over days. Spark state thrashes. Either cap depth or tier. This PRD picks tier, scoped to <2% of windows.',
   ARRAY['Replacing Spark with Neo4j for all workloads','General-purpose graph layer','Realtime <1s queries on the tier'],
   ARRAY['Routing rule: depth>7 or fanout>8 triggers tiered materialization','Subgraph handoff via Lakebase','Results flow back with provenance=external_tier','Cost cap <2% of windows','Engine choice documented (recommend Neo4j AuraDS)'],
   ARRAY['Which engine best fits Databricks VPC peering?','Can we avoid adding a vendor?','Is depth prediction reliable for routing?'],
   ARRAY['Captures trends depth 10+ Spark misses','Cost overhead <15% of baseline','Explicit provenance on every tiered trend'],
   'CET Trend Engine (tier extension)', 12, 'high', 7),
  ('graphlet-ttl',
   'Explicit TTL for graphlet state beyond watermark',
   'Spark state evicts only by watermark. Add explicit TTL on graphlets via the Lakebase warm-path cache.',
   'Stale graphlets inflate memory. Watermark-only eviction cannot express graphlet logic. Lakebase holds graphlets; add SQL TTL there.',
   ARRAY['Rewriting Spark state store','Forking Spark','TTL on hot-path RocksDB keys'],
   ARRAY['TTL policy DSL: max_age, max_unused_seconds, evict_if_reuse_ratio','Implemented as pg_cron job','Metrics: graphlets evicted/min, avg age','Cascade: purging invalidates dependent partials'],
   ARRAY['Right default TTL without dropping useful graphlets?','Per-query TTL policies?','Learn TTL from reuse history?'],
   ARRAY['Graphlet memory bounded under 24h load','No trend miss attributable to premature TTL','Policy DSL per tenant'],
   'CET Trend Engine (warm-path)', 6, 'low', 8),
  ('lakebase-hot-boundary',
   'Lakebase boundary enforcement and observability',
   'Enforce the hot/warm path boundary architecturally and monitor it so no future engineer accidentally puts Lakebase in the hot loop.',
   'The hybrid architecture works only if the boundary holds. A single misplaced Lakebase call in flatMapGroupsWithState tanks throughput silently. Need guardrails, not good intentions.',
   ARRAY['Replacing Lakebase with RocksDB everywhere','Moving hot-path state to Lakebase','Hiding latency via async (that is a lie)'],
   ARRAY['Lint rule: no direct Lakebase inside flatMapGroupsWithState','Runtime guard: wrapper rejects calls from hot-path threads','Latency histograms per call site; alert p99 >1ms','ADR enforced in PR template'],
   ARRAY['Reliably detect hot-path callers at runtime?','Fail hard or degrade gracefully?','New wrapper SDK?'],
   ARRAY['Zero hot-path Lakebase calls in production','CI catches violations','Dashboards show boundary health'],
   'CET Trend Engine / Platform SRE', 4, 'low', 9),
  ('cep-oracle',
   'CEP correctness oracle for CET semantics',
   'Build a hand-curated oracle of 20 canonical CET scenarios plus a property-based fuzzer for skip-till-any-match edge cases.',
   'Skip-till-any-match interacts with watermarks, duplicates, and partial-match eviction in non-obvious ways. Bugs here produce silent missed detections. An oracle is the only way to prove semantics.',
   ARRAY['Proving NFA correctness formally','Full property-based coverage','Cross-engine oracle (Flink parity is separate)'],
   ARRAY['20 curated scenarios with input + expected trends','Property-based fuzzer (Hypothesis)','Differential test: NFA vs GraphFrames Kleene offline','CI gate: any diff fails PR','Scenarios include watermark skew, out-of-order, duplicates'],
   ARRAY['How to pick 20 scenarios without gaming tests?','Is Hypothesis fast enough for streams?','Diff tolerance for non-determinism?'],
   ARRAY['20 scenarios green every PR','Fuzzer 10K sequences/night zero diffs','Regression blocks merge'],
   'QA / Feature Lab', 9, 'medium', 10),
  ('checkpoint-cost',
   'Changelog checkpointing cost optimization',
   'Reduce the ~15% CPU overhead of RocksDB changelog checkpointing via tuned interval, zstd compression, and selective checkpointing of hot keys.',
   '15% overhead is 15% cluster cost. At scale that is meaningful. Tuning is low-risk high-return.',
   ARRAY['Removing checkpointing (data loss unacceptable)','Custom checkpoint format','Cross-engine sync'],
   ARRAY['Checkpoint interval tuned per workload','zstd compression benchmarked','Selective checkpointing: hot keys more often','Rollback drill at any interval','Target overhead <7%'],
   ARRAY['Selective checkpointing complicate recovery?','zstd compatible with state store format?','Minimum safe checkpoint interval?'],
   ARRAY['100K EPS with <7% CPU overhead','Recovery drill passes from any checkpoint','Tuning guide published'],
   'Platform SRE', 5, 'low', 11)
ON CONFLICT (prd_key) DO NOTHING;