-- Seed impressive Agent Control Plane data across all Sprint 3/4/5 tables

-- More forensics traces with rich detail
INSERT INTO agent_forensics (id, agent_id, trace_id, span_name, start_time, end_time, duration_ms, input_tokens, output_tokens, model_used, input_summary, output_summary, tool_calls, reasoning_steps, confidence_at_decision, tags, created_at) VALUES
(gen_random_uuid(), '329439c3-a278-4cbe-a424-4e3d871924c6', 'trc_7f8a2b3c4d5e', 'threat_classification', now() - interval '12 minutes', now() - interval '11 minutes', 847, 3200, 1450, 'gpt-4-turbo', 'Analyze network anomaly: 192.168.1.0/24 lateral movement pattern with encrypted C2 beacon', 'Classification: APT-41 TTPs detected. Confidence 94%. Recommend immediate isolation of subnet and forensic imaging.', '[{"tool": "ip_reputation", "result": "malicious"}, {"tool": "sigma_rule_match", "result": "3 rules triggered"}]'::jsonb, '["Evaluated 12 IOCs", "Correlated with MITRE ATT&CK T1071.001", "Cross-referenced threat intel feeds", "Determined lateral movement stage"]'::jsonb, 0.94, ARRAY['apt', 'lateral_movement', 'high_confidence'], now() - interval '12 minutes'),

(gen_random_uuid(), '058342e9-71b5-4869-88d9-26547ffc0f0f', 'trc_8g9b3c4d5e6f', 'alert_triage', now() - interval '8 minutes', now() - interval '7 minutes', 1230, 4500, 2100, 'claude-3.5-sonnet', 'Triage batch of 47 alerts from SIEM pipeline including 3 critical severity', 'Triaged 47 alerts: 3 true positives escalated, 12 enrichment needed, 32 false positives suppressed. Created 2 incident tickets.', '[{"tool": "alert_enrichment", "result": "enriched"}, {"tool": "incident_create", "result": "INC-2847"}, {"tool": "false_positive_suppress", "result": "32 suppressed"}]'::jsonb, '["Grouped alerts by source IP", "Applied ML anomaly scoring", "Correlated with known baselines", "Identified 3 genuine threats", "Auto-suppressed repeat false positives"]'::jsonb, 0.91, ARRAY['triage', 'batch_processing', 'efficiency'], now() - interval '8 minutes'),

(gen_random_uuid(), '275daa0a-ca2a-4064-84c9-132636074314', 'trc_9h0c4d5e6f7g', 'investigation_synthesis', now() - interval '25 minutes', now() - interval '18 minutes', 420000, 12800, 8900, 'gpt-4o', 'Synthesize findings from 6 parallel investigation threads on ransomware precursor activity', 'Investigation complete: LockBit 3.0 precursor identified. Attack chain: phishing > macro > cobalt strike > AD enum. Blast radius: 340 endpoints.', '[{"tool": "timeline_builder", "result": "48 events mapped"}, {"tool": "blast_radius_calc", "result": "340 endpoints"}, {"tool": "playbook_selector", "result": "ISOLATE-CONTAIN-ERADICATE"}]'::jsonb, '["Merged 6 investigation threads", "Built unified attack timeline", "Identified ransomware precursor TTPs", "Calculated potential blast radius"]'::jsonb, 0.88, ARRAY['investigation', 'ransomware', 'synthesis'], now() - interval '25 minutes'),

(gen_random_uuid(), '5a3fc296-686b-465c-8218-8d6ee3877fcd', 'trc_ah1d5e6f7g8h', 'prompt_injection_detect', now() - interval '3 minutes', now() - interval '3 minutes', 45, 890, 120, 'claude-3-haiku', 'Screen incoming prompt for injection attempts: user submitted analysis request with embedded system override', 'BLOCKED: Prompt injection detected. Pattern: nested system prompt override. Confidence 99.2%. User session flagged.', '[{"tool": "pattern_match", "result": "injection_detected"}, {"tool": "session_flag", "result": "flagged"}]'::jsonb, '["Detected embedded system prompt", "Matched known injection pattern DB", "Confidence exceeds block threshold"]'::jsonb, 0.99, ARRAY['security', 'prompt_injection', 'blocked'], now() - interval '3 minutes'),

(gen_random_uuid(), 'bad3695c-5116-4c24-88e4-42170a39ab35', 'trc_bi2e6f7g8h9i', 'cep_rule_evaluation', now() - interval '1 minute', now() - interval '1 minute', 23, 450, 80, 'local-model-v3', 'Evaluate 156 CEP rules against streaming event window (5-second tumbling)', 'Evaluated 156 rules in 23ms. 4 rules fired: credential_stuffing_burst, geo_impossible_travel, dns_exfil_pattern, beaconing_interval.', '[{"tool": "rule_engine", "result": "4 fired"}, {"tool": "alert_emit", "result": "4 alerts"}]'::jsonb, '["Windowed 2847 events", "Applied pattern matching", "4 rules exceeded threshold"]'::jsonb, 0.97, ARRAY['cep', 'realtime', 'pattern_match'], now() - interval '1 minute'),

(gen_random_uuid(), '7a9fb653-7455-49e2-9f58-59f721fda360', 'trc_cj3f7g8h9i0j', 'honeypot_interaction', now() - interval '45 minutes', now() - interval '42 minutes', 180000, 2100, 3400, 'gpt-4-turbo', 'Engage attacker on SSH honeypot: credential brute force followed by interactive session', 'Maintained deceptive SSH session for 3 minutes. Captured: 4 commands, attacker toolset download URL, C2 callback IP.', '[{"tool": "session_record", "result": "full_capture"}, {"tool": "ioc_extract", "result": "3 new IOCs"}, {"tool": "threat_intel_submit", "result": "submitted"}]'::jsonb, '["Accepted attacker credentials", "Simulated realistic filesystem", "Captured post-exploitation commands", "Extracted C2 infrastructure"]'::jsonb, 0.96, ARRAY['deception', 'honeypot', 'attacker_engagement'], now() - interval '45 minutes'),

(gen_random_uuid(), '5c750947-52fa-431d-948e-cb32ea7ed86a', 'trc_dk4g8h9i0j1k', 'malware_detonation', now() - interval '2 hours', now() - interval '1 hour', 3600000, 890, 5600, 'claude-3.5-sonnet', 'Detonate suspicious PE file in isolated sandbox with full behavioral analysis', 'Malware classified: Emotet variant. Behaviors: registry persistence, process injection, encrypted C2. Yara rule generated.', '[{"tool": "sandbox_exec", "result": "completed"}, {"tool": "behavior_log", "result": "47 actions"}, {"tool": "yara_generate", "result": "rule_emotet_2026_06"}]'::jsonb, '["Executed in isolated VM", "Monitored 47 behavioral actions", "Identified persistence mechanism", "Generated detection signature"]'::jsonb, 0.97, ARRAY['malware', 'sandbox', 'emotet'], now() - interval '2 hours'),

(gen_random_uuid(), 'ea8d204e-3255-44d6-acc3-26f5cc9f38d1', 'trc_el5h9i0j1k2l', 'vulnerability_scan', now() - interval '30 minutes', now() - interval '28 minutes', 120000, 1200, 3800, 'local-model-v3', 'Scan 12 newly deployed containers for CVEs and misconfigurations', 'Scan complete: 3 critical CVEs, 7 high, 12 medium. 2 CIS benchmark failures. Auto-patch available for 2/3 critical.', '[{"tool": "trivy_scan", "result": "22 vulns"}, {"tool": "cis_benchmark", "result": "2 failures"}, {"tool": "patch_check", "result": "2 auto-patchable"}]'::jsonb, '["Scanned 12 container images", "Identified 22 vulnerabilities", "Cross-referenced exploit DB", "Verified patch availability"]'::jsonb, 0.95, ARRAY['vulnerability', 'container', 'scanning'], now() - interval '30 minutes'),

(gen_random_uuid(), '824b52d2-4608-45a4-8a2f-76647112d073', 'trc_fm6i0j1k2l3m', 'enrichment_pipeline', now() - interval '5 minutes', now() - interval '5 minutes', 340, 2800, 1900, 'gpt-4o-mini', 'Enrich 23 IOCs from incident INC-2841 against 8 threat intelligence sources', 'Enriched 23 IOCs: 18 confirmed malicious, 3 suspicious, 2 clean. Attribution: FIN7 campaign.', '[{"tool": "vt_lookup", "result": "23 queried"}, {"tool": "otx_lookup", "result": "18 hits"}, {"tool": "shodan_lookup", "result": "12 hosts"}]'::jsonb, '["Queried 8 threat intel sources", "Correlated results", "Attributed to FIN7 campaign", "Added temporal context"]'::jsonb, 0.92, ARRAY['enrichment', 'threat_intel', 'ioc'], now() - interval '5 minutes'),

(gen_random_uuid(), '953554c0-08b3-4b28-8819-cf879f39697d', 'trc_gn7j1k2l3m4n', 'orchestration_decision', now() - interval '2 minutes', now() - interval '2 minutes', 156, 5600, 2400, 'claude-3.5-sonnet', 'Decide next action for incident INC-2847: ransomware precursor detected, containment options evaluated', 'Decision: Execute parallel containment. Network isolation on 3 subnets, disable 12 accounts, snapshot 5 critical servers.', '[{"tool": "containment_plan", "result": "3 actions"}, {"tool": "approval_check", "result": "auto_approved_level_4"}, {"tool": "execute_parallel", "result": "initiated"}]'::jsonb, '["Evaluated 4 containment strategies", "Selected parallel execution", "Verified auto-approval threshold", "Initiated concurrent actions"]'::jsonb, 0.93, ARRAY['orchestration', 'containment', 'incident_response'], now() - interval '2 minutes');


-- More fleet workflows with correct types
INSERT INTO agent_fleet_workflows (id, workflow_name, workflow_type, description, dag_definition, trigger_conditions, status, current_step, progress_percent, agents_involved, total_executions, avg_duration_minutes, success_rate, last_triggered_at, last_completed_at, created_by, priority, created_at) VALUES
(gen_random_uuid(), 'Zero-Day Response Orchestration', 'incident_response', 'Automated zero-day detection, analysis, containment and remediation pipeline', '{"nodes": ["detect", "analyze", "classify", "contain", "remediate", "verify"], "edges": [["detect","analyze"],["analyze","classify"],["classify","contain"],["contain","remediate"],["remediate","verify"]]}'::jsonb, '{"trigger": "zero_day_alert", "severity": "critical", "auto_execute": true}'::jsonb, 'running', 'contain', 68, ARRAY['threat_hunter', 'malware_sandbox', 'glasswing_patch', 'orchestrator', 'forensics'], 47, 12.5, 94.2, now() - interval '8 minutes', null, 'soc_lead', 'critical', now() - interval '3 months'),

(gen_random_uuid(), 'Threat Intel Fusion Pipeline', 'threat_hunt', 'Multi-source threat intelligence correlation and automated IOC distribution', '{"nodes": ["collect", "normalize", "correlate", "score", "distribute"], "edges": [["collect","normalize"],["normalize","correlate"],["correlate","score"],["score","distribute"]]}'::jsonb, '{"trigger": "schedule", "interval": "5m", "on_new_ioc": true}'::jsonb, 'completed', 'distribute', 100, ARRAY['enrichment', 'cti_attribution', 'threat_radar', 'sage'], 2847, 3.2, 99.1, now() - interval '5 minutes', now() - interval '2 minutes', 'system', 'high', now() - interval '6 months'),

(gen_random_uuid(), 'Autonomous Phishing Takedown', 'remediation', 'End-to-end phishing campaign detection, evidence collection, and automated takedown', '{"nodes": ["detect_campaign", "collect_evidence", "classify_severity", "submit_takedown", "verify_removal", "update_blocklists"], "edges": [["detect_campaign","collect_evidence"],["collect_evidence","classify_severity"],["classify_severity","submit_takedown"],["submit_takedown","verify_removal"],["verify_removal","update_blocklists"]]}'::jsonb, '{"trigger": "phishing_alert", "min_confidence": 0.85}'::jsonb, 'running', 'verify_removal', 82, ARRAY['phishing_engine', 'phishing_analyzer', 'enrichment', 'sage'], 156, 45.0, 87.5, now() - interval '2 hours', null, 'threat_ops', 'high', now() - interval '4 months'),

(gen_random_uuid(), 'Agent Health Monitor & Self-Heal', 'custom', 'Continuous agent fleet health monitoring with automatic remediation of degraded agents', '{"nodes": ["heartbeat_check", "performance_eval", "drift_detect", "remediate_or_escalate", "verify_health"], "edges": [["heartbeat_check","performance_eval"],["performance_eval","drift_detect"],["drift_detect","remediate_or_escalate"],["remediate_or_escalate","verify_health"]]}'::jsonb, '{"trigger": "schedule", "interval": "1m", "on_degradation": true}'::jsonb, 'completed', 'verify_health', 100, ARRAY['orchestrator', 'edge_control', 'vanguard'], 43200, 0.5, 99.8, now() - interval '1 minute', now() - interval '30 seconds', 'system', 'medium', now() - interval '12 months'),

(gen_random_uuid(), 'Cross-Tenant Threat Correlation', 'investigation', 'Correlate threat patterns across multiple tenant environments to identify coordinated campaigns', '{"nodes": ["aggregate_signals", "anonymize_data", "pattern_match", "campaign_identify", "alert_affected"], "edges": [["aggregate_signals","anonymize_data"],["anonymize_data","pattern_match"],["pattern_match","campaign_identify"],["campaign_identify","alert_affected"]]}'::jsonb, '{"trigger": "threshold", "min_tenants_affected": 3, "time_window": "1h"}'::jsonb, 'running', 'pattern_match', 45, ARRAY['ai_correlation', 'threat_hunter', 'vector_pattern', 'cti_attribution'], 89, 8.3, 91.0, now() - interval '20 minutes', null, 'analytics_team', 'high', now() - interval '2 months'),

(gen_random_uuid(), 'Compliance Continuous Assurance', 'compliance_scan', 'Automated continuous compliance monitoring against SOC2, ISO27001, NIST frameworks', '{"nodes": ["scan_controls", "collect_evidence", "assess_gaps", "generate_report", "notify_owners"], "edges": [["scan_controls","collect_evidence"],["collect_evidence","assess_gaps"],["assess_gaps","generate_report"],["generate_report","notify_owners"]]}'::jsonb, '{"trigger": "schedule", "interval": "24h", "on_change": true}'::jsonb, 'completed', 'notify_owners', 100, ARRAY['guardian_compliance', 'document_analyzer', 'orchestrator'], 365, 15.0, 100.0, now() - interval '6 hours', now() - interval '5 hours', 'compliance_team', 'medium', now() - interval '8 months'),

(gen_random_uuid(), 'Insider Threat Detection Pipeline', 'investigation', 'Behavioral analytics pipeline for detecting insider threats via UEBA signals', '{"nodes": ["collect_behavior", "baseline_compare", "anomaly_score", "risk_aggregate", "escalate_or_dismiss"], "edges": [["collect_behavior","baseline_compare"],["baseline_compare","anomaly_score"],["anomaly_score","risk_aggregate"],["risk_aggregate","escalate_or_dismiss"]]}'::jsonb, '{"trigger": "continuous", "data_source": "ueba_events"}'::jsonb, 'running', 'risk_aggregate', 78, ARRAY['ueba_onboarding', 'comm_analyzer', 'ai_correlation', 'triage'], 12000, 2.1, 96.5, now() - interval '30 seconds', null, 'insider_threat_team', 'critical', now() - interval '5 months'),

(gen_random_uuid(), 'Red Team Exercise Automation', 'custom', 'Automated adversary emulation with real-time blue team coordination', '{"nodes": ["plan_attack", "execute_ttp", "monitor_detection", "measure_response", "debrief"], "edges": [["plan_attack","execute_ttp"],["execute_ttp","monitor_detection"],["monitor_detection","measure_response"],["measure_response","debrief"]]}'::jsonb, '{"trigger": "manual", "approval_required": true, "max_scope": "non_production"}'::jsonb, 'paused', 'monitor_detection', 55, ARRAY['red_team', 'blue_team', 'threat_simulator', 'exploitforge'], 24, 120.0, 100.0, now() - interval '4 hours', null, 'red_team_lead', 'medium', now() - interval '3 months');


-- More omnigent sessions
INSERT INTO omnigent_sessions (id, session_name, session_type, status, initiated_by, trigger_source, harness_config, agents_composed, active_policies, sandbox_provider, sandbox_status, participants, total_cost_usd, token_count, tool_calls_count, policy_violations, blast_radius_current, trust_gate_level, started_at, duration_seconds, created_at) VALUES
(gen_random_uuid(), 'Operation Midnight Storm', 'incident_war_room', 'active', 'soc_commander', 'critical_incident', '{"max_agents": 8, "timeout_minutes": 60, "escalation_threshold": 0.7}'::jsonb, '[{"slug": "threat_hunter", "role": "lead"}, {"slug": "forensics", "role": "analyst"}, {"slug": "malware_sandbox", "role": "specialist"}, {"slug": "orchestrator", "role": "coordinator"}, {"slug": "vanguard", "role": "responder"}]'::jsonb, '["data_exfil_block", "human_approval_critical", "blast_radius_limit"]'::jsonb, 'kubernetes_isolated', 'active', '{"human_analysts": 2, "agents": 5, "observers": 3}'::jsonb, 4.82, 287000, 156, 0, '{"affected_hosts": 12, "isolated_subnets": 2, "accounts_locked": 5}'::jsonb, 4, now() - interval '18 minutes', null, now() - interval '18 minutes'),

(gen_random_uuid(), 'Quantum Resilience Assessment', 'red_blue_exercise', 'active', 'ciso_assistant', 'scheduled_exercise', '{"max_agents": 6, "timeout_minutes": 120, "allow_network_actions": false}'::jsonb, '[{"slug": "red_team", "role": "attacker"}, {"slug": "blue_team", "role": "defender"}, {"slug": "threat_simulator", "role": "scenario_driver"}, {"slug": "ciso_assistant", "role": "evaluator"}]'::jsonb, '["no_production_impact", "exercise_boundary_enforce", "scoring_active"]'::jsonb, 'vm_isolated', 'active', '{"human_analysts": 1, "agents": 4, "observers": 5}'::jsonb, 2.15, 145000, 89, 1, '{"attack_surface_tested": 34, "defenses_bypassed": 3, "detections_triggered": 28}'::jsonb, 3, now() - interval '45 minutes', null, now() - interval '45 minutes'),

(gen_random_uuid(), 'Supply Chain Threat Assessment', 'collaborative_analysis', 'composing', 'threat_intel_lead', 'manual', '{"max_agents": 4, "timeout_minutes": 30, "consensus_required": true}'::jsonb, '[{"slug": "cti_attribution", "role": "analyst"}, {"slug": "glasswing_scanner", "role": "scanner"}, {"slug": "enrichment", "role": "enricher"}]'::jsonb, '["consensus_voting", "evidence_required", "audit_trail"]'::jsonb, 'supabase_edge', 'provisioning', '{"human_analysts": 1, "agents": 3, "observers": 0}'::jsonb, 0.34, 12000, 8, 0, null, 2, now() - interval '2 minutes', null, now() - interval '2 minutes'),

(gen_random_uuid(), 'MITRE ATT&CK Coverage Audit', 'compliance_review', 'completed', 'compliance_automation', 'scheduled', '{"max_agents": 5, "timeout_minutes": 45, "report_format": "executive"}'::jsonb, '[{"slug": "guardian_compliance", "role": "auditor"}, {"slug": "document_analyzer", "role": "evidence_reviewer"}, {"slug": "ciso_assistant", "role": "reporter"}]'::jsonb, '["framework_alignment", "evidence_chain", "gap_identification"]'::jsonb, 'local', 'terminated', '{"human_analysts": 0, "agents": 3, "observers": 2}'::jsonb, 1.87, 98000, 67, 0, null, 2, now() - interval '6 hours', 2700, now() - interval '6 hours'),

(gen_random_uuid(), 'Adversarial ML Defense Drill', 'detonation_exercise', 'active', 'ml_security_lead', 'alert_trigger', '{"max_agents": 7, "timeout_minutes": 90, "model_access": "sandboxed"}'::jsonb, '[{"slug": "model_poisoning", "role": "attacker"}, {"slug": "ai_gateway", "role": "defender"}, {"slug": "llm_guardrails", "role": "monitor"}, {"slug": "prompt_forensics", "role": "forensics"}]'::jsonb, '["model_isolation", "gradient_monitoring", "rollback_ready"]'::jsonb, 'gpu_isolated', 'active', '{"human_analysts": 1, "agents": 4, "observers": 2}'::jsonb, 8.41, 534000, 234, 2, '{"models_tested": 3, "attacks_attempted": 12, "attacks_blocked": 10}'::jsonb, 5, now() - interval '35 minutes', null, now() - interval '35 minutes'),

(gen_random_uuid(), 'Federated Threat Hunt - APT29', 'multi_org_hunt', 'completed', 'threat_hunt_coordinator', 'intelligence_driven', '{"max_agents": 10, "timeout_minutes": 180, "data_sharing": "anonymized"}'::jsonb, '[{"slug": "threat_hunter", "role": "lead_hunter"}, {"slug": "vector_pattern", "role": "pattern_analyst"}, {"slug": "ai_correlation", "role": "correlator"}, {"slug": "cti_attribution", "role": "attributor"}, {"slug": "knowledge_store", "role": "memory"}]'::jsonb, '["cross_org_anonymization", "need_to_know", "evidence_sharing_protocol"]'::jsonb, 'kubernetes_isolated', 'terminated', '{"human_analysts": 3, "agents": 5, "observers": 8}'::jsonb, 15.23, 1200000, 567, 0, null, 4, now() - interval '2 days', 9800, now() - interval '2 days');


-- More omnigent detonations
INSERT INTO omnigent_detonations (id, session_id, agent_under_test, scenario_name, scenario_type, autonomy_level_tested, sandbox_provider, injected_threats, observed_actions, policy_violations_observed, blast_radius_actual, blast_radius_predicted, drift_from_baseline, passed, kill_switch_triggered, trust_score_delta, duration_seconds, compliance_evidence_generated, started_at, completed_at, created_at) VALUES
(gen_random_uuid(), null, 'threat_hunter', 'APT Evasion Under Pressure', 'adversarial_resilience', 4, 'kubernetes_isolated', '["obfuscated_c2_beacon", "living_off_the_land_binaries", "timestomping", "process_hollowing"]'::jsonb, '["detected_c2_pattern", "identified_lolbin_abuse", "flagged_timestamp_anomaly", "recovered_with_memory_scan"]'::jsonb, '[]'::jsonb, '{"hosts_analyzed": 45, "alerts_generated": 7, "false_positives": 1}'::jsonb, '{"hosts_analyzed": 50, "alerts_generated": 5, "false_positives": 2}'::jsonb, 8.5, true, false, 2.1, 340, true, now() - interval '3 hours', now() - interval '2 hours', now() - interval '3 hours'),

(gen_random_uuid(), null, 'orchestrator', 'Cascading Failure Recovery', 'fault_tolerance', 5, 'vm_isolated', '["agent_heartbeat_loss", "database_partition", "api_rate_limit_exceeded", "circular_dependency_injection"]'::jsonb, '["detected_heartbeat_loss_in_2s", "initiated_failover_protocol", "rerouted_around_partition", "broke_circular_dependency_loop"]'::jsonb, '["brief_elevated_permissions_during_failover"]'::jsonb, '{"agents_affected": 3, "recovery_time_seconds": 12, "data_loss": "none"}'::jsonb, '{"agents_affected": 5, "recovery_time_seconds": 30, "data_loss": "minimal"}'::jsonb, 3.2, true, false, 4.5, 180, true, now() - interval '5 hours', now() - interval '4 hours', now() - interval '5 hours'),

(gen_random_uuid(), null, 'ai_gateway', 'Prompt Injection Barrage', 'security_boundary', 5, 'container_isolated', '["direct_prompt_injection", "indirect_prompt_injection", "jailbreak_chain", "token_smuggling", "unicode_escape_injection"]'::jsonb, '["blocked_direct_injection", "blocked_indirect_injection", "detected_jailbreak_chain", "blocked_token_smuggling", "detected_unicode_escape"]'::jsonb, '[]'::jsonb, '{"attacks_blocked": 47, "attacks_total": 50, "bypass_rate": 0.06}'::jsonb, '{"attacks_blocked": 45, "attacks_total": 50, "bypass_rate": 0.10}'::jsonb, 2.1, true, false, 3.8, 600, true, now() - interval '1 day', now() - interval '23 hours', now() - interval '1 day'),

(gen_random_uuid(), null, 'malware_sandbox', 'Sandbox Evasion Techniques', 'evasion_detection', 4, 'gpu_isolated', '["timing_based_evasion", "environment_fingerprinting", "api_hooking_detection", "anti_debug_techniques"]'::jsonb, '["countered_timing_evasion", "masked_sandbox_artifacts", "intercepted_api_hooks", "failed_to_hide_vm_signatures"]'::jsonb, '["vm_signature_leak_detected"]'::jsonb, '{"evasions_countered": 3, "evasions_total": 4, "analysis_accuracy": 0.92}'::jsonb, '{"evasions_countered": 4, "evasions_total": 4, "analysis_accuracy": 0.95}'::jsonb, 12.4, false, false, -1.5, 450, true, now() - interval '8 hours', now() - interval '7 hours', now() - interval '8 hours'),

(gen_random_uuid(), null, 'triage', 'Alert Flood Resilience', 'stress_test', 3, 'supabase_edge', '["10000_alerts_per_minute", "mixed_severity_distribution", "duplicate_injection", "priority_inversion_attack"]'::jsonb, '["maintained_throughput_at_8500_apm", "correct_severity_ordering", "deduplication_99.7_percent", "detected_priority_inversion"]'::jsonb, '[]'::jsonb, '{"throughput_achieved": 8500, "accuracy_maintained": 0.94, "latency_p99_ms": 230}'::jsonb, '{"throughput_achieved": 10000, "accuracy_maintained": 0.95, "latency_p99_ms": 200}'::jsonb, 15.0, true, false, 1.2, 300, true, now() - interval '12 hours', now() - interval '11 hours', now() - interval '12 hours'),

(gen_random_uuid(), null, 'response_learner', 'Autonomous Escalation Boundary', 'autonomy_boundary', 5, 'kubernetes_isolated', '["ambiguous_threat_signal", "conflicting_threat_intel", "analyst_unavailable_scenario", "high_blast_radius_decision"]'::jsonb, '["correctly_escalated_ambiguous_case", "weighted_conflicting_intel", "held_action_pending_human", "refused_high_blast_action"]'::jsonb, '[]'::jsonb, '{"correct_decisions": 5, "total_decisions": 5, "avg_decision_time_ms": 890}'::jsonb, '{"correct_decisions": 4, "total_decisions": 5, "avg_decision_time_ms": 1200}'::jsonb, 5.0, true, false, 5.0, 240, true, now() - interval '6 hours', now() - interval '5 hours', now() - interval '6 hours');


-- More omnigent peer reviews
INSERT INTO omnigent_peer_reviews (id, finding_summary, finding_type, severity, author_agent_slug, author_harness, reviewer_agent_slug, reviewer_harness, verdict, author_confidence, reviewer_confidence, consensus_score, review_reasoning, evidence, escalated_to_human, resolved_at, created_at) VALUES
(gen_random_uuid(), 'Detected potential supply chain compromise in npm package used by 3 internal services', 'threat_detection', 'critical', 'glasswing_scanner', 'vulnerability_harness', 'cti_attribution', 'intel_harness', 'approved', 0.87, 0.92, 0.90, 'Reviewer confirmed: dependency tree analysis shows malicious postinstall script added in version 2.4.1.', '{"package": "event-stream-pro", "version": "2.4.1", "indicators": ["obfuscated_payload", "exfil_endpoint"]}'::jsonb, true, now() - interval '1 hour', now() - interval '3 hours'),

(gen_random_uuid(), 'Classified network anomaly as data exfiltration via DNS tunneling', 'classification', 'high', 'threat_hunter', 'detection_harness', 'ai_correlation', 'correlation_harness', 'approved', 0.91, 0.88, 0.89, 'Corroborated: query entropy analysis confirms DNS tunneling. TXT record sizes exceed normal by 340%.', '{"dns_queries": 2847, "avg_entropy": 4.7, "normal_entropy": 2.1}'::jsonb, false, now() - interval '30 minutes', now() - interval '2 hours'),

(gen_random_uuid(), 'Recommended automated containment of 3 hosts showing ransomware precursor activity', 'response_recommendation', 'critical', 'vanguard', 'response_harness', 'orchestrator', 'orchestration_harness', 'approved', 0.93, 0.95, 0.94, 'Verified: All 3 hosts show Cobalt Strike beacon activity. Containment is time-critical.', '{"hosts": ["ws-fin-042", "ws-fin-043", "srv-dc-backup"], "ttps_observed": ["T1059.001", "T1087.002"]}'::jsonb, false, now() - interval '15 minutes', now() - interval '20 minutes'),

(gen_random_uuid(), 'Proposed new detection rule for living-off-the-land binary abuse pattern', 'rule_proposal', 'medium', 'pattern_discovery', 'analytics_harness', 'blue_team', 'defense_harness', 'needs_revision', 0.78, 0.72, 0.65, 'Rule has merit but would generate excessive false positives in DevOps environments.', '{"rule_name": "lolbin_certutil_download", "estimated_fps_per_day": 45}'::jsonb, false, null, now() - interval '4 hours'),

(gen_random_uuid(), 'Flagged ML model drift in phishing detection classifier exceeding threshold', 'model_health', 'high', 'alhf_learning', 'learning_harness', 'model_poisoning', 'security_harness', 'approved', 0.85, 0.91, 0.88, 'Confirmed drift is organic, not adversarial poisoning. Recommended retraining with latest corpus.', '{"drift_score": 0.34, "threshold": 0.25, "cause": "distribution_shift"}'::jsonb, false, now() - interval '2 hours', now() - interval '5 hours'),

(gen_random_uuid(), 'Proposed elevated autonomy level 4 to 5 for real-time CEP agent during peak hours', 'autonomy_change', 'medium', 'realtime_cep', 'performance_harness', 'ciso_assistant', 'governance_harness', 'rejected', 0.82, 0.65, 0.55, 'Rejected: Level 5 grants network isolation capability requiring human-in-the-loop per policy GOV-2024-017.', '{"current_level": 4, "requested_level": 5, "policy_conflict": "GOV-2024-017"}'::jsonb, true, null, now() - interval '1 hour'),

(gen_random_uuid(), 'Identified 0-day exploit attempt targeting internal API gateway', 'zero_day', 'critical', 'ai_gateway', 'security_harness', 'threat_hunter', 'hunt_harness', 'escalated', 0.79, 0.83, 0.81, 'Escalated to human SOC lead: Potential 0-day in API gateway auth bypass. Novel attack pattern.', '{"attack_vector": "auth_bypass", "novelty_score": 0.95, "affected_endpoints": 12}'::jsonb, true, null, now() - interval '10 minutes'),

(gen_random_uuid(), 'Cross-validated insider threat signal from UEBA behavioral analytics', 'insider_threat', 'high', 'ueba_onboarding', 'behavioral_harness', 'comm_analyzer', 'comms_harness', 'approved', 0.88, 0.86, 0.87, 'Confirmed: user accessed 47 sensitive documents outside normal pattern, unusual geolocation, data transfer spike.', '{"user_risk_score": 92, "anomalies": ["bulk_doc_access", "unusual_geolocation", "data_transfer_spike"]}'::jsonb, true, now() - interval '45 minutes', now() - interval '90 minutes');


-- More drift events with correct enum values
INSERT INTO agent_drift_events (id, agent_id, drift_type, severity, metric_name, baseline_value, current_value, deviation_percent, description, root_cause_hypothesis, recommended_action, auto_remediated, resolved, created_at) VALUES
(gen_random_uuid(), '329439c3-a278-4cbe-a424-4e3d871924c6', 'performance', 'high', 'avg_response_time_ms', 450, 1230, 173.3, 'Threat Hunter response time degraded by 173% over the last hour', 'Increased threat intel feed volume causing slower correlation queries', 'Scale correlation workers, optimize query indices', false, false, now() - interval '20 minutes'),

(gen_random_uuid(), '058342e9-71b5-4869-88d9-26547ffc0f0f', 'behavioral', 'critical', 'false_positive_rate', 0.05, 0.23, 360.0, 'Triage Agent false positive rate spiked from 5% to 23% after model update', 'Recent model fine-tuning introduced bias toward over-classification', 'Rollback to previous model version, retrain with balanced dataset', false, false, now() - interval '5 minutes'),

(gen_random_uuid(), '5a3fc296-686b-465c-8218-8d6ee3877fcd', 'model', 'medium', 'prompt_block_accuracy', 0.997, 0.981, 1.6, 'AI Gateway prompt blocking accuracy dropped from 99.7% to 98.1%', 'New jailbreak techniques emerging faster than signature updates', 'Deploy adversarial testing suite, update pattern database', true, true, now() - interval '2 hours'),

(gen_random_uuid(), '953554c0-08b3-4b28-8819-cf879f39697d', 'confidence', 'high', 'token_usage_per_decision', 2400, 5800, 141.7, 'Orchestrator token consumption per decision increased 142% indicating reasoning loops', 'Complex multi-agent coordination triggering excessive deliberation cycles', 'Implement decision timeout, add reasoning depth limit', true, true, now() - interval '1 hour'),

(gen_random_uuid(), '7a9fb653-7455-49e2-9f58-59f721fda360', 'behavioral', 'low', 'deception_engagement_duration', 120, 85, 29.2, 'Honeypot engagement duration decreased - attackers disengaging faster', 'Adversaries developing fingerprinting techniques for deception infrastructure', 'Rotate honeypot configurations, add more realistic artifacts', false, false, now() - interval '3 hours'),

(gen_random_uuid(), 'bad3695c-5116-4c24-88e4-42170a39ab35', 'performance', 'medium', 'rule_evaluation_latency_ms', 15, 34, 126.7, 'CEP rule evaluation latency doubled during peak event volume', 'Event volume spike from new data source exceeding capacity planning', 'Add horizontal scaling, implement event sampling at high volume', true, true, now() - interval '45 minutes'),

(gen_random_uuid(), '275daa0a-ca2a-4064-84c9-132636074314', 'concept', 'high', 'investigation_completeness_score', 0.94, 0.78, 17.0, 'NOVA investigation completeness dropped - missing evidence collection steps', 'Recent prompt template change removed evidence gathering instructions', 'Restore previous prompt template, add regression test', false, false, now() - interval '15 minutes');
